### ISSUE TITLE
Add the ability to sort the list of application services by the number of services running

### ISSUE THREAD

**Issue by Pahomk** [MuntashirAkon/AppManager#1004]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

In the list of application services, it would be very useful to be able to sort the list by the number of services running.

AppManager can already sort services, but AppManager does not sort by number of services running.

### Describe the solution you'd like

- Sorting/filter the list of application services by the number of running services
- Inverse sorting/filter the list of application services by the number of running services

### Describe alternatives you've considered

There is an application that is similar in functionality to AppManager, but it is no longer being developed. This application is called: MyAndroidTools. 
MyAndroidTools has a list of application services. This list can be sorted by the number of running application services. This is what I miss so much about AppManager.

![Screenshot](https://user-images.githubusercontent.com/115905749/219962414-ec36b401-6484-4068-a5c3-801195cdaed2.png)

**Comment by MuntashirAkon** [comment]
We have no plans to implement such a feature:

Number of running services is _not_ a useful information because the memory consumption is calculated per process, not per service. So, it does not really matter how many services are running in a process. For each process, the running services are not currently listed in the Running Apps page but it is planned for a future release. You can currently view it from the **App Details page** of the corresponding app from the Running Apps page.
