### ISSUE TITLE
On the apps list, I need to know which apps has already saved by "Save APK" 

### ISSUE THREAD

**Issue by sobaee** [MuntashirAkon/AppManager#1019]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Hello MuntashirAkon
I hope you are fine

Dear developer

On the apps list; I need the saved apps (by "Save APK" function) to be labeled "Saved" below the app icon for example, [To have the same behavior as the backup function; i.e. the app will be labeled "Backup" below its icon if backup has already done for it]

I will show you a picture:
![Screenshot_20230306004622](https://user-images.githubusercontent.com/65910585/222988273-7bc84a32-cc5e-40d9-affa-3bfcb7f5afa7.jpg)

Thanks a lot

**Comment by MuntashirAkon** [comment]
> On the apps list; I need the saved apps (by "Save APK" function) to be labeled "Saved" below the app icon for example, [To have the same behavior as the backup function; i.e. the app will be labeled "Backup" below its icon if backup has already done for it]

**Save APK** is never meant to be a part of App Manager functionality, a common directory is selected only because when it was implemented, it deemed unnecessary to do so (but it's still possible to allow the user to chose any directory to export the APK files. If you want to manage APK files, use backup/restore feature but with only **APK files** flag selected which works in all modes of operation, and perfectly align with what you want.

Still, this is a good question because I think the title "Save APK" is misleading and should be replaced by other meaningful word such as **Export APK**

**Comment by sobaee** [comment]
Okay

I don't mean to choose the directory, bro, it's no problem to be as it is right now.

About backup/restore, yes it's the same as I want, but I need the app to be saved in SD card as .apk or .apks file for splits, not in compressed manner.

Just think about my suggestion, this will replace all other apk backup apps.

**Comment by MuntashirAkon** [comment]
> About backup/restore, yes it's the same as I want, but I need the app to be saved in SD card as .apk or .apks file, not in compressed manner.

You can easily get the real APK file by uncompressing the file (or better install them using App Manager itself) or even ensure the integrity of the files by encrypting them. Developing a duplicate functionality simply does not worth the effort for several reasons:

1. Since APK files are stored in a shared directory, there are always chances of modification (e.g. insertion of spyware/ransomware) by a malicious software without you even knowing it. You might think this to be far fetched, but it's not actually that difficult. (There are even some PoC projects in GitHub that allows you to inject malware into the APK.)
2. We already provide a better alternative, namely backup/restore, which is designed cleverly to avoid security issues like the one mentioned above.
3. We use extensive caching mechanism to ensure that the app list in the main page loads quite fast (old users of App manager knows how long it took to load the list of app). Adding features such as this would increase the caching overhead as the files are located in a shared storage, thus, we do not have any control over those files.
4. This bears all the sign of xy problem, that is, you're trying to solve an issue without talking about the real issue. Instead you're talking about another issue that _you think_ might solve the real issue.

> Just think about my suggestion, this will replace all other apk backup apps.

It's not just about replacing other apps, it's also about doing things in a way that is beneficial to the users in the long run. In this case, the simple APK saving applications (which are usually developed by new developers for practising development in Android) are simply doing it incorrectly as they are failing to ensure the integrity of their saved apps.
