### ISSUE TITLE
AppOps bug

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#1024]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When toggling ACCESS_FINE_LOCATION(and some other AppOps) on and off,we do not end up with the desirable result.
Also AM doesn't seem to properly update the state of the given AppOpp(here ACCESS_FINE_LOCATION)

### To Reproduce

1)Open any app which uses certain permissions(only some of them seem to have this issue one of them is  ACCESS_FINE_LOCATION )
2)Toggle the AppOpp on or off and notice the if the appopp really got toggled on or off (i did this by using the in-built AppInfo)

### Expected behavior

AM should properly update the state of an AppOpp and the toggle should properly switch on or off

### Logs

[AppOpp_bug.zip](https://github.com/MuntashirAkon/AppManager/files/10939456/AppOpp_bug.zip)

### Device info

- Device:RMX2061
- OS Version:A11
- App Manager Version:3.1.0-beta2-DEBUG
- Mode: Root

### ScreenRecording

https://user-images.githubusercontent.com/72438196/224348832-de4a76cf-6283-423f-bb6d-557ac3521aac.mp4

**Comment by kryptobolt200528** [comment]
Might be a possible duplicate of #712

**Comment by MuntashirAkon** [comment]
> Here i attach a video depicting the bug:

Wrong video❓

**Comment by kryptobolt200528** [comment]
> > Here i attach a video depicting the bug:
> 
> Wrong video❓

yeah.kinda didn't notice(have updated it)

**Comment by MuntashirAkon** [comment]
Thanks for the video and steps to reproduce the behaviour. I am quite aware of the issue though its not really an issue per se. The reason for this issue is App Manager providing a low-level view of permissions in Android than, say, the Setting app.

Location is composed of two permissions and two app ops for location and precise location respectively, the combinations of which imply different meaning and behaviour depending on Android version. In this particular Android version, the location permission should _only_ be operated through permissions, not app ops. This is why you get interesting and ambiguous results when you try to modify app ops as the system, upon receiving invalid inputs, declines to process them. And even if you change the app ops, there is no guarantee that the app will be able to access location because it also depends on location permissions too. But if you insist:
1. First you need to know that `ACCESS_FINE_LOCATION` app op depends on `ACCESS_COARSE_LOCATION` app op. Both works simultaneously along with the _corresponding permissions_. As a result, the app op `ACCESS_FINE_LOCATION` changes the behaviour of `ACCESS_COARSE_LOCATION` instead of itself.
2. When you change `ACCESS_FINE_LOCATION` to values such as _foreground_ or _ignore_, it toggles `ACCESS_COARSE_LOCATION` app op and the `ACCESS_FINE_LOCATION` permission. This essentially done by the framework to ensure that the app can access precise location.
3. When you change `ACCESS_COARSE_LOCATION` to _allow_ or _ignore_, it toggles the corresponding permission as well. This is the default or expected behaviour, except that the input pattern has to be very specific.

Ideally, it should be possible to inform the user regarding these behaviours, but in reality, we can't, because the amount of investigation needed to figure out all the behaviour changes since Android 5 (across 14 versions) does not worth the effort. I wish somebody would help me, but again, the reality is, there is nobody else.

**Comment by kryptobolt200528** [comment]
I appreciate the detailed response and am satisfied with the answer thank you dev👍.

**Comment by kryptobolt200528** [comment]
I am not aware about the ethical state of the following project but it does provide a good faq page which is also applicable in to Appmanager
:https://mirfatif.github.io/PermissionManagerX/help/en/#faq37

**Comment by MuntashirAkon** [comment]
> I am not aware about the ethical state of the following project but it does provide a good faq page which is also applicable in to Appmanager(for anyone interested in further details) :https://mirfatif.github.io/PermissionManagerX/help/en/#faq37

PMX is an open source software featuring only permissions (and app ops).
