### ISSUE TITLE
KNOX mode for Samsung devices

### ISSUE THREAD

**Issue by AuYoku** [MuntashirAkon/AppManager#1057]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Add KNOX mode support for Samsung devices,PLZ.

**Comment by MuntashirAkon** [comment]
What is it that you exactly want from App Manager regarding KNOX?

**Comment by AuYoku** [comment]
> 

I want to disabled App components and Uninstall/Enable/Disable Apps.
![Uploading Screenshot_20230503_135918_App Manager.png…]()

**Comment by MuntashirAkon** [comment]
Sorry, I've no idea how to deal with KNOX issues. Maybe if you shared some resources on how these functions might be controlled, then I might consider this. Otherwise, I can't do anything about it.

**Comment by ascendbeing** [comment]
I don't think you can do this in 2023.

"Samsung, an OEM partner of 42Gears has decided to deprecate the support for ELM (Enterprise License management) and KLM (KNOX License Management) license keys due to security purposes and will be supporting KPE (KNOX Platform for Enterprise) licenses in the future. The end of service for ELM and KLM license keys will be at the end of December 2020. This calls for certain changes in products."

You used to see people rolling their own Knox based AdBlock softwares but after Dec 2020 it died down. You have to have money and/or connections to do anything with Knox nowadays afaik
