### ISSUE TITLE
wrong App version displayed in the search

### ISSUE THREAD

**Issue by Sami32** [MuntashirAkon/AppManager#1065]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Not actual, fresh App version value is displayed when browsing the applications

### To Reproduce

1 - go to the search bar and look at a newly updated App
2 - select this App and compare the displayed version with the previous one

### Expected behavior

The version of the same application should have the same value.

### Screenshots

![IMG_20230514_202046](https://github.com/MuntashirAkon/AppManager/assets/18471069/1b9bf0f2-86d5-4940-b973-844f6a8795d1)
![IMG_20230514_202019](https://github.com/MuntashirAkon/AppManager/assets/18471069/a495661c-6d73-404a-956b-6561b5ea7a85)

### Device info

- Device: Xiami Redmi Note 4
- OS Version: Android 7.0 MIUI 11
- App Manager Version: 3.1.0
- Mode: NonRoot

### Additional context

No Google Play services
MIUI UI disabled

**Comment by Sami32** [comment]
Ok my screen capture has been taken later so the version has been updated...

**Comment by MuntashirAkon** [comment]
App Manager uses cache to load app info in order to improve the startup time. So, if an app is updated, it would take a few seconds or more (depending on the number of apps you have and other factors such as backups made) to update the cache with latest info. So, this behaviour is expected. In App Details page, no caching takes place (other than images) which means you get mostly fresh info there unless, of course, there's a caching issue in Android framework itself (which isn't uncommon).
