### ISSUE TITLE
App not useable if notification is not allowed

### ISSUE THREAD

**Issue by privacyonly** [MuntashirAkon/AppManager#1092]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Unable to press anything inside the app while starting for the first time, If I don't allow notification.

### To Reproduce

1. download and install App Manager v3.1.1 Stable
2. keystore close
3. do not allow notification
4. try ticking disclaimer checkbox "Never Show this again"

- download and install App Manager v3.1.0 Stable
- keystore close
- do not allow notification
- try ticking disclaimer checkbox "Never Show this again"

1. download and install App Manager v3.0.4
2. keystore close
3. tick disclaimer checkbox "Never Show this again"
4. I Agree
5. Update to App Manager v3.1.0 Stable
6. do not allow notification
7. I can scroll but not do anything

### Expected behavior

I installed App Manager v3.0.4 and everything works perfectly because it doesn't ask notification access.
So I expect the apps to work when I press do not allow notification

### Screenshots

Screenshot can't show apps that doesn't work.

### Logs

no logs

### Device info

- Device: Samsung S21 Ultra SM-G998B
- OS Version: Android 13 one ui 5.1 May security Update
- App Manager Version: 3.1.0 stable
- Mode: ADB & NonRoot

### Additional context

I tested this on another Samsung tablet, it didn't ask for notification access Android 11 one ui 3.1 December 2022 update.

**Comment by MuntashirAkon** [comment]
Notification permission is a runtime permission since Android 13 for apps that targets Android 13 (SDK 33 and later). Since v3.0.4 targeted SDK 32, the permission was granted by default. v3.1.0 targets SDK 33 meaning it requires that permission in order for it to work. Without the permission, App Manager cannot effectively perform any tasks such as installation, batch operations, profiles, freeze/unfreeze etc. that require user interaction (and also as a side effect, the user will not know what App Manager's actually doing which is a breach of user's privacy and right to be informed). Hence, there's no point in using App Manager without granting that permission. In case you're wondering, Notification permission is not related to privacy at all (on the contrary, the user will be in the dark about the foreground services that used to display a notification to inform user about what the app is doing). Google only added it to reduce the amount of notification received by the user as well as to have a more control over power management.

**Comment by MuntashirAkon** [comment]
> it is just that the notification is going to be sent to my smartwatch, adding a little annoyance

I've reduced some annoyance in b645e34adc82b0c81a60a2502fd46ce086590028. In addition, an option is added to disable sending notifications to wearables altogether. Read the commit message for details.
