### ISSUE TITLE
Persistent Installation Progress Notification 

### ISSUE THREAD

**Issue by Nzzyme** [MuntashirAkon/AppManager#1103]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After downloading an apk file, I open the built-in 'File Manager' app and tap on the apk file. The system shows me the 'Open with' dialog with various options like App Info, Explore, Install (AM), Package Installer, Scanner, etc.). Now, when I tap on the 'Install' option (installation via App Manager), the app is installed but at the same time, there is a persistent notification about the installation progress as seen below which does not disappear even after several minutes. 

### To Reproduce

1. Download any apk file
2. Open the built-in 'File Manager' app
3. Tap on the apk file and then tap on the 'Install' option (installation via App Manager)

The app is installed but you will still see a persistent notification about the installation progress

### Expected behavior

After an app is installed via AM, the notification should read something like:

App Name installed successfully

Ex: Facebook installed successfully

### Screenshots

Screen Recording Found Here:

[https://filebin.net/k1zjzo8a2s0jwyzq](url)

### Logs

None

### Device info

- Device: Poco M5
- OS Version: MIUI 13.0.12 (Android 12)
- App Manager Version: 3.1.1
- Mode: Root/ADB/NonRoot: Non-root

### Additional context

Happens with other apk files as well and not just a one-off case.

**Comment by MuntashirAkon** [comment]
This issue cannot be fully fixed due to limitations in the Android itself. Other unprivileged apps that provide background installation via session installer has similar issues. But it can be minimised. I'm making some changes to the installer in v4.0.0 which will reduce incidents like this. So, for now, you can wait until v4.0.0 becomes stable enough for day to day use. Feel free to open the issue again if you continue to face this issue after the final release of v4.0.0.
