### ISSUE TITLE
Feature Reversion Request: Please revert to older way of handling shortcuts

### ISSUE THREAD

**Issue by VA1DER** [MuntashirAkon/AppManager#1129]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

A recent change in App Manager changed the way that App intent shortcuts are executed.  Previously, (3.0.4), creating and executing a shortcut for an app intent launched only that app.  Now the way the shortcuts are made causes App Manager to launch and initialize prior to the app whose intent you want to activate.

This is a significant setback for all app intent shortcuts.  It now uses much more memory, and takes added time where the user has to wait for App Manager to initialize and to register with SU before it can go on to run the simple shortcut.  Many people do not have SU configured to automatically authorize App Manager, so now executing any shortcut requires a SU authorization.

### Describe the solution you'd like

Revert to the old system of creating and launching App intent shortcuts that does not require App Manager to be launched to handle the shortcut.

**Comment by MuntashirAkon** [comment]
This is done for several reasons:
1. Android no longer allows third-party apps to open third-party shortcuts directly from the home screen (#1001)
2. To provide enhance security for those who are using screen lock mechanism within App Manager
3. To facilitate launching any type of activities, not just the exported ones with no permission.

For the reason#1, not only App Manager but also all the other shortcut managers are now doing the same. You can't feel it because you can't see the activity being launched from those tools. Initialisation is essential to figure out what to do with the Intent or what sort of security mechanism is in place. If you're using the latest alpha, you can choose to run App Manager in the background (has little to no influence on the battery) to reduce short-term memory pressure. If you do not want App Manager to use root, you can disable it in settings.

**Comment by VA1DER** [comment]
The old shortcut mechanism still works all the way up until at least Android 12.  Rather than forcing a new (and less beneficial) way of creating and activating all shortcuts created on all the versions of Android which still allow the old, better way,  perhaps you would consider having App Manager supporting the old shortcut creation method on those platforms which support it when creating a shortcut for exported activities.

I want App Manager to use Root.  I just do not want to have to have App Manager invoked (and thus have to approve root access) every time a shortcut is that App Manager created gets invoked.
