### ISSUE TITLE
Sometimes all block rules are gone

### ISSUE THREAD

**Issue by yilksd** [MuntashirAkon/AppManager#1134]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Sometimes all component block rules for an app are suddenly  gone, which means all components are permitted. 

### Device info

- Device: Samsung s10e dotOS
- OS Version:Android 11
- App Manager Version:3.1.1
- Mode: Root

### Additional context

Default blocking method is IFW + PM Disable

**Comment by MuntashirAkon** [comment]
This can only happen when you factory reset your system. Clearing data from App Manager does not remove any rules from the system.

**Comment by yilksd** [comment]
@MuntashirAkon But this is  exactly what happened.   I've seen this problem twice, on different devices, with different Android version & App Manager version . But I can't find a pattern, so I can't reliably reproduce the problem. Of course I didn't factory reset my system or clear data in App Manager. The rules were just suddenly gone in App Manager's GUI.

**Comment by MuntashirAkon** [comment]
If they're only disappearing from App Manager, it might be a due to an old issue where the rules files were created using root instead of no-root. So, when you updated from that version to the latest, the rules would disappear because the files were no longer accessible. There's no other (known) ways to explain this incident.

If this is indeed the issue, you can restore permissions for those files using the following commands:

**Fix users and owners**
```sh
su -c chown -R UID:GID /data/data/io.github.muntashirakon.AppManager/files/conf
```
(Replace `UID` and `GID` with App Manager's user ID)

**Fix SELinux context**
```sh
su -c restorecon -R /data/data/io.github.muntashirakon.AppManager/files/conf
```

**Comment by yilksd** [comment]
@MuntashirAkon No, it's not because of this. The permission and SELinux context of /data/data/io.github.muntashirakon.AppManager/files/conf is correct, and I have not update App Manager's version.

**Comment by MuntashirAkon** [comment]
We're tracking issues like this via #1071
