### ISSUE TITLE
REMOVE/UNINSTALL THIS APP

### ISSUE THREAD

**Issue by mulrennan** [MuntashirAkon/AppManager#1143]
### Describe the existing feature/documentation

Cannot Uninstall this app from device!

### Describe your problem(s)

same as above. downloaded from f-droid repository and cannot be uninstalled, haven't even used it once I saw that it wants root permissions...this is NOT a rooted device and no warning was given in the repository box description prior to installing like WARNING! THIS APP MANAGER CANNOT BE UNINSTALLED!

**Comment by Aridlvory** [comment]
Check if any Device admin is active or not..

**Comment by mulrennan** [comment]
No device administrators are active, that was one of the first things I checked.

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 13, 2023 at 5:23 PM, ***@***.***> wrote:   


Check if any Device admin is active or not..

**Comment by mulrennan** [comment]
No Device Administrators are active, that's the first thing I checked before submitting issue.

**Comment by MuntashirAkon** [comment]
I'm guessing you're a Samsung One UI user. In some versions of One UI, the native installer app crashes when you attempt to uninstall App Manager as explained in countless occasions in the past (e.g. read one of #989, #465, #990, #605, #259, ... for an answer). However, no user ever posted any logs from their device so that the actual issue can be discovered and possibly, reported to Samsung so that they can fix that issue for good.

**Comment by mulrennan** [comment]
No I'm not using Samsung so those other issues don't apply other than no side loaded app should be uninstallable especially without warning in the box description... this is the first time this has happened in over 7 years on Android. Somehow the app seems to be highjacking superuser functionality.

**Comment by mulrennan** [comment]
I just finished reading all the previous issues regarding not being able to uninstall. Also tried the removing the SD card routine, unfortunately, it didn't work. App cannot be 'disabled' and the built-in package installer stops or crashes while trying to uninstall. This is not Samsung, but a standard name brand device with stock android launcher/UI less than two years old.

**Comment by MuntashirAkon** [comment]
In that case, I cannot explain the issue if you do not share a crash log from the package installer along with your device information so that I can also look into the AOSP source code. However, whatever is preventing App Manager to be uninstalled in your case, it must be something to do with the AndroidManifest.xml.

**Comment by mulrennan** [comment]
You can explain the issue by simply installing your app into a stock Android  device and see how the package installer crashes for yourself. I'm not set up to send bug reports on broken applications and doing so compromises sensitive device information. In issue #159 which I also looked at regarding Samsung, you implied that you could fix the Uninstall issue but not without "reverting an important feature"... I suggest that you revert that feature in an immediate update so people can uninstall this app as soon as possible. How the app is highjacking super user function with no device admin; no usage access, and no process even running is beyond me.

**Comment by MuntashirAkon** [comment]
> You can explain the issue by simply installing your app into a stock Android device and see how the package installer crashes for yourself.

This issue is very much device specific as I too use such as device without issues. I also tested uninstallation on many devices without issues. The pattern suggested a small number of devices which I am yet to figure out because those who cannot uninstall App Manager are prejudiced enough to think that it is I who have done something intentionally that's causing the issue that happens to be in their own device framework, which pray if goes in the wrong hands, may be one of biggest vulnerabilities of all time (e.g. what's worse than being unable to install a vulnerable app?). Were I able to find out the vulnerability, I wouldn't miss it for the world. But my current situations in life does not permit me to invest time on finding Android vulnerabilities.

> In issue #159 which I also looked at regarding Samsung, you implied that you could fix the Uninstall issue but not without "reverting an important feature"...

That statement was provided there based on a user's assessment that an app with `hasFragileUserData` attribute in AndroidManifest caused such as failure which turned out to be false.

Anyway, since (like others), you've declined to help us sorting the issue, there's no point in leaving the issue open.

**Comment by mulrennan** [comment]
This is a standard Android OS with stock UI, it is NOT Samsung or other user's devices; the brand name has nothing to do with it; it is your broken application; FIX IT AS PER YOUR REMARKS ISSUE #159 with an immediate update.

**Comment by MuntashirAkon** [comment]
> FIX IT AS PER YOUR REMARKS ISSUE #159 with an immediate update.

Did you even read what I wrote above. That fix didn't work.
