### ISSUE TITLE
Titanium Backup encrypted backups

### ISSUE THREAD

**Issue by ltguillaume** [MuntashirAkon/AppManager#1157]
### Describe the existing feature/documentation

As far as I can find (https://github.com/MuntashirAkon/AppManager/issues/371), importing a Titanium Backup folder currenty does not support encrypted archives.

### Describe your problem(s)

However, when I tried to do so, I did not get an error message, but instead got asked for an input AES key _multiple times_ before starting the input. Is one of those input requests (or all) in fact meant for the decryption of the backups, or are they meant for me to input the AES key I've set in App Manager's backup options? Either way, the procedure seems rather unclear to me.

All backups were processed (136 according to the progress notification, taking quite some time, I estimate about 25 minutes), even though I never actually typed in the password I used in TB, and 131 of them failed...

### Additional context

There _are_ ways to decrypt TB backups quite easily, though. An example (which I've recently used successfully) is https://pypi.org/project/pytibade/

So it should be possible to fully support importing encrypted backups from TB into App Manager.

App Manager v4.0.0-alpha01
Android 11

**Comment by MuntashirAkon** [comment]
Encrypted TB backups aren't tested because nobody provided any encrypted backups for me to test. I've never really used TB for backups, the feature was implemented based on the information and backups provided by the former TB users who wanted to restore their precious backups in a modern Android operating system. A solution for you at present would be decrypting the encrypted backups and then importing them to App Manager.
