### ISSUE TITLE
Export the AudioPlayerActivity Activity.

### ISSUE THREAD

**Issue by libamidi** [MuntashirAkon/AppManager#1159]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Export the io.github.muntashirakon.AppManager.viewer.audio.AudioPlayerActivity Activity.

### Describe alternatives you've considered

Create an alias activity for the io.github.muntashirakon.AppManager.viewer.audio.AudioPlayerActivity Activity.

**Comment by MuntashirAkon** [comment]
Since App Manager declares the Internet permission, the audio player is restricted to App Manager itself to reduce the ability to exploit potential framework/driver vulnerabilities, especially the RCE ones. An alternative solution is to use a sandboxed (i.e. permission-less) service to load and play the audio files, but for now, we aren't using any services at all.
