### ISSUE TITLE
tracker blocker not following default blocking method settings

### ISSUE THREAD

**Issue by rhjdvsgsgks** [MuntashirAkon/AppManager#1174]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

when i set "Default blocking method" to disable. the tracker blocker in app page or "one click" menu will still use "IFW + disable" to block

### To Reproduce

1. set "Default blocking method" to disable
2. use "block trackers" in one click menu
3. some file created in `/data/system/ifw`

### Expected behavior

follow the "Default blocking method" setting

### Device info

- Device: any
- OS Version: 11
- App Manager Version: 3.1.1
- Mode: Root

**Comment by MuntashirAkon** [comment]
Yes, if the IFW folder is writable, a file might be created. But it does not mean that the selected components are in that file. Since the components could be configured individually (notice the _default_ keyword in the setting), it's possible that some other components were blocked using IFW. If the package did not have any components configured via IFW, the file would be empty, eg.

```xml
<rules>
</rules>
```

The filename does not bear any significance. It's possible to combine all those files into one, too. The files are named after their package name for convenience.
