### ISSUE TITLE
Adapting blocking rules

### ISSUE THREAD

**Issue by gab12** [MuntashirAkon/AppManager#1192]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Hello,

Congratulations on your extraordinary tool.

I recognised that the list of blockages is taken from Exodus.
However, it has some problems and I think that the following adaptations need to be made:

- Proxy Billing is detected as a tracker. The problem is that blocking it will make in-app payments impossible. The user will get a non-explicit error message in the applications. I think it's too dangerous to consider it as a tracker. It will generate a lot of errors for users without them understanding. Especially as I don't think it can be considered a tracker, given that it's a payment tool and not a tracking tool.
com.android.billingclient.api.ProxyBillingActivity

- Google Ads: The world's leading tracker is not blocked.
The components below are not in the list of blockers when they should be:
com.google.android.gms.ads.AdActivity
com.google.android.gms.ads.OutOfContextTestingActivity

Note: I had contacted Exodus about these problems in their list. I never received a reply.

**Comment by MuntashirAkon** [comment]
> I recognised that the list of blockages is taken from Exodus.

Not quite. The list is only _based on_ Exodus, but not the same as Exodus, because we believe that Exodus does not have a well-defined threat model (and you've already discovered it, I think, by finding the absence of certain trackers and their refusal to include those). Without a threat model, I don't think Exodus has any relevance to this project which offers (and is trying to offer) flexible threat model to its users.

> * Proxy Billing is detected as a tracker. The problem is that blocking it will make in-app payments impossible. The user will get a non-explicit error message in the applications. I think it's too dangerous to consider it as a tracker. It will generate a lot of errors for users without them understanding. Especially as I don't think it can be considered a tracker, given that it's a payment tool and not a tracking tool.

_Thinking_ does not matter when it comes to trackers. We decide things _logically_. Does it track users by storing Personally Identifiable Information (PII) in a hostile place (eg. five eyes)? Yes. I don't think you need any other criteria to not consider it as trackers. Now, trackers aren't ignored or whitelisted based on the dangerousness of it (it's not even in the threat model), they're decided solely based on their behaviour. Threat modelling, in this case, is left as an exercise to the user. As explained in #664, if we were to alter our threat model to exclude these trackers, it would not only raise ethical questions about the projects I maintain but also harm the sole purpose of the project (that is to spread privacy awareness among users). For the same reason, other Google products (eg. MLKit) are also listed as trackers in App Manager despite multiple requests to remove it. Now, if we hadn't investigated MLKit, no one would ever know that this library has the capability of phoning home.

> * Google Ads: The world's leading tracker is not blocked.

They're detected as trackers in App Manager. Not just those, we have many other exceptions to Exodus' list.

---

The rest of the FR is identical to #664. So, I'm closing this in favour of #664.

**Comment by gab12** [comment]
Hello,

Thanks MunstashirAkon for your detailed feedback.
Concerning googles trackeurs it's
com.google.android.gms.ads.AdService and
com.google.android.gms.ads.OutOfContextTestingActivity
which are not referenced.

**Comment by MuntashirAkon** [comment]
> Concerning googles trackeurs it's
> com.google.android.gms.ads.AdService and
> com.google.android.gms.ads.OutOfContextTestingActivity
> which are not referenced.

Yes, it seems we are no longer using `com.google.android.gms.ads.` signature. This will be fixed in the next release.

**Comment by MuntashirAkon** [comment]
BTW, as specified in the issue template section (which you see when you open a new issue), these issues should be posted in [my other project](https://github.com/MuntashirAkon/android-libraries) which specifically deals with these issues.
