### ISSUE TITLE
Suppress keyboard activation when returning to app list with search terms

### ISSUE THREAD

**Issue by mario0318** [MuntashirAkon/AppManager#1199]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

If I were to seek a search on the apps list by typing whatever into the search box, and I get the newly refreshed apps list containing that term, I can go to any one app without issue.

But upon going Back to the apps list, while the list remains the same along with the term still present in the search box, the focus is moved to the search box, causing the keyboard to pop up and taking a ton of screen area. This means having to either tap on the hide keyboard button or pressing Back again, which isn't always recognized by the device and so perpetuates more aggravation if there was device lag at that moment (a common occurrence when my keyboard is activated, for example) 

### Describe the solution you'd like

Normally refining the search terms to specify or find what I'm looking for would be an action made exclusively by the user. Returning to the previous screen should maintain the state of the input device unless it is a necessary input, like a popup window to enter a PIN or some other variable.

If this focus can be moved to another element or removed altogether, then only upon explicit user choice tapping on the search box should the keyboard be activated.

**Comment by shuvashish76** [comment]
Similar issue #729
> But upon going Back to the apps list, while the list remains the same along with the term still present in the search box, the focus is moved to the search box, causing the keyboard to pop up and taking a ton of screen area.

This should be the expected behaviour i.e. the user come back to search box _with previously entered keyword_ probably to search another app hence the focus stays on search box > show keyboard.

>  This means having to either tap on the _hide keyboard_ button _or pressing Back_ again, **which isn't always recognized by the device** and so perpetuates more aggravation if there was device lag at that moment (a common occurrence when my keyboard is activated, for example)

You should mention which keyboards you use & test if changing keyboard app fixes your issue.

---

Here is demonstration of keyboard behaviour of both FlorisBoard & AnySoftKeyboard

On AM main page (MP)
1. AM opens up without focus on search/keyboard (KB) ✔️

Without any input
2. MP > click on any app > back > it doesn't focus on search/KB ✔️
3. MP > click on search > it shows KB > click on any app > back > focus stays on search/KB ✔️
 - i) MP > click on search > it shows KB > **hide the KB** > click on any app > back > focus stays on search/KB ✔️
 - ii) MP > click on search > it shows KB > **close the KB** (using device navigation back) > click on any app > back > it doesn't focus on search/KB ✔️
<details><summary>Demo</summary>
<p>

https://github.com/MuntashirAkon/AppManager/assets/48226312/d8fcc881-17b8-461a-b2a8-d902d8309d35

</p>
</details> 

With input
4. MP > click on search > it shows KB > type your keyword > click on any app > back > focus  stays on search/KB ✔️
 - i) MP > click on search > it shows KB > type your keyword > **hide the KB** > click on any app > back > focus  stays on search/KB ✔️
 - ii) MP > click on search > it shows KB > type your keyword > **close the KB** > click on any app > back > focus stays on search/KB ❓
[So everything is same here only change is 3(ii) vs 4(ii)]
<details><summary>Demo2</summary>
<p>

https://github.com/MuntashirAkon/AppManager/assets/48226312/7d5cb1eb-a0bc-4fd1-a80f-b8ea41041193

</p>
</details>

**Comment by MuntashirAkon** [comment]
> * ii) MP > click on search > it shows KB > type your keyword > **close the KB** > click on any app > back > focus stays on search/KB ❓

I've used the Android-default search widget for accessibility. But it appears it behaves in the wrong way in this particular case.

**Comment by mario0318** [comment]
If this is the intended behaviour, could there be an option to disable it or to at least keep the keyboard from activating if an element outside of the search box was selected so as to keep the keyboard from popping up.

My particular case scenario is almost the opposite of the intended behaviour. That is, I usually know what I'm looking for seldom needing to refine the search terms. The primary actions I perform involve doing a search for apps of a certain type, name, size, etc, then going down the list opening each app details, doing an action or going thru its info, returning to the app list and go to the next app, and so on. It may be 3 apps or it may be 30 apps, but the search term once refined to seek what I'm looking for kinda gets in the way when even after selecting other elements outside the search box, the focus is set to it upon returning to the app list which is where the frustration stems from after going down a few apps with the keyboard popping up automatically each time.

I tested this on the the default keyboard on my device, GBoard. and the same behaviour occurs.

**Comment by MuntashirAkon** [comment]
> My particular case scenario is almost the opposite of the intended behaviour. That is, I usually know what I'm looking for seldom needing to refine the search terms. The primary actions I perform involve doing a search for apps of a certain type, name, size, etc, then going down the list opening each app details, doing an action or going thru its info, returning to the app list and go to the next app, and so on. It may be 3 apps or it may be 30 apps. But if I ran the search and refined the terms and have what I was looking for, the keyboard gets in the way when even after selecting other elements outside the search box, the focus is set to it upon returning to the app list which is where the frustration stems from after going down a few apps with the keyboard popping up automatically each time.

In that case, all you needed to do was using the “go back” gesture or button to hide the keyboard. But as @shuvashish76 pointed out, this isn't working as expected. Although it's written “Search”, it's basically one of the filtering methods, and it's expected that the user will continue to look for new things until the IME (eg. the keyboard) is closed.

**Comment by mario0318** [comment]
Ah. So then given the fact that I do close the keyboard each time, regardless of how much I interact outside of the search box and avoid activating IME on app list, since the focus is **always** set to the search box upon returning to the app list thus activating IME, is **not** the intended behavior (a bug), and not a matter of missing feature/functionality, correct?

**Comment by shuvashish76** [comment]
> I ran the search and refined the terms and have what I was looking for, the keyboard gets in the way when even after selecting other elements outside the search box, the focus is set to it upon returning to the app list which is where the frustration stems from after going down a few apps with the keyboard popping up automatically each time.

If you think from others prospective, suppose AM work as you suggested then we've to click on the search option each time I come back to app list.
For your use better just ~hide~**close** the KB once 4 (ii) [when fixed*] after your search & it should never show you again until you click the search again just like 3 (ii).

**Comment by MuntashirAkon** [comment]
> So then given the fact that I do close the keyboard each time, regardless of how much I interact outside of the search box and avoid activating IME on app list, since the focus is **always** set to the search box upon returning to the app list thus activating IME, is **not** the intended behavior (a bug), and not a matter of missing feature/functionality, correct?

Yes. IME should never activate itself if it is deactivated by the user, at least, this is how it should in principle work.

**Comment by mario0318** [comment]
I truly appreciate your efforts to fix the bug. Looking forward to the update that will make the feature work smoothly again. Thanks for your hard work, @MuntashirAkon

**Comment by MuntashirAkon** [comment]
Fixed in f91400dcd839afe7ac8ae404ce89ea0179d4e258
