### ISSUE TITLE
Add "in-between items" selection mode for Running Apps

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1212]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Add the in between selection mode feature just like we've for MainPage/FileManager/LogViewer.

Currently after select some items, if you go to another app & comeback (from device recents) it refreshs the "running apps" page though the bottom sheet shows correct info and all the operations works expected. Visually empty selection just looks odd, no major issues.

### Additional context

We're missing search logs from package name directly from Running Apps page.
Suggestion :
1. Can we use either 3dot context menu or bottom sheet "View Logs" option to view logs from _package name_ and other one to view logs from _process id._
2. [Or] long click on "View Logs" and select > "package name" to view **all logs** from that specific app?

**Comment by MuntashirAkon** [comment]
> We're missing search logs from package name directly from Running Apps page.

Android does not provide an option to filter by package name directly. What others do is they translate the package name into UID or PID but with certain drawbacks. If you filter by UID, you may also include other packages that share the same UID, and if you filter by PID, multiple instances of the app won't be taken into account. But since UID is more stable and most apps do not shared UID, we've decided to use UID translation instead, but this is a different topic.

**Comment by MuntashirAkon** [comment]
I've already added this in c5219c7826099419825622994916669a0ab368a4 (accidental push)
