### ISSUE TITLE
ADB TCPIP DOES NOT WORK

### ISSUE THREAD

**Issue by ZakitheBig** [MuntashirAkon/AppManager#1213]
### Describe your problem(s)

Follow the steps on the website and in the SDK tools I typed adb tcpip 5555

### Additional context

ADB WIFI DIDN'T WORK ALSO

I SAW SEVERAL THREADS ASKING FOR SHIZUKU, MY SHIZUKU DOESN'T RECOGNIZE IT VIA ADB TCP, BUT ON ADB-WIFI YES

**Comment by MuntashirAkon** [comment]
> I gave permission and I still get this error at the end of the video

You didn't upload any video 🤭 

I think this should be reported as a bug because additional information are necessary to identify the underlying issue. So, create another issue using the [bug report template](https://github.com/MuntashirAkon/AppManager/issues/new?assignees=&labels=Bug&projects=&template=bug_report.yml) instead. I'm closing the issue.
