### ISSUE TITLE
Using assistant settings to launch system only/privileged components

### ISSUE THREAD

**Issue by Tharow** [MuntashirAkon/AppManager#1243]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

The secure setting found in the android settings database can allow for launching of any system only component.

Example using com.android.settings/.password.ChooseLockPattern

adb exec-out settings put secure assistant com.android.settings/.password.ChooseLockPattern
adb exec-out input keyevent 219

### Describe the solution you'd like

Step By Step
1. Check App Manager has Accessibility Perms
2. Store secure assistant setting
3. Store Component to be launched into secure assistant setting.
4. Use Accessibility to send KEYCODE_ASSIST (219)
5. Restore secure assistant setting to original value

### Describe alternatives you've considered

this could also be done via adb mode.
but with the android.permission.WRITE_SECURE_SETTINGS it could be done in "No Root" mode.

### Additional context

Works since API 16, Works Across Vendors As Well
Personally only tested down to API 20, and on Google, Redmi, Motorola, and Samsung devices.

Google Pixel 6a
Redmi Note 7
Samsung Note 8
Motorola G Stylus
Some Random Android Desk Phone running 4.4W

**Comment by MuntashirAkon** [comment]
Thanks for your detailed investigation. This appears to be a very good and consistent hack.

<details>
<summary>Note to self</summary>

`input` shell command [source](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/services/core/java/com/android/server/input/InputShellCommand.java;l=350;drc=0b80090e02814093f2187c2ce7e64f87cb917edc) suggest that any app with `android.permission.INJECT_EVENTS` permission can inject global key events. `android` and `shell` packages have this permission, but user apps cannot have this permission by default since it's a signature permission. As an alternative, accessibility permission can be utilised like the report suggest.

</details>

**Comment by MuntashirAkon** [comment]
It appears accessibility service does not allow launching assistant. So, it's not possible to inject the key code via accessibility. Still, we can allow ADB users to launch private components. We can also ask the no-root users to trigger the assist shortcut manually after they click launch.

**Comment by MuntashirAkon** [comment]
Added in bcbd6b2e1dd7360df3127084a9f5056aeabc2dcf
