### ISSUE TITLE
filter: quantitative error

### ISSUE THREAD

**Issue by Pantyhose-X** [MuntashirAkon/AppManager#1275]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I have 291 apps installed. 
AppManager But it showed 460 apps.

I only enable `user apps`
I did not enable `system apps`

### To Reproduce

1. filter User apps
2. Back to list Long press any app

### Screenshots

# filter User apps
![1](https://github.com/MuntashirAkon/AppManager/assets/42504385/a212c11c-954b-4c9c-9762-750f8d56dab3)

# bug 460 User apps
![2](https://github.com/MuntashirAkon/AppManager/assets/42504385/1ef90a93-9beb-4238-a6a2-510b38d72ec2)

# User apps 291 properly
![3](https://github.com/MuntashirAkon/AppManager/assets/42504385/3dd1a0cc-49ef-4fcc-ae9e-c290be895e93)

### Device info

- Device: Pixxel 7
- OS Version: grapheneos
- App Manager Version: v1.7-8 ~ v3.1.4
- Mode: Root/ADB/ NonRoot

**Comment by MuntashirAkon** [comment]
Selection panel does not take any filters into account as they are temporary modifiers just like the search widget above (you can, for example, choose to filter the system apps to select a few system apps and then filter the user apps to select a few user apps at the same time). This gives an user the freedom to select any apps they like instead of just restricting themselves to a handful of apps. To find the real number of user apps, you can simply click the select all button.
