### ISSUE TITLE
Implement SetEdit Functionality.

### ISSUE THREAD

**Issue by LucioAmely** [MuntashirAkon/AppManager#1278]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Since it seems like you're no longer updating that app, I believe it's features should be merged into App manager.

**Comment by drogga** [comment]
BTW, the NavBar looks a lot better IMO in SetEdit than in this app, because there it's fully transparent, unlike with A.M., at least for me.

**Comment by MuntashirAkon** [comment]
> Since it seems like you're no longer updating that app, I believe it's features should be merged into App manager.

SetEdit is not updated because there's nothing to update right now.

> BTW, the NavBar looks a lot better IMO in SetEdit than in this app, because there it's fully transparent, unlike with A.M., at least for me.

Not sure whether you're talking about the SetEdit that I've developed. They share the exact same code for navbar.

**Comment by drogga** [comment]
And yet the NavBars appearance of both is different (the last time I checked) on S20 FE, with A.11

**Comment by LucioAmely** [comment]
> @MuntashirAkon ...and yet the NavBars appearance of both is different (the last time I checked) on S20 FE, with A.11

Can you please provide screenshots?

**Comment by drogga** [comment]
You reacted with thumbs-up on my first comment regarding this, so I thought that you've noticed the same thing, so you can probably attach screenshots yourself, I prefer not to, because the SetEdit app got updated and I haven't tested it yet, so IDK if that's still the case, maybe this changed and the NavBars are no longer different - IDK...
Anyway, the difference of the NavBar's style of the 2 apps can probably be compared on any Samsung with Android 11 on BrowserStack (I've never used it).
