### ISSUE TITLE
Include HiddenApps feature from AppWarden(AuroraOSS)

### ISSUE THREAD

**Issue by Rexadev** [MuntashirAkon/AppManager#1280]
### Please check before submitting an issue
- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature
https://gitlab.com/AuroraOSS/AppWarden
![image](https://github.com/MuntashirAkon/AppManager/assets/62152714/ab9ea4d1-6138-40f6-9df7-53cc56d32aea)

**Comment by MuntashirAkon** [comment]
What does it do?

**Comment by MuntashirAkon** [comment]
So, it only hides the configured from the lists in the app, right? What's the use of this feature in App Manager? I think it to be an anti-feature because it reduces the amount of info App Manager offers by default. What happens if you accidentally hide an app from the list, completely forgot about it and switch device relying on AM's backup/restore feature? The results could be catastrophic. However, if there are any valid use of this feature, we can always display a warning in the main page saying that some apps are being hidden from the list.

**Comment by MuntashirAkon** [comment]
Closed due to a lack of response. Feel free to open it again if you're still facing the issue.
