### ISSUE TITLE
can be disable "Update Required" ?

### ISSUE THREAD

**Issue by Mitezuss** [MuntashirAkon/AppManager#1293]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

disable forced update

### Describe the solution you'd like

wanna keep using whatever version i want (a old or beta version)

### Describe alternatives you've considered

maybe just a reminder with a checkbox to disable

### Additional context

related to "BuildExpiryChecker.buildExpired"

**Comment by MuntashirAkon** [comment]
As I said in another issue, this is a privacy-focused app. If you do not care about privacy and security, it's best not to use this app (or any of my apps). We do our best to avoid drawing the wrong crowd because it needlessly increases the burden.

As for bypassing that warning, you can return `false` to the function you specified above by modifying the APK. This way, the responsibility and consequences will be yours alone.

**Comment by drogga** [comment]
While this is one of those apps which you would want to and even should keep updated, especially given how many bugs it has and some of them are bing addressed, I still don't like and even hate when devs. force users to update, this is extremely wrong IMO, especially when a developer decides to remove a useful thing or suddenly decides to make the app worse in some cases, for example: an app doesn't have ads, dev. decides to add such junk, even full screen video ones and don't fix anything (if something needs fixing at all), which will also increase the file size 4x times in some cases and call this an "update", which is actually nothing but a downgrade, sure it's normal for the dev. to want anyone that installed the app to generate him income, but users will hate this, look for mods or stop using the app, which will get bad rating and reviews (that's why you can't rely on those nowadays on PS), I can probably give more examples why I hate forced updates, but I don't think it's necessary, given that I tend to keep this updated, so I will have to check how bad the case is with this one by myself soon, but still I wanted to share my opinion on this and I hope that it's not a problem that I did.

BTW, I believe I'm capable of disabling/bypassing it by myself, but that's not the point.

**Comment by MuntashirAkon** [comment]
> While this is one of those apps which you would want to and even should keep updated, especially given how many bugs it has and some of them are being addressed, I still don't like and even hate when devs. force users to update, this is extremely wrong IMO, especially when a developer decides to remove a useful thing or suddenly decides to make the app worse in some cases, for example: an app doesn't have ads, dev. decides to add such junk, even full screen video ones and don't fix anything (if something needs fixing at all), which will also increase the file size 4x times in some cases and call this an "update", which is actually nothing but a downgrade, sure it's normal for the dev. to want anyone that installed the app to generate him income, but users will hate this, look for mods or stop using the app, which will get bad rating and reviews (that's why you can't rely on those nowadays on PS), I can probably give more examples why I hate forced updates, but I don't think it's necessary, given that I tend to keep this updated, so I will have to check how bad the case is with this one by myself soon, but still I wanted to share my opinion on this and I hope that it's not a problem that I did.

If you are not satisfied with a feature, you're very welcome to argue against it. As for updates, everything has an ending. For example, App Manager's signing key will expire in 2045. After that, you won't be able to use App Manager without altering the signing key. There are many reasons as to why we needed to introduce a more early death: This app interacts directly with the framework at a very low-level. These low-level features have no public documentation and quite unstable. This also has security issues as well. Ensuring the app is up-to-date is the only thing which is effective against these threats.
 
> BTW, I believe I'm capable of disabling/bypassing it by myself, but that's not the point.

You're perfectly allowed to do anything with an app that you own. But the point is that when you do that you're on your own.
