### ISSUE TITLE
Usage widget should show more then top 3 apps on  higher widget dimension 

### ISSUE THREAD

**Issue by czarnyckm** [MuntashirAkon/AppManager#1320]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Usage widget should show more then 3 top apps on higher widget dimension.
Maybe as config entry or auto scale feature.

![Screenshot_20240325-100252](https://github.com/MuntashirAkon/AppManager/assets/18211387/7233cbfc-6d1e-485c-a004-64d75e7f2603)

**Comment by MuntashirAkon** [comment]
Widgets in Android are particularly tricky to implement as they have lots of limitation. For example, there's a limit on what type of views or colors you can use here. This makes it very difficult to implement. That's why almost all the other screen time widget will display the top three apps instead of loading them dynamically. App Manager retains the behavior as I have much less time and resource than the developers of those apps.
