### ISSUE TITLE
Setting gets overriden

### ISSUE THREAD

**Issue by LucasBS1** [MuntashirAkon/AppManager#1336]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Some settings that I disable via App Manager are simply RESTORED when the corresponding application is run, or if the app has a "supervisor" that monitors this setting.

One example is the Screen Lock Service, from the Device Administrators page.
This service is actually a Receiver from Google Play Services (com.google.android.gms.auth.managed.admin.DeviceAdminReceiver)

Another example is from the app Aliexpress (com.taobao.accs.ChannelService)

### To Reproduce

1 - Disable the Screen Lock Service, from the Device Administrators page;
2 - Disable the receiver com.google.android.gms.auth.managed.admin.DeviceAdminReceiver;
3 - Wait a few hours to see if it is really gone;
4 - Cry of disappointment

### Expected behavior

Anything that was disabled should stay disabled

### Screenshots

![Screenshot_20240407-175403](https://github.com/MuntashirAkon/AppManager/assets/86728997/48e1ceb8-14fe-4e99-a147-6b86385e3c05)

![Screenshot_20240407-175237](https://github.com/MuntashirAkon/AppManager/assets/86728997/1072e85c-ebe5-4bfd-8f70-4c72db7eb46c)

### Logs

Takes hours for the thing to come back. Can't upload a logcat of that size without anyone giving me filters to begin with

### Device info

- Device: Motorola G6
- OS Version: Pie
- App Manager Version: 2.1.5
- Mode: Root

**Comment by MuntashirAkon** [comment]
When you use the default blocking option e.g., Intent Firewall (IFW) + disable, enabling this component does not matter. It's still being blocked by IFW, but most other blockers cannot display it because they don't use it. If it's shown as blocked in App Manager, it should be enough for you. But if you do not use IFW, then there's nothing anybody could do about it other than you removing/blocking the offending app (which I guess, you aren't going to do).

**Comment by LucasBS1** [comment]
>moving/blocking the offending app (which I guess, you aren't going to do).

We are talking about Google Play Services. Are you aware we cannot "move this offending app" ?

If a heart is diseased, should I pluck out the heart or make a better medicine ?

App Ops is a software to manipulate other apps, but there's no interest in enhancing that core feature, apparently...

**Comment by MuntashirAkon** [comment]
> If a heart is diseased, should I pluck out the heart or make a better medicine ?

Bad analogy. I've gone this far without GMS in my phone. So could you or anybody. GMS is set to bypass every rules in the book by the vendor. Since you're on root, why not use IFW? GMS cannot detect changes in IFW because it can't access the info, it will think that the component is enabled. Even then, some system apps are set to bypass IFW rules as well, and some components will continue to work as expected even if they're _disabled_.

> Of course, I'm just pointing a weak point of the app.

This is a weakness of your device and in your threat model. I assume you're expecting App Manager to somehow monitor this change in component and revert it? What this will create is an infinite loop of enabling and disabling of the component causing your battery to drain quite fast.

> It's your decision to enhance or not the core feature of App Ops (manipulating the functionality of other apps).

App ops (application operation) is a different feature which is related to permissions. It's called app ops because the AOSP named it so.

**Comment by LucasBS1** [comment]
>I've gone this far without GMS in my phone

I wish I could get rid of it, but I use the Wallet !
Wasn't for that, my headache would be so in the past !

>GMS is set to bypass every rules in the book by the vendor

They are ! It's even insulting how intrusive google is.

>Since you're on root, why not use IFW?

The offending receiver that led me to find this "weak point" of App Manager is purely a local function. It corrupts the OEM's face unlock.
I don't believe it relies on internet.

Unless I'm taking the word "firewall" too literal and firewall is not a internet-blocking tool (I don't know exactly what IFW is)

>I assume you're expecting App Manager to somehow monitor this change in component and revert it? 

Maybe corrupt the receiver instead, so it never launches in the first place

Possible ?

> App ops (application operation) is a different feature which is related to permissions

Really sorry! I meant to say App Manager !
(There's another manager out there called App Ops that I used in the past)

**Comment by MuntashirAkon** [comment]
> The offending receiver that led me to find this "weak point" of App Manager is purely a local function. It corrupts the OEM's face unlock. I don't believe it relies on internet.
> 
> Unless I'm taking the word "firewall" too literal and firewall is not a internet-blocking tool (I don't know exactly what IFW is)

I guess you haven't read the docs yet: https://muntashirakon.github.io/AppManager/en/#subsec:faq:how-components-blocked
