### ISSUE TITLE
A while ago I could use AM in adb mode when I was not on wifi but not anymore which sucks so bad

### ISSUE THREAD

**Issue by vordx** [MuntashirAkon/AppManager#1356]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

A while ago before you made the app not detect adb when no wifi you killed a good feature and added inconvenience to the users that relay on wireless adb and could use it before without wifi.

I could run am in adb mode without wifi if it wasn't killed when I had wifi back home. Now I can't. Could we get that change reverted? It adds nothing but inconvenience to those who don't always have wifi and doesn't affect those who have wifi everywhere.

### To Reproduce

Start am in wireless debug mode
Turn off wifi and run it

### Expected behavior

To work fine like it did before.

### Device info

- Device: s23U
- OS Version: a14 one ui 6.1 
- App Manager Version: 4.0 beta 01 436
- Mode: ADB

**Comment by MuntashirAkon** [comment]
> A while ago before you made the app not detect adb when no wifi you killed a good feature and added inconvenience to the users that relay on wireless adb and could use it before without wifi.

This was never removed. After App Manager successfully connects to Wireless Debugging, it remains connected even when you turn it off. But you need to make sure the following:
1. `adb` hasn't been restarted or stopped. This could happen if your OS has a timeout for ADB or when you disable “USB debugging”.
2. You never change mode from Settings > Mode of Operations while App Manager is running as ADB. Because it's intended for a full-refresh by force-stopping the remote server and services.

> I could run am in adb mode without wifi if it wasn't killed when I had wifi back home. Now I can't. Could we get that change reverted? It adds nothing but inconvenience to those who don't always have wifi and doesn't affect those who have wifi everywhere.

I can't revert a change that was never made. If you think this is done in error, install the debug version and upload some logs so that I can look into it.

**PS:** Use of NSFW will get you blocked from all of my projects. Consider this as the first and final warning.

**Comment by vordx** [comment]
I had no wifi for the past 2 weeks so I couldn't test adb.

Now I'm trying test old versions but I can't because you are not allowing the use of older versions because of a "security threat". Idk what to do now

**Comment by MuntashirAkon** [comment]
Always install the latest debug versions. Except for some exceptional cases, there's usually no point in trying the old ones even if they worked in the past.

**Comment by MuntashirAkon** [comment]
Closed due to the lack of a response. Feel free to open it again along with the requested info if you're still facing the issue.
