### ISSUE TITLE
Very Simple File Manager

### ISSUE THREAD

**Issue by RickyM7** [MuntashirAkon/AppManager#141]
**Is your feature request related to a problem? Please describe.**
It's not a problem, it's just an improvement.

**Describe the solution you'd like**
It would be great to have a file manager integrated into the app.
This would be very useful for using AM tools in uninstalled apps that are in internal or external memory without having to leave the app.

**Describe alternatives you've considered**
This file manager would serve to explore internal and external storage and would show only folders with .apk files, .apks, etc; only files of this type and maybe files related to them (such as .xml, .dex, etc.) would be shown.

**Additional context**

**Comment by MuntashirAkon** [comment]
There's a reason for AM not to supply any file manager: **Storage Access Framework** (SAF). Google has been forcing the developers to use this badly-designed, slow and unusable-via-command-line API (instead of Java's File API) and will be mandatory for Android 11, which means trivial *nix way for handling files will not work without root for external storage. (There are really long threads in the Google's Issue Tracker on this if you're interested.) As a result, I'm not going to take the trouble of handling both SAF and Java File API (at least for now).

**Comment by Atrate** [comment]
On that: I've seen that you've forked MaterialFiles (https://github.com/MuntashirAkon/MaterialFiles), @MuntashirAkon, do you plan on expanding MF with stuff like a better text editor and media support?

**Comment by MuntashirAkon** [comment]
> do you plan on expanding MF with stuff like a better text editor and media support?

Not really. I initially forked it to change the material dark theme as it looks too white to me. But I haven't got the time to work on it.

But a basic text editor with syntax highlighting will be available in AM in order to allow users to edit resources, manifest and smali files (as you may have already guessed from #138) which can be also opened via file managers.

**Comment by pazos** [comment]
> There's a reason for AM not to supply any file manager: **Storage Access Framework** (SAF). Google has been forcing the developers to use this badly-designed, slow and unusable-via-command-line API (instead of Java's File API) and will be mandatory for Android 11, which means trivial *nix way for handling files will not work without root for external storage. (There are really long threads in the Google's Issue Tracker on this if you're interested.) As a result, I'm not going to take the trouble of handling both SAF and Java File API (at least for now).

If you don't want to publish on the PlayStore you're free to use https://developer.android.com/reference/android/Manifest.permission#MANAGE_EXTERNAL_STORAGE to use Java File API on API30.

For play store apps that want that permission google needs to aprove them first.

**Comment by MuntashirAkon** [comment]
> If you don't want to publish on the PlayStore you're free to use https://developer.android.com/reference/android/Manifest.permission#MANAGE_EXTERNAL_STORAGE to use Java File API on API30.

Does it work for external storage though? In API 29, I used `android:requestLegacyExternalStorage="true"` which was used to bypass the restriction but does it still work on API 30?

**Comment by pazos** [comment]
@MuntashirAkon: it works like WRITE_EXTERNAL_STORAGE up to API28 (API29 with the trick you mentioned).

Have a look at https://github.com/koreader/android-luajit-launcher/pull/253/files (we bump from API28 to API30 using the `android:requestLegacyExternalStorage="true"` for API29 and using the new permission in API30). It works fine as long as you don't depend on Google Play.

**Comment by MuntashirAkon** [comment]
> Have a look at https://github.com/koreader/android-luajit-launcher/pull/253/files (we bump from API28 to API30 using the `android:requestLegacyExternalStorage="true"` for API29 and using the new permission in API30). It works fine as long as you don't depend on Google Play.

Thanks. The PR was very useful.

**Comment by MuntashirAkon** [comment]
In order to explore APK files (feature#2 of #138), we need a simple file explorer. So, I don't see any harm in creating a simple file manager in order to allow features like APK explorer and batch install. In order to make things easier, AM will only display folders and supported files (APK, APKS, APKM and XAPK). If the user have a file with ZIP extension, they have to rename it to one of them.

**Comment by MuntashirAkon** [comment]
Implemented in 74b92117. Currently there isn't any way to access it, but you can directly open `FmActivity` from the **activities** tab of _AM Debug_.
