### ISSUE TITLE
Different package name for alpha/beta and stable, so they may be installed side by side

### ISSUE THREAD

**Issue by namesarebloat** [MuntashirAkon/AppManager#1440]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Since android updates like to break some of AppManager's functionality and the alpha/beta (are supposed to) get compatibility patches sooner, it might sometimes be necessary to upgrade to them, but they have other potentially unstable changes. 

Also once you upgrade, you're locked into the unstable branch even when the compatibility change landed in stable because the unstable is already 4.x and the stable released after that is still 3.x. 

There is a longer time between unstable releases than there is between stable releases and since AppManager builds expire, people were actually locked out of the app between alpha 2 and beta 1.

-----

Sometimes I worry that, regardless of which release I have installed, I may miss out on features or bug fixes from the other, because the stable gets more frequent updates that contain bug fixes and compatibility patches and I'm not 100% sure if those are just transfered from the latest beta or if those are new changes that went straight to the stable and the beta doesn't have them. 

### Describe the solution you'd like

A different package name for the unstable release so it can be installed alongside the stable release

### Describe alternatives you've considered

- More frequent unstable releases
- Mark in changelog of stable releases when a change is from the unstable release vs new and not included in the latest unstable release
- Issue may mostly resolve itself when stable is at 4.x, that is until work at 5.x starts

**Comment by MuntashirAkon** [comment]
> Since android updates like to break some of AppManager's functionality and the alpha/beta (are supposed to) get compatibility patches sooner, it might sometimes be necessary to upgrade to them, but they have other potentially unstable changes.

That's incorrect. Unstable branches don't get compatibility patches, only the current stable branch does. This is why there are frequent updates to the stable branch. The compatibility patches are usually backported from the master/main branch. So, the same changes will be present in the next unstable release. The only catch being that, you don't get to see the latest features when you're on the stable branch, or you don't get compatibility patches as frequently as you'd expect on the unstable branch.

If you're suffering from FOMO, consider installing the debug releases. They're a bit slower than the regular ones due to extensive logging, but they are always up-to-date and uses a different package name.
