### ISSUE TITLE
Latvian language

### ISSUE THREAD

**Issue by Coool** [MuntashirAkon/AppManager#1459]
Hi!

Can you add Weblate account (Coool) to Lavian language contributor.

Thanks.

**Comment by MuntashirAkon** [comment]
Added, thanks.

**Comment by Coool** [comment]
What is required from my side to be able you to use my Latvian translation contribution?

**Comment by MuntashirAkon** [comment]
> What is required from my side to be able you to use my Latvian translation contribution?

You've to wait until the translations are merged to App Manager and a release has been made (which may take several months because I need to review those).

**Comment by MuntashirAkon** [comment]
@Coool: Your translations are not of good quality, partly due to a lack of attention to the details/context, a lack of technical knowledge, and use of informal languages. For example, you use lots of brackets. For example,

- `App Manager (Lietotņu pārvaldnieks) piedāvā`: "App Manager" is a proper noun and it does not stand for anything (such as application manager).
- `%1$d sekundes` to describe seconds, for example, which the original version has a shorter version.
- `Atļaut (Aiziet)` unnecessary use of brackets. "Go" is an action. Similar strings: `Daudz (liela) kaudzes atmiņas`, `Piemērot (izmantot) noteikumus`,  ~~`Lietotnes nosaukuma (etiķetes)`~~, `Vispārīgā (koplietotā) lietotāja identifikatora`, ~~`Piekļuve lietošanas (lietojuma) datiem`~~.

You need to be more careful about choosing your words, especially the technical ones.

**Comment by Coool** [comment]
@MuntashirAkon, translation is still in progress. Be patience. I will adrese your complaints. But looks like you are Latvian language expert better than me.

**Comment by MuntashirAkon** [comment]
> P.S. Have your eagle eye turned attention that many of those translated strings are marked as fuzzy (mark as edit).

Those information are never transferred to the version control system, thus, are not checked by me. I think the "Suggest Edit" button is the only thing that works correctly on Weblate in terms of version control. I wish there existed a better tool for managing translations, but Weblate is currently the best we have.

As for language review, I have interests in linguistics and studied a lot of languages. So, apart from a few complex languages (such as Polish), most prominent languages share similar features. Therefore, it's not difficult to screen a translation for potential mistranslation or machine translation.

**Comment by Coool** [comment]
Don't remember right now which one[^ref2] was the difficult one based on Xiaomanyc[^ref1] source. But it's shure not Polish. If I strain my brain, even I can understand Polish (most Slavic, Cyrillic spoken languages).

P.S.
So you are language freak! Can you comment what is the hardest thing for Latvians to distinguish in Russian language?

[^ref1]: [YouTube](https://youtube.com/channel/UCLNoXf8gq6vhwsrYp-l0J-Q)
[^ref2]: [Massive thanks to @xiaomanyc  can’t wait to watch the full video @visitwales @CANAMOFFROAD](https://youtube.com/watch?v=mo8uZVipt-A&t=84)

**Comment by Coool** [comment]
@MuntashirAkon, I have requested multiple times to add Latvian language for Docs component on Weblate, but no response from your side. Have you received any request from Weblate?
