### ISSUE TITLE
Add a button to download the APK

### ISSUE THREAD

**Issue by shifoc** [MuntashirAkon/AppManager#1460]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Add a way to download the apk (with the package name and version as name instead of base.apk) in addition to the share apk button

**Comment by shuvashish76** [comment]
You can do that from main page > long click your preferred apps > Save apk
The naming format can be configured from Settings > Advanced > [Saved APK Name Format](https://muntashirakon.github.io/AppManager/en/#subsubsec:saved-apk-name-format)

---

### Observation:

> **Share.** Share button can be used to share the APK or (if the application is has multiple splits, OBB files or any dependencies) APKS file extracted from the application. (Source: https://muntashirakon.github.io/AppManager/en/#subsec:app-info-tab)

- While sharing apk that has no-splits it always saves the file as `base.apk`
- While sharing apk that has splits it always saves the apk file as `%label%_%version%.apks`

### Expected behavior:

While sharing the apps from **App Info** page it should also follow **Saved APK Name Format** configuration.

**Comment by MuntashirAkon** [comment]
> While sharing the apps from **App Info** page it should also follow **Saved APK Name Format** configuration.

Implemented via bce8011cf31aa7b3fc61c4acef411e691897bbcd
