### ISSUE TITLE
Virustotal enable scanning 

### ISSUE THREAD

**Issue by virusRK** [MuntashirAkon/AppManager#1463]
### Describe the existing feature/documentation

Virustotal scanning is not working properly like is used to work in prep release apk 

### Describe your problem(s)

I provide my api key to on virustotal api key box but like in prerelease 4.0 beta1 version work stable version is not work when I scan an app ro result found by virustotal 

### Additional context

It say enable scanning via virustotal

**Comment by virusRK** [comment]
Please can you help me with that  a pre release version also coming to end (expire)

**Comment by MuntashirAkon** [comment]
This should be an issue report. Please create an issue with the issue template instead. I have tested the stable release. It appears the file did upload and get scanned correctly, but it displayed error instead of retrieving the report due to some unexpected issues. You simply go back and scan again to get the results.
