### ISSUE TITLE
Install without confirmation

### ISSUE THREAD

**Issue by DestroyerBDT** [MuntashirAkon/AppManager#1466]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

In the Installer settings, it would be very useful to allow specific apps to install applications without confirmation when ch can be very useful for apps like Aurora store

### Describe alternatives you've considered

We can use root installer in aurora store but it doesn't block trackers and we later have to manually block them within the app

**Comment by shuvashish76** [comment]
I've requested similar feature in https://github.com/MuntashirAkon/AppManager/issues/464#issuecomment-1617508393 for multiple apps

> Optionally AM should allow installing All apps in background but for users safety by default they'll have to click install for each app one by one.

Not sure if no-confirmation installation is that useful though. Suppose you clicked **download** from Aurora/Droid-ify or clicked on an downloaded-apk file from file-manager mistakenly (and previously you've set "_complete action using AM install_" as **Always**) then it would auto-install without asking anything. Not good for security as Apps can request many unnecessary permission.

**Comment by MuntashirAkon** [comment]
Automated installation, in general, can have dire consequences, even when installing an update from popular apps such as Google Play Store as we saw in the past. That's why it is encouraged that such an action should be explicit instead of implicit. However, in this particular case, we cannot actually provide a way to allow automatic installation because there's no reliable way to detect the source of the APK(S) file. There are a few unreliable and undocumented ways (such as the one App Manager currently using to auto-detect certain app store), but since they're neither reliable (the only reason they are used in App Manager is that there's no chance of false-positives which is crucial for security) nor documented, we cannot build a user-facing interface for it. It'll be too costly for that. Instead, we're planning on providing some form of API to the third-party stores to use.
