### ISSUE TITLE
Freezed App Launcher

### ISSUE THREAD

**Issue by deadlevel13** [MuntashirAkon/AppManager#1469]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

When needed to launch a freezed app, you have to go to the App Manager, find the app, unfreeze, then launch it, that is way too many steps to open an apps

### Describe the solution you'd like

A seperated menu, like the Files one, that can be launched with a shortcut, have

- A list of all app freezed (temporary, have something to differences not added app from the list, app gone when defrosted and not added to the list) + added app (can only be add + remove by user), which
+ When click on one of the app, if the app is freezed, a confirmation forms show before launch the apps, else just launch it
+ A menu next to the app, which have a button inside to freeze the app, a button to add it to the list if not in, and some thing else

- A shortcut to freeze all the apps in the list

Bonus if you can: A notification to freeze each app, if not freezed and added to the freeze list. Yeah, that is too much, but still something i want

### Describe alternatives you've considered

I have used IceBox (which is really, where most of my idea is) + Island to do this thing, but:
+ My new phone (Redmi Note 13 4G) just refused to run this app, no matter anything i tried
+ Device Admin config is not fun at all

Then i tried to use AM profiles to do this, but:
+ When selected many apps (like 20 + of them), then run the profiles to freeze all of them, the result is way too random, some app freezed, some don't, so when i do need to freeze all of them, i just select all apps from the profile in the main menu, that works every time
+ Open AM to launch 1 of them takes a lot of steps, i thinks a mini menu to do this would work way better for many peoples

### Additional context

Sorry for my English, that is not my first language at all.

**Comment by MuntashirAkon** [comment]
This is not possible for many reasons:
1. There's already an alternative: profiles. If you're facing issues with freezing using profiles, you should report them instead of solving the problem in an xy manner. I personally use profiles to freeze/unfreeze a bunch of apps on a regular basis without any issues. For individual freeze/unfreeze, you can also leverage the freeze/unfreeze shortcut instead.
2. App Manager is a general-purpose app, unlike IceBox or Greenify. We care more about ideas that can cover a lot of users' needs, not just a few.
3. Finally, for this specific feature, the benefits outweigh the cost. There are already several ways to do the same thing you're trying to do, and many more options are coming in the future.

Files is a utility software, like Terminal or Log Viewer. I find the necessity of developing it because I wasn't satisfied with the existing solutions (e.g., among other issues, Material Files does not remember the last opened file paths and position, MiXplorer has good viewers, but it has similar issues with an old and ugly user interface), and App Manager already had a full file system implementation for backup/restore. There are also certain security guarantees (e.g., SSL pinning, and process isolation for viewers which is still under development) with App Manager that aren't present with MiXplorer.
