### ISSUE TITLE
Add support for dhizuku

### ISSUE THREAD

**Issue by Dantoza** [MuntashirAkon/AppManager#1481]
You said you don't wantsupport for shizuku because it is closed source. Well, dhizuku is open source and even more useful that shizuku. Would be great to implement that mode

**Comment by MuntashirAkon** [comment]
I think this issue was discussed before when Discussions tab was enabled. TL;DR Dhizuku supports only a handful of permissions, and most administrative tasks has to be handled through the non-standard DevicePolicyManager which requires a lot of code refactoring. Therefore, the cost outweighs the benefits.
