### ISSUE TITLE
Move the forced dev options navigation to Initializing hang (4.0.0-beta2)

### ISSUE THREAD

**Issue by schbrns** [MuntashirAkon/AppManager#1483]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

When enabling Wireless ADB, it's quicker to long-press the quick tile. This forced navigation adds extra steps.
It could still be used in the case of Initializing hang.

It should perform forced navigations to:
1. Accessibility menu if the permission is missing
2. Re-check Notification permission
3. Developer options menu if connection is not successful (with instructions to re-pair)

**Comment by MuntashirAkon** [comment]
> When enabling Wireless ADB, it's quicker to long-press the quick tile. This forced navigation adds extra steps.

App Manager enables wireless debugging automatically if it has enough permissions. No need to enable it yourself.

> It could still be used in the case of Initializing hang.

Addressed by 51f107fa2632e42eea030e0f91e48fe39d8f5836

> 1\. Accessibility menu if the permission is missing

App Manager does not use accessibility for enabling wireless debugging, because there's a better way. ADB pairing probably does not work with accessibility because as far as I know, accessibility in the pairing dialog is disabled for security reasons.

> 2\. Re-check Notification permission

While it's possible to check for the notification permission, it would add additional workflow if App Manager were to ask the user to grant it again. Because the notification permission prompt generated by the system can be used only twice. It does not work after that.

> 3\. Developer options menu if connection is not successful (with instructions to re-pair)

An unsuccessful connection does not imply that the pairing was not done before (sometimes ADB fails for no visible reason). This is why the dialog offers both options.

**Comment by schbrns** [comment]
> > When enabling Wireless ADB, it's quicker to long-press the quick tile. This forced navigation adds extra steps.
Sorry, I meant for the first-time pairing step. You still need to land on the Wireless ADB view to hit the Pairing code button and get the code. I just meant it's easier to 1) swipe down 2) long-press the Wireless ADB quicktile, instead of being force-navigated to the Dev Options and then having to scroll down to Wireless ADB to get to the pairing code button. 
It's not a big deal, I was just hoping the force-navigation "Cancel / Go" dialog could be bypassed.

Thank you for explaining the rest.

**Comment by schbrns** [comment]
![Screenshot_20241225_200806_Settings](https://github.com/user-attachments/assets/d0e02010-69a1-4dcd-a3b9-bd45b169c236)

Cancel prevents the follow-up notification to enter Pairing code. Go navigates the Wireless ADB window back to Developer options menu view.

![Screenshot_20241225_201247_Settings](https://github.com/user-attachments/assets/de93173b-22b1-44fd-95ee-39dbb95c25be)

**Comment by MuntashirAkon** [comment]
OK, so you want a "manual" option here? That's doable.

**Comment by schbrns** [comment]
> OK, so you want a "manual" option here? That's doable.

Please and thank you. Yeah, just an option that will trigger the pairing search without navigation.

**Comment by MuntashirAkon** [comment]
370e311c4bb43086f9859ec35f2f84a8b6a334f1
