### ISSUE TITLE
Unable to uninstall app manager from device

### ISSUE THREAD

**Issue by maahem** [MuntashirAkon/AppManager#159]
![Screenshot_20201121-132712_F-Droid](https://user-images.githubusercontent.com/74835136/99885515-8205db00-2c5b-11eb-8df9-179ecb1e27fa.jpg)
![Screenshot_20201121-132712_F-Droid](https://user-images.githubusercontent.com/74835136/99885523-8d590680-2c5b-11eb-8457-8b0f6495172d.jpg)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Crash logs**
If applicable, add crash logs to help us figure out the problem.

**Device info**
 - Device: [e.g. One Plus 8 Pro]
 - OS Version: [e.g. Android 10]
 - App Manager Version: [e.g. v2.5.13]
 - Mode: root/adb/no-root

**Additional context**

**Comment by maahem** [comment]
I have installed this from fdroid but now Im unable to remove it as it was consuming too much battery. 
I have samsung a6 2018 non rooted phone

**Comment by MuntashirAkon** [comment]
This could be due to a problem on your device. AM doesn't do anything to prevent users from uninstalling the app. If you have access to a PC, try checking the crash log using `adb logcat` that the Android package installer is generating. Also, try uninstalling from a decent uninstaller (F-Droid is particularly buggy on this matter) such as from the Android settings app.

> it was consuming too much battery.

AM doesn't run in background. It runs only on foreground. But your device's power management might be a little behind in which case you can disable battery optimisation or restrict AM from running in background (in case you forget to remove it from the recents).

**Comment by shandow856** [comment]
> 
> 
> I have installed this from fdroid but now Im unable to remove it as it was consuming too much battery.
> I have samsung a6 2018 non rooted phone

I have the same issue. I've removed it via adb so you may try it. Enable android debugging in setting. Download SDK platform tools on PC. Unzip and open the platform-tools folder in cmd or any other terminals. Connect the phone to PC. Type 
`
adb devices`
Ensure you see your devices. Type
`adb shell`

`pm list packages`
Find the app (io.github.muntashirakon.AppManager). Type
`pm uninstall -k --user 0 io.github.muntashirakon.AppManager`

**Comment by MuntashirAkon** [comment]
This bug is present mostly on Samsung phones and some variants of Lineage OS. It's an issue with the respective operating systems and there's nothing I can do without reverting an important feature.

If you have root, you can uninstall App Manager your favourite Terminal:
```sh
pm uninstall -k io.github.muntashirakon.AppManager
```

If you do not have root, you can do it this way using ADB:
```sh
adb shell pm uninstall -k io.github.muntashirakon.AppManager
```

In the upcoming version (v2.5.20), you can also uninstall App Manager from App Manager itself but you've to select “Keep data and signatures” first.

**Comment by Cyberavater** [comment]
Since it's a breaking issue for some devices, maybe keep it opened and pinned until it's fixed?

**Comment by MuntashirAkon** [comment]
> Since it's a breaking issue for some devices, maybe keep it opened and pinned until it's fixed?

Vendors such as Samsung do not care about issues reported by the users (or do not care about their users at all, see KNOX issues for instance). So, chances are they won't fix the issue in many years (unlike Lineage OS who were quick to fix it) until they realise that some of their own applications couldn't be uninstalled.

**Comment by MuntashirAkon** [comment]
We've added a guide for this in the community page: https://t.me/AppManagerCommunity/14

**Comment by Helloyouyesitsme** [comment]
> ![Screenshot_20201121-132712_F-Droid](https://user-images.githubusercontent.com/74835136/99885515-8205db00-2c5b-11eb-8df9-179ecb1e27fa.jpg) ![Screenshot_20201121-132712_F-Droid](https://user-images.githubusercontent.com/74835136/99885523-8d590680-2c5b-11eb-8457-8b0f6495172d.jpg)
> 
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behaviour:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Crash logs** If applicable, add crash logs to help us figure out the problem.
> 
> **Device info**
> 
> * Device: [e.g. One Plus 8 Pro]
> * OS Version: [e.g. Android 10]
> * App Manager Version: [e.g. v2.5.13]
> * Mode: root/adb/no-root
> 
> **Additional context** Add any other context about the problem here.

I have a moto G7 Pure no root I installed your app from f Droid and Droid isn't the problem this app is it seems people are getting an answer to where the answer is you have nothing to do with it it relies on Samsung or some operating system how can you give those answers when obviously I'm just like the other users who tried your app out and have neither one of that device or that operating system nor have root I shouldn't have to hook it up to computerand adb to remove it.

**Comment by MuntashirAkon** [comment]
> I have a moto G7 Pure no root I installed your app from f Droid and Droid isn't the problem this app is it seems people are getting an answer to where the answer is you have nothing to do with it it relies on Samsung or some operating system how can you give those answers when obviously I'm just like the other users who tried your app out and have neither one of that device or that operating system nor have root I shouldn't have to hook it up to computerand adb to remove it.

In your case, it may be due to a bug in the AOSP installer which is triggered when it lacks a mandatory permission. You can check if this is the case by following the steps below:
1. Open “Settings” app
2. Look for “Usage access” and navigate to the page
3. Click on the 3-dots menu and click “Show system”
4. In the app list there, find “Package Installer” (or something similar if it's been renamed)
5. Click on “Package Installer” and check if “Permit usage access” is enabled
6. If it's not enabled, enable it and try uninstalling App Manager once again.
