### ISSUE TITLE
"About Device" Option

### ISSUE THREAD

**Issue by RickyM7** [MuntashirAkon/AppManager#164]
## Is your feature request related to a problem? Please describe.
I think this may be off topic (regarding the purpose of the app), but I think it's something interesting to have in the app.

## Describe the solution you'd like
This would basically be an option with information about the device (hardware, software, etc). This option would be in the "More Options" floating menu.

## Describe alternatives you've considered
What I imagined was taking apps like [CPU-Z](https://play.google.com/store/apps/details?id=com.cpuid.cpu_z), [AIDA64](https://play.google.com/store/apps/details?id=com.finalwire.aida64) or [CPU Info](https://github.com/kamgurgul/cpu-info) as an example for this option (mainly CPU Info, as it is an Open Source app). These apps have several tabs with different information about CPU, GPU, Storage, Battery, etc.

#### Apps Features (From Play Store Description)

| CPU Info Features | CPU-Z Features | AIDA64 Features |
| --- | --- | --- |
| - CPU specification (with current frequency on specific cores) | - SoC (System On Chip) name, architecture, clock speed for each core | - CPU detection, real-time core clock measurement |
| - GPU specification | - System information : device brand & model, screen resolution, RAM, storage | - Screen dimensions, pixel density and camera information |
| - RAM and storage state (internal, external and SD card) | - Battery information : level, status, temperature, capacity | - Battery level and temperature monitoring |
| - Display metrics | - Sensors | - WiFi and cellular network information |
| - Android OS details | | - Android OS and Dalvik properties |
| - Sensors data | | - SoC and device model identification |
| - Battery status | | - Memory and storage utilization |
| - WiFi and Bluetooth mac address (on older Androids) | | - OpenGL ES GPU details, real-time GPU clock measurement |
| - Audio card info | | - Vulkan, OpenCL, CUDA, PCI, USB device listing |
| - Native libraries used in another applications | | - Sensor polling |
| - CPU and battery temperature monitor | | - Listing of installed apps, codecs and system directories |
| | | - Android Wear module: native app for watches |

**Comment by bbigam** [comment]
My opinion: add a Phone Info page, but keep it focused on only what's directly relevant to this being an _App Manager_. So display just what phone information is directly related to the information already shown for each app. What is this phone's current SDK & Android version, arch, etc. Mostly some of what's on the "Android" page of the app CPU Info, plus ABI/arch.

These basics could be helpful especially to new users who are discovering, for example, "Oh, App X targets sdk30 and I'm running sdk29, maybe that's why this feature or permission isn't exactly what I expected."

But I'd prefer to see App Manager stay focused on managing apps, and not become a general system info app with extra features like sensor polling, battery, RAM, etc. It's so good at the app part, and doesn't need to do everything.

Just my opinion as a happy user!

**Comment by RickyM7** [comment]
@bbigam Yes, as I wrote in the issue, this function may be a bit off topic compared to the purpose of the app, but I think having a share of the features of these apps (or all features, but really not necessary) would be really interesting. The problem is that I don't know which features would be suitable for the AM, so I listed them all in the additional context section.

**Comment by MuntashirAkon** [comment]
I've decided to follow @bbigam's opinion and add features directly relevant to AM. Due to design issues, they will be available under “About Phone” section in the settings page. I can remember the following properties right now:
- Android build version
- Android release version
- SDK
- Build ID
- Device hardware name
- Supported architectures aka ABI
- System locale(s)
- Screen resolution aka DPI
- No. of installed apps: all, system, user
- No. of users

**Comment by RickyM7** [comment]
@MuntashirAkon This is great in my opinion, but I think there are other features that you could take into consideration, like: 
- [CPU] Basic information, core usage and temperature. 
- [GPU] Basic information. 
- [RAM] Total memory and available memory. 
- [Internal/External Storage] Total memory and available memory. 
- [Android Information] Everything that is available in the CPU info. 
- [Battery] Information and temperature.

 (All this based on the CPU info features)

**Comment by MuntashirAkon** [comment]
My understanding is that **About Phone** is a section where people looks for static info ie. the info which never/hardly change. CPU/RAM usage is not something that people will look for there. It would be better if they were available at the running apps page (as headers) instead.

For CPU, I can include the following:
1. SoC
2. ABIs
3. No. of cores

For RAM, I'll only include total RAM.

I forgot about GPU, which is also important since GL ES version plays a role here. So, this info will not only be available in the **About Phone** section, but also in the **Configurations** and **Uses Features** tab so that people can easily check which configurations/features are compatible.

Storage info has to be overlooked since AM has nothing to do with storage. It's something that a File Manager should do.

I agree with you about Android information. I'll add everything that are available there.

Battery info will include basic “static” info. Dynamic info should be available in the App Info tab and/or in the Running Apps page.

This also reminds me, I should also include basic hardware info which are usually specified in the manifest as **uses features**. There will be _available_ tag in the **uses features** tab (beside the features that are available in the device).

**Comment by RickyM7** [comment]
@MuntashirAkon Having static information in "About Phone" and dynamic information in "Running Apps" is perfect in my opinion.
Thank you for the explanations and for accepting this request.

**Comment by bbigam** [comment]
@MuntashirAkon Sounds like a great plan and thanks for taking feedback and suggestions so graciously!
@RickyM7 Great idea!

One more thought though: App Manager is also useful on tablets, so call it "About Device" instead of "About Phone" unless you can dynamically detect whether it's a tablet or phone to generate the page title and menu item. It's on my mind because I just got a Fire tablet and App Manager was on my list of first apps to install once I sideloaded F-Droid. :-)

**Comment by MuntashirAkon** [comment]
> App Manager is also useful on tablets, so call it "About Device" instead of "About Phone" unless you can dynamically detect whether it's a tablet or phone to generate the page title and menu item. It's on my mind because I just got a Fire tablet and App Manager was on my list of first apps to install once I sideloaded F-Droid.

Thanks. It's great to know that AM is one of the first apps in your list of choices! And thanks for reminding me about the title. AM also has a handful of Android TV users. So, I agree that it's better to use a generic name such as “About Device” for now.

**Comment by RickyM7** [comment]
@MuntashirAkon I think you could add the "GPU Renderer" in Graphics and add a section with basic screen information as well.
Incidentally, I tested the last Debug Build and I think that first information (Version, SDK, etc) should be one below the other and not divided by comma.

**Comment by MuntashirAkon** [comment]
@RickyM7 Please wait until the implementation is complete. There are still many things to do there (some needs native code, I'm afraid). I'll post an update when it is complete.

**Comment by RickyM7** [comment]
@MuntashirAkon Of course, sorry about that.

**Comment by MuntashirAkon** [comment]
By 112e7446, this feature has become more or less complete. There may still be some indices that can be added but I'll skip them for now. You're free to suggest anything that I might have missed.

**Comment by RickyM7** [comment]
@MuntashirAkon I think the information available on the page is sufficient because it encompasses practically or maybe everything you may need to know to use the AM. Maybe one thing or another can be added to complement the page but I'm not sure what could be added. Maybe it's a good idea for you to take a look at [AIDA64](https://play.google.com/store/apps/details?id=com.finalwire.aida64) because it's the most complete app about it (I think), but it's a closed source app.
Anyway, thanks for working on this feature.

**Comment by MuntashirAkon** [comment]
> Maybe one thing or another can be added to complement the page but I'm not sure what could be added. Maybe it's a good idea for you to take a look at [AIDA64](https://play.google.com/store/apps/details?id=com.finalwire.aida64) because it's the most complete app about it (I think), but it's a closed source app.

I'm leaving it for the user to find out if it needs to display more info than it is now.

**Comment by RickyM7** [comment]
@MuntashirAkon Sorry i'm commenting on an issue already closed, but you'll still work on it? It is that there are two small problems and I would like to know if they can be solved before the release of v2.5.23.

| ![android-version](https://user-images.githubusercontent.com/24703825/105489442-fbd53780-5c91-11eb-802b-000e9af7cdbf.jpg) | In this part it is not clear what this version is. Even if you can assume what it is, it would be ideal for the string here to be `OS Version` instead of `Version`. |
| --- | --- |
| ![apps](https://user-images.githubusercontent.com/24703825/105489447-fed02800-5c91-11eb-8d91-a2f69ad3d64e.jpg) | The apps info are in the `Languages` section instead of in a separate section. I don't know if that's expected but I think it would be better to have a separate section for this. |

**Comment by MuntashirAkon** [comment]
> The apps info are in the `Languages` section instead of in a separate section. I don't know if that's expected but I think it would be better to have a separate section for this.

This seems to be a bug, only visible to the no-root users.

**Comment by MuntashirAkon** [comment]
Fixed via 2d830b8d

**Comment by RickyM7** [comment]
> This seems to be a bug, only visible to the no-root users.

Got it! Btw, the AM crashes if you change the mode of operation to `root` or `ADB over TCP` and try to open the `About device` option, that is if you have no root, of course, but the AM does not generate any crash log.
