### ISSUE TITLE
SERIUOS BUG PLEASE HELP Am not disabling components AT ALL 

### ISSUE THREAD

**Issue by ale82to** [MuntashirAkon/AppManager#177]
AM is not disabling components for me please see the screenshot 
to better understand what I meandisabling share intent activity with my android tools also remove Foldersync from android sharing sheet why AM IS NOT WORKING AT ALL?
![screen](https://user-images.githubusercontent.com/3341224/100891429-8a5ee100-34b9-11eb-9250-af24f63bc0a1.png)

**Comment by MuntashirAkon** [comment]
I've already answered the question on TG. In short, AM didn't disable the component rather it blocked it which is why the app wasn't able to detect that the component was blocked. This is pretty much how Intent firewall (IFW) works.

Related documentation: https://muntashirakon.github.io/AppManager/faq/app-components.html#why-are-the-components-blocked-by-am-not-detected-by-other-related-apps
