### ISSUE TITLE
UI/UX improvement suggestions

### ISSUE THREAD

**Issue by Cyberavater** [MuntashirAkon/AppManager#190]
Onboard;

1. [x] Add package Icon on the Onboard page for uninstalled but backed up apps.
2. [x] Add a new sort by option named Last changes/actions. This will sort packages according to any action I took for a package, i.e. Installed, Disabled, Backed up via AM, Uninstalled, Blocked components via AM, you get the point.
3. [x] Batch selection: If I select one app on Onboard and press and hold on another app, everything else in between should be selected as well.
4. [x] Currently it takes a long time to load apps (when 400+). Should the database (mentioned here https://github.com/MuntashirAkon/AppManager/issues/236#issuecomment-761564921) fix this issue? LP uses loaded apps from the first launch and updates them accordingly. So except for the first launch, it loads quite fast.

UI Bugs
1. [x] Refreshing the Onboard page keeps the apps selected but takes away the selection color.
2. [x] Select one specific filter, then close the app (even from the "Recent apps"). Relaunch AM you'll see that the filter is not selected but AM only showing those apps as if the filter is selected.

Backup menu;

1. [x] For uninstalled apps there is no need for keeping the backup button, Only the restore button is enough there.
2. [x] Backup menu redesign;

Backup Components:

◘ APK                      ◘ Data
◘ External Data       ◘ OBB and Media
◘ Source                 ◘ Cache

Backup App Settings: ▼-(Here  will be a separate drop-down menu, the list will be shown after the user presses on it, both the text and icon)
◘ Permission          ◘ Blocking Rules
◘ Various Stats (not implemented yet)

Backup Behavior(/Settings): ▼
◘ Skip Signature check  ◘ All Users
◘ Backup multiple

The Submenu design should give the user a clean UI experience.

**Comment by Cyberavater** [comment]
I've updated the OP, should be easier to understand now.

**Comment by MuntashirAkon** [comment]
While I agree that backup options should tailored a bit but not the way you've mentioned here. The options present there are all equally important (backup is not something one does everyday) and it will reduce the UX if additional workflow is added. The users can always set presets in settings if they don't need to use some options too often. The sequence of options should be as follows (along with descriptions):
1. **Source.** Back up entire the source directory
2. **APK only.** Back up only the APK files from the source directory (not functional if option 1 is not clicked)
3. **Data.** Back up data folders
4. **External data.** Back up external data folders (requires option 3 to be enabled)
5. **OBB and media.** Back up OBB and media folders
6. **Exclude cache.** Don't back up cache/code_cache/no_backup folders
7. **Extras.** (replacing permissions) Back up app permissions, battery saving, data usage options, MagiskHide status
8. **Rules.** Back up rules configured within AM
9. **Multiple.** Perform a separate _named_ backup instead of the _base_ backup
10. **All users.** Perform back up for all users
11. **Skip signature checks.** Useful for restoring backups which are failing due to checksum verification failure or has different APK signature than the backed up one.

Philosophy behind not adding the last three options in settings:
1. **Skip signature checks.** Most backups will not need this option. It is needed—

    - For backups that have a different APK signature than the installed ones
    - For backups with KeyStore files and the masterkey that currently present or not present is different from the one during the backups were taken
    - For backups that have been tampered with.

   Adding this option in the settings will give rise to a security issue.

2. **Back up multiple.** This option is needed only when the user wants a backup that is different from the base backup. The user may one time choose to override the existing backup by not selecting it and in other time, may choose to create a different backup by selecting it. So, adding it in settings won't do much good other than increasing the hassle of navigating to settings each time they choose to switch their preferences.

3. **All users.** Similar to back up multiple, one may choose to back up only certain apps for all users in one time and the opposite it other time. Navigating to settings just to enable/disable it every time is an unnecessary overhead.

The dialog might seem a little verbose but this is what AM is. For instance, I had to downgrade to ViewPager because ViewPager2 has troubles loading the tabs in the app details page because there are too much information to load in a single screen (you'll realise that if you start counting) and that, there are more than 30 info to display per app in the main page.

I hope you've understood why I did it this way.

**Comment by Cyberavater** [comment]
I get that every option is required/useful. That's why I didn't ask to remove any of it, rather categorizing them by their nature to have a cleaner UI. The 2 columns and the dropdown menu for the less-needed category should also help in this regard.

If Source is a superset of both APK and Data, both should be grayed out if Source is already selected.

**Comment by Cyberavater** [comment]
Also, I can guarantee you that that cleaner UI will also improve UX. You can create a poll on the Telegram group, linking this issue to better understand users' views on this.

**Comment by MuntashirAkon** [comment]
> If Source is a superset of both APK and Data, both should be grayed out if Source is already selected.

I agree. But this will take months as developing a custom UI needs a lot of time and it's not something that I currently have in mind. (I'm literally running out of my time as this pandemic is waning away in this part.)

> The 2 columns and the dropdown menu for the less-needed category should also help in this regard.

To me, all options have equal priority as I use all of them all the time. You suggestions will make the UI more complicated because the user has to remember the position of these options rather than just skimming over all the options (even I don't remember all the options all the time and having a look at all the options refreshes my memory).

> You can create a poll on the Telegram group, linking this issue to better understand users' views on this.

I'll rather wait for the final release.

**Comment by Cyberavater** [comment]
Hmm, having similar options together is very natural, and 2 columns would help to see the whole page on one screen.

>the user has to remember the position of these options

That's what the heading is there for, to describe the nature of the content. 

> just skimming over all the options (even I don't remember all the options all the time and having a look at all the options refreshes my memory).

The Dropdown menu would do that job with less action (1/2 click) than scrolling all the way down, maybe I failed to describe its design.

Anyway, even if you don't like the Dropdown menu idea, categorizing all options with a heading should still make the UI look more elegant.

**Comment by MuntashirAkon** [comment]
> Anyway, even if you don't like the Dropdown menu idea, categorizing all options with a heading should still make the UI look more elegant.

Yeah, this could be done.

**Comment by MuntashirAkon** [comment]
Backup options are now reordered in f008babe.

**Comment by MuntashirAkon** [comment]
AM now displays icon for backed up but uninstalled app (040461ed).

**Comment by Cyberavater** [comment]
I've added another suggestion in OP namely, O (3)

**Comment by Cyberavater** [comment]
I've updated OP with some more suggestions

> AM now displays the icon for backed up but uninstalled app (040461e).

I don't see it latest debug, can you re-check, please?

**Comment by MuntashirAkon** [comment]
> I don't see it in the latest debug, can you re-check, please?

Icons won't display if you're using external SD card.

**Comment by MuntashirAkon** [comment]
> I've updated OP with some more suggestions

Bugs ≠ Suggestions. Next time use a separate issue for reporting bugs. This issue already covers a lot.

**Comment by Cyberavater** [comment]
> Icons won't display if you're using external SD card.

Can you add icon support for ExtSdCard too?

**Comment by MuntashirAkon** [comment]
> Can you add icon support for ExtSdCard too?

Fixed via 38abc068.
