### ISSUE TITLE
Blocking trackers in apps

### ISSUE THREAD

**Issue by molitona** [MuntashirAkon/AppManager#206]
Hi everyone, first, thank you for the amazing app. Then after that, I wanna know what does the App Manager technically do when It blocks a tracker in an app ?
And does It work with all apps (because, I have tested many apps like Warden to no avail).
The functionality that I'm talking about is in "1-Click Ops" --> "Block/Unblock trackers".
Please, I wanna a detailed explanation of what It is done if you don't mind. Thanks.

**Comment by MuntashirAkon** [comment]
> I wanna know what does the App Manager technically do when It blocks a tracker in an app ?

First you have to know what the term _tracker_ means in AM. As stated in the [FAQ](https://muntashirakon.github.io/AppManager/faq/app-components.html#tracker-classes-versus-tracker-components), AM blocks tracker components, not tracker classes (that you see in the scanner page). So, when you see `20 trackers` in the App Info page, it means that there are 20 tracker components and at least 20 tracker classes in the app. They don't specify the actual number of trackers that you see in the scanner page.

Tracker components are blocked like any other app components using Intent Firewall (see [related FAQ](https://muntashirakon.github.io/AppManager/faq/app-components.html#why-are-the-components-blocked-by-am-not-detected-by-other-related-apps) and [this difference](https://github.com/lihenggui/blocker#differences-between-intent-firewall-and-package-manager)).

> And does It work with all apps (because, I have tested many apps like Warden to no avail).

If you followed the links, you'd know why Intent Firewall (IFW) is far more superior to the traditional `pm disable` method that apps like Warden are using. But even IFW has limitations: It works with all _user_ apps but may not work with all _system_ apps. Here are the few reasons as to why IFW might fail:
- The app in question is whitelisted by the system such as Android System, System UI, Phone Services. This whitelist consists of critical apps that are required in order to function properly. They will run even if you disable them or block their components.
- Another system app or system process is calling the specific component of the app in question via interprocess communication (IPC) in which case the component will be activated regardless of its presence in the IFW rules or even if the entire app is disabled (see #105). If you have such system apps, the only way is to get rid of them. I'm working on a feature to get rid of such apps systemless-ly (#150).

**Comment by molitona** [comment]
Ok fine, as I understand the number shown when I click "1-Click Ops --> Block trackers" is the number of tracking components in each app.

Please, if you can confirm those :

In the picture below of Ampere app there are 2 tracker/ads, the first is implemented in 1 class, the second in 5 classes, is that right ?

![dc3f0ed7-9d17-4252-95f7-2272e67817f1](https://user-images.githubusercontent.com/35532337/103369497-91820a80-4aca-11eb-8d4f-972c94446d7b.png)

In 1-Click ops, I don't see Ampere app even if It contains 2 trackers, why ? (Is that because they are all tracker classes so they cannot be blocked, They can only be removed by editing the app itself as you mentioned in the docs ?)

![25797157-4b7d-4faa-82fb-71c7cc561e6a](https://user-images.githubusercontent.com/35532337/103369521-a3fc4400-4aca-11eb-9def-d587f46c38e2.png)

**Comment by MuntashirAkon** [comment]
> In the picture below of Ampere app there are 2 tracker/ads, the first is implemented in 5 classes, the second in 71 classes, is that right ?

Yes.

> Is that because they are all tracker classes so they cannot be blocked, They can only be removed by editing the app itself as you mentioned in the docs ?

Yes, you are correct.

> And the number between () Is it of tracking components ?

Yes.


> What's the difference between Block trackers below button (seen in all components) and 1-Click ops - Block trackers

None. The former is for individual apps and the latter is for all apps.

**Comment by molitona** [comment]
> None. The former is for individual apps and the latter is for all apps.
So, as I understand block trackers button in services component only block services trackers, and the same for the other 3 components (activities, receivers, providers), in contrast to 1-Click ops which block them 4 in the same time.
Is that right ?

**Comment by MuntashirAkon** [comment]
> block trackers button in services component only block services trackers, and the same for the other 3 components (activities, receivers, providers), in contrast to 1-Click ops which block them 4 in the same time.
> Is that right ?

No, the four tabs are jointly known as the component tabs, and _block trackers_ and _sorting_ options are applicable for all of them. So, if you choose to block trackers in one tab, the blocking will be applied for all the app components.

**Comment by molitona** [comment]
I understand, thanks 💯

**Comment by MuntashirAkon** [comment]
Thanks for asking the questions. I'll be closing the issue _after_ I add some improvements to the docs.

**Comment by molitona** [comment]
I always want to understand how things go, not only using them, all thanks to you :))

**Comment by MuntashirAkon** [comment]
Closed via 9912a850
