### ISSUE TITLE
Permissions types in the app.

### ISSUE THREAD

**Issue by molitona** [MuntashirAkon/AppManager#209]
Hi, thanks for your great support and helping us to better understand android things.

After that, in android developers docs they classified permissions to 3 types :

Install-time (sub-types including normal permissions and signature permissions), Run-time and Special permissions.
https://developer.android.com/guide/topics/permissions/overview

I have 3 question here :

1- Where each of the 3 permissions types (Install-time,Run-time,Special) are declared in the app developement (in which files(androidmanifest.xml...?).

2- Is AppOps permissions same as Install-time permissions or what ?

3- How can edit each of them (Install-time,Run-time,Special) ?

I understand that Run-time permissions and Special permissions can be eddited via settings (if you could confirm).

But, for Install-time permissions how can I edit them (there is an app called AppOpsx that claims to do that, as well as your 3 tabs (USES PERMISSIONS, APP OPS, PERMISSIONS)

So, how can I edit Install-time permissions ?

Hint : I read the docs, but I still not having a response for those questions.
Thanks.

**Comment by MuntashirAkon** [comment]
> in android developers docs they classified permissions to 3 types :
> 
> Install-time (sub-types including normal permissions and signature permissions), Run-time and Special permissions.
> https://developer.android.com/guide/topics/permissions/overview

> 1- Where each of the 3 permissions types (Install-time,Run-time,Special) are declared in the app developement (in which files(androidmanifest.xml...?).

In order to understand how permissions work, you have to forget the classification described by Google in the link. Because this is not exactly how permissions are defined in Android. In Android framework, permissions are classified based on _protection level_. There are 4 basic protection levels:
1. **Dangerous.** These permissions are also known as runtime permissions (as stated in the link). It means that the app has to ask for the permissions explicitly and the user has to allow them manually. Note that the dangerous-ness of a permission is determined by Google, so there's not much choice for us about it unless you use Graphene OS, for example.
2. **Normal.** These permissions are granted by default if they are present in the Manifest. There's not much you can do about them other than editing them off the Manifest.
3. **Signature.** As mentioned in the link above, they must match the signature of the app where the permission is defined. But this isn't always the case. As you will see soon, it depends on other protection flags.
4. **SignatureOrPrivileged.** Like _signature_, they must match the signature of the app where the permission is defined.

They can have multiple flags:
- **privileged.** Privileged permission means they can't be granted like normal or dangerous permissions. This was known as **system** before API 23.
- **appop.** The permission is associated with an app operation.
- **development.** These are _allowed_ permissions and can be enabled using the `pm` command using ADB or root. Few permissions such as PACKAGE_USAGE_STATS can also be asked by the app where you have to enable it by navigating to an activity in settings. _signature_, _privileged_ flags are ignored for these permissions and can be granted to any app if the permission is defined in the Manifest.
- **runtime.** These permissions can only be granted in runtime ie. explicitly asked to the user.

and so on.

> Is AppOps permissions same as Install-time permissions or what ?

As mentioned different times, app ops is completely different from permissions in terms of implementation. But behind the scene, both control Interprocess Communication (IPC) which is why many developers don't distinguish between the two. Some permissions are associated with app operations but they have very weird relationships and their functionalities depend largely on OS versions.

> How can edit each of them (Install-time,Run-time,Special) ?

Permissions can be removed only by editing Manifest. But you can grant/revoke runtime and some development permissions either from Android settings or from AM (provided you have root/ADB permission).

> there is an app called AppOpsx that claims to do that, as well as your 3 tabs (USES PERMISSIONS, APP OPS, PERMISSIONS)

AppOpsX cannot revoke normal permissions and neither does AM. Because it's not possible. AppOpsX has added two custom app operations to disable the Internet permissions. But in the background, it actually maintain entries in the ip table (consider it to be a simplified version of AFWall+).

**Comment by molitona** [comment]
as I understand, 
USES PERMISSIONS tab only display manifest file permissions. (it cannot edit them), is that right ?

for, APP OPS tab, does it shows those one with appop flag ? and I'm able to edit them ?

but, what about PERMISSIONS tab, what flags does it shows ?


reply to ###  AppOpsX has added two custom app operations to disable the Internet permissions

But, it can disable other perms shown when i download an app like read sdcard,run in background ?

**Comment by MuntashirAkon** [comment]
> But, it can disable other perms shown when i download an app like read sdcard,run in background ?

Reading/writing SD Card are two dangerous permissions and can be disabled from settings (or by AM or by AppOpsX). RUN_IN_BACKGROUND is an app op (not a permission per se) and can be disabled in the app ops section of AM if you have chosen to display the default (aka permission-less) app ops. The bad thing about apps like App Ops or AppOpX are that they've confused their users about permissions and app ops (App Ops authors have explicitly stated the differences between the two in the docs but who reads docs anyway).

> USES PERMISSIONS tab only display manifest file permissions. (it cannot edit them), is that right ?

As mentioned in the docs, uses permissions tab displays the permissions under the `uses-permission` tag in the Manifest. These permissions are defined by other apps and the app has declared them so that it can request them. And the permissions tab displays the permissions _defined_ by the app in question. You can only grant or revoke any dangerous or development permissions in AM (to be more precise, in Android). _Edit_ isn't the right word here. (You can also edit the app manifest and remove the permissions but that has other consequences.)

> but, what about PERMISSIONS tab, what flags does it shows ?

The differences between permissions and uses permissions are described above. The flags behave exactly the same. _Any app can introduce new permissions with pre-existing flags._ But no two app can define the same permission.

> for, APP OPS tab, does it shows those one with appop flag ? and I'm able to edit them ?

As I've said multiple times both here and in the docs, permissions are not always the same as app ops. They are two different concepts and are handled different ways in the different versions of Android. You can set specific mode to them or simply use the toggle button next to them to turn them on or off. App ops are a OS feature. They cannot be specified in the app manifest and thus, can't be removed. They can only be enabled or disabled.

**Comment by molitona** [comment]
Thanks
