### ISSUE TITLE
Ability to link up with APK Updater or have it integrated in Application Manager

### ISSUE THREAD

**Issue by Deerp1976** [MuntashirAkon/AppManager#22]
You've managed to include all my favourite applications into one so very much appreciate that. Well done. 

What are the chances of integrating APK Updater into your app or link to it?  Being able to update apks from within your app would make this app perfect. Even just seeing that there is an update available via APK Updater would be ideal.

**Comment by MuntashirAkon** [comment]
> You've managed to include all my favourite applications into one so very much appreciate that. Well done.

Yeah. Basically I managed to include all *my* favourite apps into one!

> What are the chances of integrating APK Updater into your app or link to it?

I'll look into it.

**Comment by 5c0tt-b0t** [comment]
+1 !!! great idea!, I also have one related to this, to complete it as the ONLY "all-in-one" app manager: 
- Include the functions of 'OAndBackup' (or its successor 'OAndBackupX') to allow backup/restore of our apps.
I feel thats it, EVERYTHING an app manager could possibly do, finally from ONE app!
I would like to THANK YOU VERY MUCH! for this app, its one of my all-time favourites! and its not even old!! plus, thank you for using Git so well, I mean, documenting everything you find with links to references etc, so one can learn from your jouney too, it is admirable! (a while back, I was actually planning to write a shell script that could handle App Ops / Intent Fire Wall as I wasn't happy with: AppOpsX, MyAndroidTools, Greenify etc. I found good references are pretty rare! so GREAT JOB!!!) Thank you, best wishes to you and this incredible app.

**Comment by Deerp1976** [comment]
> **+1** great idea!, I also have one related to this, to complete it as the **ONLY** "all-in-one" app manager:
> 
> * Include the functions of 'OAndBackup' (or its successor 'OAndBackupX') to allow backup/restore of our apps.
> 
> I feel thats it, **EVERYTHING** an app manager could possibly do, finally from only **ONE** app!
> I would like to **THANK YOU SO MUCH!** for this app, its one of my all-time favourites! and its not even old!! plus, thank you for using Git so well, I mean, documenting everything you find with links to references etc, so one can learn from your jouney too, it is **admirable!** (a while back, I was actually planning to write a shell script that could handle App Ops / Intent Fire Wall as I wasn't happy with: AppOpsX, MyAndroidTools, Greenify etc. I found good references are pretty rare! so **GREAT JOB!!!**)

Do you mean the ability to copy app data from the data folder like what Titanium can do? This is a great idea. I often install and delete apps so being able to save that data and upload it to a cloud service would be great. 

You can only do this if rooted though cant you?

**Comment by MuntashirAkon** [comment]
> You can only do this if rooted though cant you?

Accessing `/data/data` requires root permission or the app has to be system app (not just any privileged app). Even ADB shell doesn't work.

**Comment by MuntashirAkon** [comment]
> I found good references are pretty rare!

That's the irony of developing apps that do system tasks: There's not a single documentation on how to use them, at least, in English. Take AppOps as an example: all documentations I found are actually in Chinese and I had to use Google translation to read them. Source code of many open source softwares are incredibly ugly and difficult to read or understand.

**Comment by Deerp1976** [comment]
> > You can only do this if rooted though cant you?
> 
> Accessing `/data/data` requires root permission or the app has to be system app (not just any privileged app). Even ADB shell doesn't work.

Not necessarily. I can access FX File Explorer, see all the apps folders including all the system ones and even open up FX File Explorers folder to view everything inside. I can see it has its own busybox, has kept cache files of all images I've opened up on FX. I can do the same with 3c Toolbox Pro but only if I copy the path into their data/data folder and can see they have an xposed option with its own folder inside their data folder.

Solid Explorer won't even show you there is a data folder on your phone.

![Screenshot_20200622_025047_nextapp fx](https://user-images.githubusercontent.com/61953306/85250996-04d9fe00-b450-11ea-9e58-ee2adbf14f77.jpg)
![Screenshot_20200622_025302_ccc71 at free](https://user-images.githubusercontent.com/61953306/85251008-10c5c000-b450-11ea-912f-7be3f3d2aacd.jpg)

**Comment by MuntashirAkon** [comment]
> Not necessarily.

An app, of course, has access to it's own directories. Otherwise it couldn't store any data! Access to `/data/app` doesn't require root, rather some clever tricks which these file managers have applied, I think. Reading `/data/app` directly isn't possible using the typical directory listing methods.

Anyway, this is off-topic to this thread and should be discussed in #21. Generally speaking, these file explorers don't support opening files from any third-pary app. So, you can try contacting them instead of me.

**Comment by 5c0tt-b0t** [comment]
Busybox is very useful, and can be bundled into an app too, useful **IF** your phone doesnt have it already installed in /system/bin or /system/xbin, but root is still required to extract/backup that data you see in your screenshots. 
Alot of phones nowadays have toybox installed, this achieves the same thing but more widely available in unrooted phones (toybox doesnt cover everything as project isnt finished yet, so not even on release 1.0 yet, will be amazing once its finished though)
In fact, root **AND** *either* busybox **or** toybox are needed by apps like OAndBackupX to do backup **all** data.

**Comment by MuntashirAkon** [comment]
If I were to support backup/restore feature, I would definitely follow OAB. But since the devs of OpenKeychain are yet to release an update of their API supporting Androidx, encryption through OpenKeychain will not work which, by the way, is very sad. I'm on Android 10 but still using OAB instead of OABX as the latter doesn't support encryption through OpenKeychain last time I checked.

**Comment by MuntashirAkon** [comment]
APK Updater has only a single activity and what I can do at best is to add a direct link to APK Updater. While an updater may seem to be a valuable part of an app manager, the updating mechanism used by APK Updater are rather hacky.

### What can I do about it?
I can add support for APK Mirror and F-Droid. APK Mirror is just about parsing the site itself but F-droid is about downloading a large repository (bad design I guess). Then there are custom repositories like IzzyOnDroid, Guardian, Bromite, etc. I can match apk certificates hashes to differentiate between these repo and verson codes to determine if an update is really available (APK Mirror supports filtering APKs by hashes but doesn't display version codes though).

I can copy the required implementations for F-Droid from F-droid and Aurora Droid but I'm not sure if there's any open source app which filters apk mirror apps by certificate hashes (signature verification plays an imortant role in determining if an app is modified). APK Grabber is also a nice app similar to APK Updater.

### What are my plans on this
Since there are apps which are solely developed for updating applications, I don't see any immediate neccessity for such apps. Besides there's already an option to navigate to F-Droid or Aurora Droid app in the App Info section. But I may reconsider in future if demands for such feature increases.

**Comment by 5c0tt-b0t** [comment]
I agree completely! great analysis!!

- not a fundamental feature: just a nice one.
- implementing will likely be alot of work / bloat the app
- there are open source alternatives dedicated to to this function (that contain no ads/trackers)(F-Droid, Aurora-Droid, APKupdater etc)

Your idea to open the app listed, in these stores would be great though!
Just an idea... the last icon, the 'aurora-droid' icon, could be an app store button, clicking it shows one dialog on screen, with these:

- Aurora-Droid
- Aurora-Store
- APKupdater
- F-Droid

These are the four open source stores that we all should be using. I understand you can request installed packages, as to only show the apps we have installed, so in my case: (example)

- Aurora-Droid
- Aurora-Store

Whereas the author's may list as: (example)

- APKupdater
- F-Droid

Again, not *fundamental* but definately slick! it would make the app update process alot quicker, whilst most of my apps are from Aurora-Droid (which, the shortcut is already implemented) some apps are from the Play Store, so to be able to go to Aurora-Store/APKupdater would be a very nice feature TBH.
I know that apps (links to) can be directly opened in the Aurora-Store (like it already does for Aurora-Droid) but I'm not sure if an app can be directly opened from APKupdater? would have to test that out...
Seeing as this is already something implemented (just for one store) would this be something that could be done?
I think that feature alone would answer the 'app-update' request sufficiently.

**Comment by MuntashirAkon** [comment]
The current implementation (originally issued by @Atrate) involves Aurora Droid and F-Droid (F-Droid is hidden if Aurora Droid is installed). APK Updater doesn't have any interface for a single app (as I said above, it has a single activity), consequently it doesn't support app opening like the other apps you mentioned. So, there are three apps: **Aurora Droid**, **Aurora Store**, **F-Droid**. All of them has separate UI to display app info and can be opened as though they're part of this app (as all of them use `finish()` to finish the activity). I've already implemented Aurora Droid and F-Droid, Aurora Store is all that remains (I haven't looked at its source code yet but I can assume it would be similar to Aurora Droid). These are only displayed if user have them installed. The logic behind F-Droid being hidden was that no user installs Aurora Droid unless he want to use it. However, there's still room for the debate.

**Comment by 5c0tt-b0t** [comment]
Perfect! just Aurora-Store to add then.

**To implement this:**

(if Aurora-Store is installed) then it displays either:

- A second Aurora icon next to the original one, a 'Aurora-Store' icon.

If not it would mean:

- Changing Aurora-Store icon to a more generap Aurora icon or general app store icon (the bag/basket icon etc)
- Implementing a dialog showing both options.

**Further observation:**

Adding a button for APKupdater to open a specific app isnt possible and it wouldnt be a smooth experience navigating from the specific app in App Manager, to the main activity of APKupdater (as this wont show the app, just the main screen)
What APKupdater does show though is *all* updates for all apps so I think a nice way to implement this (opening APKupdaters main acrivity) would be in the App Manager's app list screen (that shows all apps) inside the menu:

**Comment by MuntashirAkon** [comment]
**Aurora Droid** is named `aurora` as before and **Aurora Store** is named `store`. APK Updater is added in the overflow menu of the main activity.
