### ISSUE TITLE
Custom labels creation for filter 

### ISSUE THREAD

**Issue by Cyberavater** [MuntashirAkon/AppManager#236]
Apps that I'd want just after migration, I'd like to have them under a Filter created by myself, for example, called "Migration".
Apps that are required to hack games 'X', I'd like to have them under a Filter created by myself, for example, called "X".

This is just a basic idea of the custom filter preset.
Not sure if it's related to #197 anyhow.

**Comment by MuntashirAkon** [comment]
Filtering needs a revamp but even before that AM needs a database for storing all apps.

**Comment by MuntashirAkon** [comment]
An initial feasibility analysis suggests that custom filters should go with profiles. So, AM can at best allow filtering using profiles and not more than that. The workflow would be something like this:
1. Create a profile (in your example `X`)
2. Add your desired apps in the profile
3. In the main page, go to filters
4. Select your desired filter or a profile

I think this is the best approach since you can easily import/export profiles.

**Comment by MuntashirAkon** [comment]
Related to #162.

**Comment by MuntashirAkon** [comment]
Implemented in b370b676
