### ISSUE TITLE
Auto permission removal feature.

### ISSUE THREAD

**Issue by Pranab009** [MuntashirAkon/AppManager#239]
Please add auto permission removal features.
It automatically removed permissions from selected apps.
It shows a popup when you touch widget or home button. It works like android 10 or bouncer app.
Please.. please... please add this wonderful feature.

**Comment by MuntashirAkon** [comment]
Related issue #61

**Comment by Atrate** [comment]
I'd +1 a Bouncer-like implementation where the app's permissions are removed when it's closed/within x seconds/minutes of going to the home screen

**Comment by MuntashirAkon** [comment]
Dangerous permissions can be removed automatically using routine operations (via profile) when #267 and #61 are implemented. But remember that app manager is not an specialised app. It won't display any fancy UI that other related apps may display.

---
_It also doesn't mean that I endorse feature (because they're basically pointless): It's just that it can be done in the existing framework._
