### ISSUE TITLE
I translated strings.xml and disclaimer.xml to Japanese,please add.

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#240]
Preview:
 ・strings.xml
 https://paste.ec/paste/5JhsfU9O#C4r3GBKaxbpWn7vWe54cWf-qwpYf54RSFXo5Nv3EEP9
 ・disclaimer.xml
 https://paste.ec/paste/iZ38xoKq#BgXh5bdzoBgajpAH11sXLTqDQJxg6G63Ld0GxiNiWk6

ZIP(values-ja.zip):
https://upload.disroot.org/r/DykNanGy#e92O6FapHrE9CFPcZLNbbr+W0M1cBkg92E603dNlvxI=

**Comment by MuntashirAkon** [comment]
Do you want credits for this? In this project, the only way to give credits for translations is via commit author. If you can't use git, you can provide your email address so that I can commit for you. If you can use git, consider opening a pull request or submitting a patch. From now on, consider contributing through weblate.org.

**Comment by gnuhead-chieb** [comment]
Thank you for reply.I sent pull request.
