### ISSUE TITLE
Exodus report link

### ISSUE THREAD

**Issue by fabianski7** [MuntashirAkon/AppManager#25]
After AppManager searches the Exodus report, the [screen with the results](https://upload.vaa.red/Q4HCT#L9P34eEryqIaHmXmhq3UAEVWiPpxWDMy) is displayed but it does not show the direct link to their site. This could be added. 
For me it is useful because I can share this link with other people (which is better than taking a screenshot)

**Comment by MuntashirAkon** [comment]
> After AppManager searches the Exodus report, the [screen with the results](https://upload.vaa.red/Q4HCT#L9P34eEryqIaHmXmhq3UAEVWiPpxWDMy) is displayed but it does not show the direct link to their site.

This app doesn't rely Exodus reports, it only partially relies on its database of trackers (some of the trackers that this app supports are not even available in the Exodus database). That's why I didn't use Exodus logo, I used ClassySharkExodus' logo (whose source code is used here). This method is also far more superior than Exodus report as they're always a chance that you're using a modified version of an app containing malware/adware etc.

> For me it is useful because I can share this link with other people (which is better than taking a screenshot)

I can still provide an Exodus link though. Also, the text in the dialog is selectable. You can copy the text share it via Pastebin or similar sites.

**Comment by fabianski7** [comment]
I see. So the scan works offline, right? That's very good.

> I can still provide an Exodus link though. Also, the text in the dialog is selectable. You can copy the text share it via Pastebin or similar sites.

I prefer to send the link because anyone else can contest the results of the scan and see more details about each tracker.

**Comment by MuntashirAkon** [comment]
> So the scan works offline, right?

Yeah, I does. As said in the discription, this app doesn't connect to the internet.

> I prefer to send the link because anyone else can contest the results of the scan and see more details about each tracker.

Ok, I'll add a link to the relevant exodus link. But beware that I won't be checking

**Comment by MuntashirAkon** [comment]
It seem there's no way to provide a report link for an app which is not the latest version without connecting to the internet. So, I'll just add the latest report link.

References:
1. https://github.com/Exodus-Privacy/exodus/blob/v1/exodus/reports/urls.py
2. https://github.com/Exodus-Privacy/exodus/blob/v1/exodus/restful_api/urls.py
3. https://github.com/Exodus-Privacy/exodus/issues/48

**Comment by MuntashirAkon** [comment]
Since `DexFile` is deprecated, I might need to use Exodus API when this class is finally removed. So, although I'm closing now, I may open it later.

**Comment by MuntashirAkon** [comment]
Fixed via a086550
