### ISSUE TITLE
Rules not applied

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#269]
Hey,
removing blockers won't apply the rules for some dumb reason. Even manually it doesn't work...
I really need help here, this made the app spit out so much data into the web...
Thanks...

**Comment by UltraBlackLinux** [comment]
Hm it seems like a restart did the trick - Now I see a fat SSAID, at least AM allows to change it.
Is there a way to prevent reboots after installing an app? I was hoping, it would just work

**Comment by MuntashirAkon** [comment]
> Now I see a fat SSAID, at least AM allows to change it.
> Is there a way to prevent reboots after installing an app? I was hoping, it would just work

It uses a system-private service to set the SSAID. It uses a definite algorithm to generate this ID. So, even if you use Xposed, you may not be able to change it without an immediate restart. What AM does is change the contents of `/data/system/user/<user_id>/settings_ssaid.xml` which is used by the system as the _persistent_ storage for SSAIDs and the system loads contents from there only during the boot time. So, without an immediate restart—
1. The file may get overridden in case some other app requests an SSAID
2. The affected app is still going to use the previous SSAID (until a restart)

> Hm it seems like a restart did the trick

Yeah, this is expected because your system is still using the cached version of the app. Probably I should ask users to perform a restart after updating the app.
