### ISSUE TITLE
Scanning .apk-files onto virus/trojan/malware etc.

### ISSUE THREAD

**Issue by RAPXT** [MuntashirAkon/AppManager#276]
Additionally to the function of scanning .apk-files for tracker/logger, a function to upload the "questionable" app to e. g. virustotal or another analyzing service (ClamAV?) could maybe help, if a user is unsure if he can trust an app.

**Comment by MuntashirAkon** [comment]
ClamAV is out of the question. But VirusTotal can work. However, its public API requires an API key and is limited to [4 requests per minute](https://support.virustotal.com/hc/en-us/articles/115002100149-API) (including file upload, status checks, etc.).

**Comment by RAPXT** [comment]
Can you give a short explanation why ClamAV is not suitable?

Regarding virustotal: I can see how the "4 requests-limit" is problematic and maybe with the intended use it would even violate their terms of service.

Another alternative I've found is:
https://virusscan.jotti.org/en-US

**Comment by MuntashirAkon** [comment]
Not only ClamAV, no single AV software is suitable because of too many false positives. All they do is finding strings, signatures in the file, i.e. static scanning. While it is good for known malware, they don't provide anything for unknown malware (which is quite prevalent in current situation). My intention is to give users some insights so that they can figure things out themselves (#133). VT can be considered because it's not a single AV software, it displays results from multiple AV software which could be useful in figuring out how bad the software could be.

**Comment by RAPXT** [comment]
OK, i understand.

Your intention "to give users insight" is a good idea, though not every user of AppManager will have the skills or even toolset required, to inspect every app at that level. I'm not blaming you, it's just sad that there's no easier way for starters.

I've (and you too) described which problems there might be, in using virustotal. Maybe jotti virusscan is a viable alternative?

Else I guess the user, has every time he wants to check an app, open a webpage and upload the file. Which on a phone, I find a bit tedious and old fashioned, but if there's no better way...

**Comment by MuntashirAkon** [comment]
> Your intention "to give users insight" is a good idea, though not every user of AppManager will have the skills or even toolset required, to inspect every app at that level. I'm not blaming you, it's just sad that there's no easier way for starters.

I'm trying my best to write some good docs for that.

**Comment by gnuhead-chieb** [comment]
> VirusTotal can work.

Virustotal and similar web service is nonfree(proprietery) service.
so maybe it will get marked as NonfreeNet(Antifeature) by F-Droid.

I think it should be use ClamAV and **show warning like "It has risks of undetected and false detection"**

**Comment by MuntashirAkon** [comment]
> Virustotal and similar web service is nonfree(proprietery) service.
> so maybe it will get marked as NonfreeNet(Antifeature) by F-Droid.

No, it would only be a part of many features that AM would offer. [NonFreeNet](https://f-droid.org/en/docs/Anti-Features/#NonFreeNet) implies that the apps “promote or depend entirely on a Non-Free network service.”

> I think it should be use ClamAV and show warning like "It has risks of undetected and false detection"

The trouble with ClamAV is that most people won't be able to use it.

**Comment by MuntashirAkon** [comment]
> Maybe jotti virusscan is a viable alternative?

It doesn't have any public API (the API page links to the contact page). While it's possible to parse the website, this should be illegal. In any case, we're proceeding with VirusTotal for now.

Due to our strict networking policy, a user has to enable Internet as well as insert a VT API key in AM settings before VT can be used.

**Comment by MuntashirAkon** [comment]
Implemented in 8a8a38bb

**Comment by gnuhead-chieb** [comment]
it should require tap on scanner before uploading apk to VT.

**Comment by MuntashirAkon** [comment]
> it should require tap on scanner before uploading apk to VT.

Hmmm, a setting could be added with manual uploading enabled by default.

**Comment by MuntashirAkon** [comment]
Added in 041af90fd8eac425a182a1a0c307a942f2ed26e7
