### ISSUE TITLE
App Unpacker

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#288]
I found some obfuscated apps by packers.
Here is examples.
https://play.google.com/store/apps/details?id=com.sweettangerine.communism
https://play.google.com/store/apps/details?id=com.ais.aistudio

We cant understand these apps class and component name due to they are obfuscated.
I also found useful library to unpacking packed apps.
https://github.com/strazzere/android-unpacker
Is it able to implement it to AM?

**Comment by MuntashirAkon** [comment]
Packer detection (using Yara rules implemented in APKiD) is easy since all it does is static analysis (scanner is supposed to like that). However, unpacking stuffs require dynamic analysis which means the APK has to be running in the foreground/background and AM has to analyse the contents of its memory using root. While it's not impossible nor difficult, do you really want this to be implemented? If the app really contains any malware, running this on your device will cause troubles.

**Comment by gnuhead-chieb** [comment]
Ah it risky to running such apps in real device.How about submit apps to PC's emulator to retrive result using MobSF REST API?

**Comment by MuntashirAkon** [comment]
That would make things too much complicated for me and unnecessarily increase the app size with features most people won't use.

**Comment by gnuhead-chieb** [comment]
ok

**Comment by MuntashirAkon** [comment]
Yeah, I'll go as far as packer detection which I think is enough for users to understand the shady-ness of an app.
