### ISSUE TITLE
Add option to choose component blocking method

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#326]
AM currently only support IFW for component blocking method.
IFW is the best method for root users but it isn't works for ADB/nonroot users.
so I think it is better to make let users to choice component blocking methods(eg, pm,apk patching(after it is supported in AM)

**Comment by MuntashirAkon** [comment]
AM uses both IFW and PackageManager to block and disable components respectively (from v2.5.22) as both methods have been found to have certain weakness (#205), and both are root-only methods. The PackageManager also works for the test-only apps since Android Oreo (I might explicitly enable blocking options for them in future).

APK editing has many risks associated with it. Therefore, the implementation will be a bit different than the usual.

I wish there existed an easier way to control application components. But Google doesn't particularly like apps that prevent other apps from tracking or displaying ads as they have explicitly described in their developer program policies.
