### ISSUE TITLE
Support searching with regex

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#332]
I need regex searching in search window on apps list,components and classes

**Comment by MuntashirAkon** [comment]
Implemented in the main page via 40386118

**Comment by gnuhead-chieb** [comment]
lgtm!thanks.

**Comment by MuntashirAkon** [comment]
I am not satisfied with the current approach, which is closely related to MiXplorer. Instead the use of typical symbols might work better. This will also go well with adding more advanced features such as the use of predefined tags which will require symbol processing.

Instead of a drop-down menu, we can use something like this:

1. **Contains**: This is the default searching method
2. **Prefix**: Adding `:` before the search query
3. **Suffix**: Adding `:` after the search query
4. **Regular Expressions**: Adding `/` (conventional) or `.` (good for on-screen keyboards) before the search query.

These symbols, of course, can be escaped.

**Comment by gnuhead-chieb** [comment]
In the first place, I think the prefix and suffix options are unnecessary while these can be substituted with regex like this:
```
^prefix
suffix$
```

**Comment by MuntashirAkon** [comment]
> In the first place, I think the prefix and suffix options are unnecessary while these can be substituted with regex like this:

The issue is that in the on-screen keyboards, these symbols are not easily accessible.
