### ISSUE TITLE
App crash on blocked crashhandler

### ISSUE THREAD

**Issue by fusionneur** [MuntashirAkon/AppManager#335]
Fennec and tor browser crash on startup after i used "block
trackers" feature

I fixed apps by allowing:
mozilla.components.lib.crash.handler.CrashHandlerService

**Comment by MuntashirAkon** [comment]
I'm aware of that. Unfortunately, I have a policy of not allowing any whitelists (as it has a wider set of consequences and open for many possibilities). What I can do is add it in the FAQ section so that people might be aware of it. Alternatively, you can open similar issues in the ETIP repository or in the Mozilla issue tracker so that this issue might be fixed by them rather than AM.

**Comment by gnuhead-chieb** [comment]
Fixed

**Comment by MuntashirAkon** [comment]
Fixed in fe1529aa
