### ISSUE TITLE
Freeze/ auto freeze option to disable the app

### ISSUE THREAD

**Issue by krouter** [MuntashirAkon/AppManager#342]
**Describe the solution you'd like**
Option to tag each app with 'freeze' or 'auto freeze' in background would be ideal to disable the apps that prevent them from running in the background. Shortcut to freeze all tagged apps with one click would be sweet too. 
Shelter app has this feature. It's great.

**Comment by MuntashirAkon** [comment]
App Manager is a general purpose app. So, you have to consider the alternatives first. In this case, the alternative you're looking for is [profile](https://muntashirakon.github.io/AppManager/guide/profile-page.html).

Freeze is not an official word, popularised by Greenify. It's officially known as force-stop. You add your desired app to the list and apply force-stop. You can create shortcut of the profiles so that you can invoke them from the launcher. You can also export, shared and import the profile later on.

Auto-freeze is related to #61. Once #61 gets implemented, you would be able to create an auto-freeze profile (similar to above) and add it to the routine task setting “when an app goes to background” to true.

**Comment by NSTAdventure** [comment]
@krouter 
do you mean disable apps?
- app manager already able to disable apps no root

do you mean force stop?
-app manager also can force stop the apps

**Comment by MuntashirAkon** [comment]
Implemented via #841
