### ISSUE TITLE
Make a custom PackageInstaller, that would allow installing mismatch signature

### ISSUE THREAD

**Issue by Cyberavater** [MuntashirAkon/AppManager#346]
This should be helpful for users who don't want to disable signature verification but want to keep the data after installation.

**Comment by Cyberavater** [comment]
As the dev said here (https://github.com/MuntashirAkon/AppManager/issues/340#issuecomment-810854182), this would be an obsolete feature to have since with own custom build package installer, one can achieve a better result than this Backup/Restore method (as it will take up unnecessary space and certainly won't work for apps that high Keystore protection). But with a custom package installer, we can simply allow the mismatch signature installation over the current one, rather than uninstalling it first.

**Comment by MuntashirAkon** [comment]
> this would be an obsolete feature to have since with own custom build package installer

It says PackageManager not PackageInstaller. Both are different things. Android PackageManager only parses the package, it doesn't install them. They are handled by the PackageInstaller which is a separate class.

**Comment by Cyberavater** [comment]
> They are handled by the PackageInstaller which is a separate class.

So, is it possible to make a custom PackageInstaller, that would allow installing mismatch signature?

**Comment by MuntashirAkon** [comment]
> So, is it possible to make a custom PackageInstaller, that would allow installing mismatch signature?

Yes, it is.

**Comment by Cyberavater** [comment]
Title changed for obvious reasons.

**Comment by MuntashirAkon** [comment]
I cannot work on this feature for several reasons:
1. It requires a lot of work, especially with the newer versions of Android. I cannot spend time on things that only a handful of people may use that does not include myself (and even then, not in a regular basis).
2. It breaks Android security paradigm. Therefore, offering such a feature is contrary to App Manager's objectives. (Yes, we take privacy even more seriously but this does not seem to fall into this domain according to my analysis.)
3. Since it exclusively promotes _hacking_ (or cracking), App Manager could be at the risk of being marked as a hacking tool, therefore, flagged by scanning services such as Google Play Protect or even VirusTotal.

There are already some tools capable of patching the Android framework in order to bypass APK signature pinning, and although we do not recommend them due to the point no. 2 above, it's completely up to the user to decide what to do with them.
