### ISSUE TITLE
Backup badge & deeper compression

### ISSUE THREAD

**Issue by Alifaisal404** [MuntashirAkon/AppManager#353]
Please add an option (as default, I wish) to backup split apps with **deeper compression** as in LuckyPatcher. If you think this may corrupt the app, you can add a warning.

![LP vs AM](https://user-images.githubusercontent.com/77747524/113476947-904adb80-9433-11eb-9ef6-f2d170bf6bfe.jpg)

**Comment by MuntashirAkon** [comment]
> 1.Add badge/star or some sort of symbol that shows app is backed up.

You mean for the **back up APK** option in the batch operations? This option will be renamed to **export APK** because this is what it does and AM doesn't keep track of them. It's the users job to keep track of them. For back up/restore, use the **back up/restore** option with only **source** and **APK only** selected.

**Comment by Alifaisal404** [comment]
> > 1.Add badge/star or some sort of symbol that shows app is backed up.
> 
> You mean for the **back up APK** option in the batch operations? This option will be renamed to **export APK** because this is what it does and AM doesn't keep track of them. It's the users job to keep track of them. For back up/restore, use the **back up/restore** option with only **source** and **APK only** selected.

Thanks, I have updated the issue,

**Comment by MuntashirAkon** [comment]
Fixed in 84ae21c5
