### ISSUE TITLE
Move to a better place!

### ISSUE THREAD

**Issue by soheilkhanalipur** [MuntashirAkon/AppManager#436]
Unfortunately, I have to say that you have put this program in a bad place! GitHub!
This app deserves places like: Codeberg, Gitea, GitLab (Instances), and wherever better…
GitHub boycotts users, removes apps, and actually says "Whatever I want is going to be saved and whatever I don't need Is going to be deleted." The app has not paid attention to users' requests for RTL support for years, and says this is not a priority!
Free software should be free somewhere, which GitHub does not have!
Aren't these enough to leave GitHub?

**Comment by MuntashirAkon** [comment]
> This app deserves places like: Codeberg, Gitea, GitLab (Instances), and wherever better…

We have Codeberg, GitLab and Riseup mirrors from the very beginning. See the relevant README section.

App Manager is an open-source project. It can be hosted anywhere and everywhere, but GitHub has its benefits.
- Collaboration is much easier and less confusing than Gitea or GitLab. In fact, some developers I know have left Gitea for Codeberg due to their overly complicated UI.
- People tend to collaborate more if a project is available on GitHub than on the said websites
- Search engines prioritise GitHub website (although App Manager is a new app and there are already many popular app that bears this name, you'll find App Manager within the first page in a Google search)
- GitHub has its own easy-to-use CI, unlike most other websites (except the official GitLab)
