### ISSUE TITLE
Question about disabling an app's broadcast receiver

### ISSUE THREAD

**Issue by garywill** [MuntashirAkon/AppManager#438]
Hi developer thank you for this amazing toolbox.

I'm trying to stop some apps from auto-starting after boot.

From some Autostarts posts I read that AppManager used some code from Autostarts.

Autostarts can only disable an app's component, so when we disable a receiver, some other receivers also get disabled. Even worth, some users reported some other app's receiver linked got disabled. ( Why no popup comfirmation or warning for that? )

Does App Manager's "RECEIVERS" tab act like Autostarts?

If so, could you pop a dialog to tell what is linked and let user comfirm

Additionally, what's the meaning of background color orange/red/pink on a receiver/service item?

**Comment by MuntashirAkon** [comment]
> From some Autostarts posts I read that AppManager used some code from Autostarts.
> Does App Manager's "RECEIVERS" tab act like Autostarts?

We haven't added any Autostarts-like feature until now. You can subscribe to #101 for updates regarding this.

> Autostarts can only disable an app's component, so when we disable a receiver, some other receivers also get disabled. Even worth, some users reported some other app's receiver linked got disabled. ( Why no popup comfirmation or warning for that? )

This is an UI issue, I think. The other receivers never gets blocked. Unfortunately, the project uses a lot of deprecated materials which cannot be fixed without changing the entire UI design which, again, I can't do because it's very time consuming. I revamped the project for the existing Autostarts fanbase. I do not wish to provide further support than that since the original developer has no intention to support the project other than accepting pull requests from others.

> Additionally, what's the meaning of background color orange/red/pink on a receiver/service item?

See docs: https://muntashirakon.github.io/AppManager/en/#x1-350002.2.1
