### ISSUE TITLE
App-specific log viewer

### ISSUE THREAD

**Issue by opusforlife2** [MuntashirAkon/AppManager#446]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [ ] I have read the docs

**Is your feature request related to a problem? Please describe.**

Just the minor inconvenience of having to filter out the logcat with an app's package name.

**Describe the solution you'd like**

I'd like a Log Viewer button in an app's details screen, which directly takes you to a filtered logcat of that app.

**Comment by MuntashirAkon** [comment]
> Just the minor inconvenience of having to filter out the logcat with an app's package name.

You can't filter logs by package name, only by process ID (PID). So, the option to view logs are displayed only if the app is currently running. You can view logs filtered by process ID from both the running apps page (click on the 3-dots menu on the right side of the desired process or app) and the app info tab of the app details page (click on the `running` tag if it's available, you'll see the log viewer option).

**Comment by MuntashirAkon** [comment]
See #34 for details.

**Comment by opusforlife2** [comment]
Oh. So is there no programmatic equivalent of going into the Log Viewer and typing the package name? That is a broader selection, because in addition to the app's own logs, it includes logs of other processes related to the app being observed.

**Comment by MuntashirAkon** [comment]
> So is there no programmatic equivalent of going into the Log Viewer and typing the package name?

Correct. Android doesn't provide such options.

**Comment by MuntashirAkon** [comment]
> So is there no programmatic equivalent of going into the Log Viewer and typing the package name?

Correct. Android doesn't provide such options.

**Comment by MPeti1** [comment]
Isn't it possible with starting the log viewer activity with a paramter? So you send an intent with an extra, which will be the value of the initial filter, and the activity checks for it and sets the filter in onCreate

**Comment by MuntashirAkon** [comment]
> Isn't it possible with starting the log viewer activity with a paramter?

PID-specific log viewers are already loaded with a PID parameter.

**Comment by MPeti1** [comment]
Sorry, I meant opening it with a package name, not a pid

**Comment by MuntashirAkon** [comment]
> Sorry, I meant opening it with a package name, not a pid

Android doesn't provide any option to filter by package name.

**Comment by MPeti1** [comment]
But what I (and I assume opusforlife2 too) wanted to mean is that on opening the log viewer for a specific app, the filter on the top could be autofilled with the package name of the app for which I opened the log viewer.
In this case PID filtering would probably already filter out useful logs, so that could be made optional.

The use case here is to see logs that were made while the app in question interacted with other apps or the system: an example for this use case is to find the reason why the installation of the app failed. The package installer activity of the system does not tell you what went wrong, but the problem is usually logged with the PackageInstaller tag, sometimes also mentioning the package name of the installer.

**Comment by MuntashirAkon** [comment]
That's different from “app-specific log viewer”. For instance, if you filter the logs generated by App Manager using its package name, it would filter out many important logs, specially the debug logs. This is specifically true for code-optimised as well as obfuscated apps. It does have limits for apps that runs on multiple processes, which can be fixed by adding the ability to filter by multiple PIDs.

Therefore, I think we can add a separate menu entry for this “filter” option in the app info tab without modifying the existing “app-specific log viewer”.
