### ISSUE TITLE
[Discussion] References and other similar projects

### ISSUE THREAD

**Issue by mubashir-rehman** [MuntashirAkon/AppManager#469]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant

**Describe the solution you'd like**
Use this issue or discussion thread for referencing other sources and projects that can be checked to implement similar features in AM

**Additional context**
I want came across https://github.com/SecTheTech/AMDH while searching for a forensic tool for thumbnail.db and imagecache file extraction.
Thought it might be useful to reference it here.
References from such a thread can later be used to solve other issues.
Also, it can serve as a primary source for Awsome curated list repo in future(if someone wants to create another one).

**Comment by MuntashirAkon** [comment]
The issue with discussion threads are that they can be really long (like chats) and GitHub is very bad at handling large conversations. So, what people generally do is create a new issue for each sources they think AM should have. I also support it because it's easy to keep track of them, and implement the features in a modular way.

You can already find a few issues referencing other apps. So, sticking to this convention should be better for all of us.

> I want came across https://github.com/SecTheTech/AMDH while searching for a forensic tool for thumbnail.db and imagecache file extraction.

It's seems to be a nice project. The good thing is they've listed all the suspected permissions in one-place which is hard to find. I'm already working on integrating Yara which is used to detect Android packers via the APKiD project (#277 & #133). We can also include permissions with it.

**Comment by mubashir-rehman** [comment]
Noted and thanks for the review.
