### ISSUE TITLE
Can not install on System/app or System/priv-app

### ISSUE THREAD

**Issue by Mitezuss** [MuntashirAkon/AppManager#477]
**To Reproduce**

Try install on System/app or System/priv-app (with permissions)

**Expected behavior**

Wanna install on System from TWRP

**Device info**
 - OS Version:  Android 9
 - App Manager Version: 2.6.1
 - Mode: root

**Comment by MuntashirAkon** [comment]
You mean **App Manager**? There's no point in installing App Manager as a system app because it doesn't declare all the necessary permissions. Even if it did add all the permissions, it would also require permission whitelisting since most system permissions are signature permissions i.e. only granted to apps having the same signature as the `android` package or having `1000` user ID.
