### ISSUE TITLE
Disallow disabling the app "App Manager" by itself

### ISSUE THREAD

**Issue by Catfriend1** [MuntashirAkon/AppManager#519]
- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

**Is your feature request related to a problem? Please describe.**
I've accidentially hit the disable button in app manager's "app settings of itself" by accident. I use App Manager to regularly disable apps I don't need very often, like Connect Bot or Alexa . Then, I was stuck unable to re-enable App Manager without adb from a computer. I wasn't home, so I did F-Droid update the app which re enabled it as a side effect.

**Comment by Atrate** [comment]
Either that or a really big and visible warning should be shown when performing potentially destructive operations on AM

**Comment by MuntashirAkon** [comment]
> Either that or a really big and visible warning should be shown when performing potentially destructive operations on AM

It already does that in most places such as in batch operations, 1-click operations. However, disabling an app via the app info tab isn't considered dangerous because it isn't actually a destructive operation (unless you're disabling App Manager itself), as it is a reversible operation. And if it's a UID < 10,000 app, disabling it isn't going to prevent it from running.

**Comment by Catfriend1** [comment]
I think the warning dialog isn't required for any other app except app manager itself.

**Comment by MuntashirAkon** [comment]
Fixed in 70416296.

**Comment by Catfriend1** [comment]
Thanks

**Comment by planetloli** [comment]
please delete issue
