### ISSUE TITLE
Blank running apps when refresh it quickly few times.

### ISSUE THREAD

**Issue by d4rkk3y** [MuntashirAkon/AppManager#528]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
The Running Apps list become blank when pull down to refresh it quickly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start AM
2. Three dot option->Running Apps
3. Pull down continuously to refresh it quickly
4. List running apps will become blank

**Expected behavior**
List running apps display normally.

**Screenshots**

**Crash logs**
[am_log.txt](https://github.com/MuntashirAkon/AppManager/files/6871148/am_log.txt)

**Device info**
 - Device: Black Shark 3
 - OS Version: Android 11
 - App Manager Version: v2.7.0-DEBUG#1430
 - Mode: `adb`

**Additional context**

**Comment by d4rkk3y** [comment]
#476

**Comment by MuntashirAkon** [comment]
This issue is present ever since Toybox was removed. So far I haven't found a fix without increasing the load time. A possible solution is to use ParceledListSlice like it is used in Android framework. But it's a work in progress (see the [corresponding branch](https://github.com/MuntashirAkon/AppManager/tree/parceled-list-slice)).

**Comment by MuntashirAkon** [comment]
Fixed via e4c151fe and 3fc71d28. You have to restart your device after updating to the latest debug build in order to see the changes.
