### ISSUE TITLE
one click disable Component cant open all apps

### ISSUE THREAD

**Issue by sjnhnp** [MuntashirAkon/AppManager#551]
Accidentally pressed one click to disable the apps component, now the apps can not open, and reinstalled app manager also can not open it

save me

**Comment by MuntashirAkon** [comment]
You haven't stated what you did exactly in order to have this situation. We can't help if we don't know what you did _exactly_.

**Comment by sjnhnp** [comment]
my English is poor can i in Chinese？

**Comment by MuntashirAkon** [comment]
> my English is poor can i in Chinese？

No problem. I can use translators.

**Comment by sjnhnp** [comment]
1.我使用了一键功能里面的：屏蔽跟踪器，禁用组件，都是默认勾选显示出来的apps
然后我就打不开所有app了，
- 微信点击没反应，Firefox跳出关闭应用错误，telegram和其他和很多apps直接跳出应用信息界面。

然后我重装了app manager，但是app manager 点击都没反应打不开

**Comment by MuntashirAkon** [comment]
> I used the one-click function inside: block tracker, disable components, all are checked by default to show the apps

Ah, I see. **Block tracker...** hardly does any damages. Did you click on the search button of the **disable components...** without putting anything in the input field? If you do not put anything there, it would list and block all the components from the user apps (I suppose you didn't click on the “apply to system apps”, did you?)!

Here's a solution for you:
1. Navigate to `/data/system/ifw/` and find `io.github.muntashirakon.AppManager.xml` or `io.github.muntashirakon.AppManager.debug.xml` (depending on what you've used). If you cannot access a Terminal app (since you've disabled every components), you can run the following from recovery/adb (the latter with root):
    ```sh
    rm /data/system/ifw/io.github.muntashirakon.AppManager.xml
    ```
    or,
    ```sh
    rm /data/system/ifw/io.github.muntashirakon.AppManager.debug.xml
    ```
2. If you cannot open Magisk, you'd also have to do the same for Magisk (file path: `/data/system/ifw/com.topjohnwu.magisk.xml`)
3. After that reinstall and open App Manager (and Magisk too if no.2 applies), grant root permission. Then, navigate to **Settings** > **Rules** > **Import/export blocking rules** and select **Import existing rules**. It will list some apps with disabled components. If that's the case, click **select all** and **apply**.
4. Navigate back to the settings by pressing **cancel**. Finally, press **Remove all rules** located immediately below **import/export blocking rules**. You've to confirm by selecting **yes**.

After that App Manager will be loading for some time and when finished, you should be able to get back to your apps without reinstalling them.

**Comment by sjnhnp** [comment]
thx very much

success

**Comment by sjnhnp** [comment]
但是每一次打开app，都是先出现该app的应用信息，

再从应用信息点击：打开，才能真正打开app

**Comment by MuntashirAkon** [comment]
I didn't get it. Which app did you mean? App Manager or any app? Could you share some screenshots or something similar in order to clarify your meaning?
