### ISSUE TITLE
App locker

### ISSUE THREAD

**Issue by the-anonymous-raven** [MuntashirAkon/AppManager#552]
Is an app locker feasible to be implemented with the app manager? 
It kinda fits for an app manager to have  locking capability. 
With the 'Usage permission' already there, it would not require any more permissions too.

There doesn't exist any FOSS apps for the same purpose.

Thanks.

**Comment by MuntashirAkon** [comment]
> With the 'Usage permission' already there, it would not require any more permissions too.

As far as I know, it also needs certain accessibility permissions in order to control other apps. It also means that an app watcher is necessary i.e. a constant foreground service to watch out for the configured apps. Since apps aren't allowed to start by themselves, additional permissions such as **draw over other apps** is also required.

> Is an app locker feasible to be implemented with the app manager?

I've got no plans to implement such as feature because I already have screen lock enabled and all my private apps (App Manager, Signal, Telegram) offer password protection.

**Comment by the-anonymous-raven** [comment]
> As far as I know, it also needs certain accessibility permissions in order to control other apps. It also means that an app watcher is necessary i.e. a constant foreground service to watch out for the configured apps. Since apps aren't allowed to start by themselves, additional permissions such as **draw over other apps** is also required.
I used a non-FOSS app recently which provided the same with only Usage Access permission, hence I commented the same.

> I've got no plans to implement such as feature because I already have screen lock enabled and all my private apps (App Manager, Signal, Telegram) offer password protection.
No issues.

**Comment by MuntashirAkon** [comment]
> I used a non-FOSS app recently which provided the feature with only Usage Access permission, hence I commented the same.

Accessibility permissions are located in the respective component names, not in the uses permissions section.

**Comment by gnuhead-chieb** [comment]
https://github.com/iammert/AppLocker
https://github.com/SubhamTyagi/AppLock

but these are childish trick.
you can bypass them by booting in safemode.

**Comment by MuntashirAkon** [comment]
The only way to effectively implement a locker for the apps is to have a built-in option to do so. If there's no such support, maybe a virtual environment might be used. However, with a few tricks, you can achieve an app locker better than the others (but still not _effective_) but _with no background activity_:

With v3.1.0, you can add shortcuts for freezing an app. If you enabled app locking in App Manager, you could in effect achieve something like an app locker since whenever you'd want to unfreeze an app, a prompt shall be displayed where you have to enter the pin number. The drawbacks are that the app cannot work in the background, requires ADB/root, can be bypassed via ADB or using root. Also, you'd have to change the default method to suspend/hide instead of disable.
