### ISSUE TITLE
[Block Trackers] auto re-applied on phone reboot?

### ISSUE THREAD

**Issue by bitpixl** [MuntashirAkon/AppManager#588]
I've been using the [1-Click Ops] [Block/unblock trackers] feature for a while now and I always redo the 'block trackers' when I've updated any of my apps or have restarted my phone. I figure it's best practice to redo the 'block trackers' on any app update, as you never know if an app update has introduced more/new trackers.

But does AppManager automatically apply the existing tracking blocks when I've restarted my phone?

Thank you for your answer in advance.

**Comment by MuntashirAkon** [comment]
> But does AppManager automatically apply the existing tracking blocks when I've restarted my phone?

No. Recurrent tasks are a part of #61.

> I figure it's best practice to redo the 'block trackers' on any app update, as you never know if an app update has introduced more/new trackers.

At present, if you update an app using AM (as of v2.6.4) and block trackers is enabled in Settings > Installer, the trackers are blocked after completing the installation. AM cannot do that if you update the app with other installers (e.g. native installers, google play, Aurora Store, etc.) because of Android's limitations.
