### ISSUE TITLE
[Hacktoberfest] implement adb shell pm uninstall 

### ISSUE THREAD

**Issue by kurt-by** [MuntashirAkon/AppManager#594]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [ ] I have read the docs

**Is your feature request related to a problem? Please describe.**
Im a big fan of [SCRIPT] Universal Android Debloater
https://forum.xda-developers.com/android/software-hacking/script-universal-android-debloater-t4069209/post82054575
I tried the same with app manager, but the apps were just deactivated. 

**Describe the solution you'd like**
I want a feature in app manager that sets apps into a state like with adb shell pm uninstall -k --user 0 <app>

**Describe alternatives you've considered**
Not use app manager, stay with debloater script.

**Additional Information**
Debloater script has some well documented app lists. Maybe it's worth merging.

**Comment by MuntashirAkon** [comment]
Uninstalling apps doesn't work well with **profiles** which is why **disable** is selected instead of uninstall.

However, there is an alternative. Here are the steps in details:
1. Create a profile with one of the presets and save it
2. Navigate back to the main page
3. Click on the three-dots menu on the top-right corner and select **List Options**
4. Scroll down and in the **profiles** section under **filter**, select the profile you saved in step 1 and close the dialog box
5. Now select any item in the app list and then click **select all** at the bottom
6. Click on the three-dots menu on the bottom-right corner and select uninstall to uninstall all the selected apps.

**Comment by MuntashirAkon** [comment]
> Debloater script has some well documented app lists. Maybe it's worth merging.

We already use app lists from UAD (and other scripts).

**Comment by kurt-by** [comment]
Thank you @MuntashirAkon . It worked for all in google profile, but chrome. 
Wouldn't it be a good idea to have a profile option to uninstall with disable as fallback?
How about deleting updates from data partition?

**Comment by MuntashirAkon** [comment]
> Wouldn't it be a good idea to have a profile option to uninstall with disable as fallback?

Sorry, I didn't understand what you're trying to say here. However, profiles are meant for recurring task which is why they have two states: **on** and **off**.

One thing that could be done is to add the preset filters in the **List options** dialog in the main page which can be used to filter out the apps so that you can perform batch operations on them.

> How about deleting updates from data partition?

Hmmm, this is a good point. I have to think about it.
