### ISSUE TITLE
Can you document "Net policy"?

### ISSUE THREAD

**Issue by 2011** [MuntashirAkon/AppManager#622]
**Describe the existing feature/documentation**

Just looked through the documentaiton pages, and I did not see it explained.

**Describe your problem(s)**

I mostly wonder if I can use it to deny internet access to some apps (something no doubt frequently desired, but not made easy by the Android developers).

**Comment by MuntashirAkon** [comment]
Here's a draft version (will be added once the #418 has been merged).

----

## Net Policy

Short for **Network policy** or network policies, usually located in Android settings under **Mobile data & Wifi** section in the app info page of an app. Not all policies are guaranteed to be included in this setting page (e.g. Samsung) and not all settings are well-understood due to lack of documentation. App Manager can display all the net policies as declared in the [NetworkPolicyManager](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/net/NetworkPolicyManager.java). Policies unknown to App Manager will have a _Unknown_ prefix along with the policy constant name and number in the hexadecimal format.

Net policy allows a user to configure certain networking behaviour of an app without modifying ip tables directly and/or running a firewall app. However, what features does it offer largely depend on Android version and ROM. A list of known net policies are listed below:

1. **None** or `POLICY_NONE`: (AOSP) No specific network policy is set. System can still assign rules depending on the nature of the app.
2. **Reject background data** or `POLICY_REJECT_METERED_BACKGROUND`: (AOSP) Reject network usage on metered networks when application in background.
3. **Allow background data when Data Saver is on** or `POLICY_ALLOW_METERED_BACKGROUND`: (AOSP) Allow metered network use in the background even when in data usage save mode.
4. **Reject cellular data** or `POLICY_REJECT_CELLULAR` (Android 11+) or `POLICY_REJECT_ON_DATA` (up to Android 10): (Lineage OS) Reject mobile/cellular data. Signals network unavailable to the configured app as if the mobile data is inactive.
5. **Reject VPN data** or `POLICY_REJECT_VPN` (Android 11+) or `POLICY_REJECT_ON_VPN` (up to Android 10): (Lineage OS) Reject VPN data. Signals network unavailable to the configured app as if the VPN is inactive.
6. **Reject Wi-Fi data** or `POLICY_REJECT_WIFI` (Android 11+) or `POLICY_REJECT_ON_WLAN` (up to Android 10): (Lineage OS) Reject Wi-Fi data. Signals network unavailable to the configured app as if the device is not connected to a Wi-Fi network.
7. **Disable network access** or `POLICY_REJECT_ALL` (Android 11+) or `POLICY_NETWORK_ISOLATED` (up to Android 10): (Lineage OS) Reject network access in all circumstances. This is not the same as enforcing the other three policies above, and is the recommended policy for dodgy apps. If this policy is enforced, there is no need to enforce the other policies.
8. `POLICY_ALLOW_METERED_IN_ROAMING`: (Samsung) Possibly allow metered network use during roaming. Exact meaning is currently unknown.
9. `POLICY_ALLOW_WHITELIST_IN_ROAMING`: (Samsung) Possibly allow network use during roaming. Exact meaning is currently unknown.

**Note.** Corresponding Lineage OS patches are as follows:
1. https://github.com/LineageOS/android_frameworks_base/commit/a04932bafbbf7d99efd18276152cc2c9c9b2073e
2. https://github.com/LineageOS/android_frameworks_base/commit/02c8c82854348f52afe2199f310f44b5f578b5b8

**Comment by MuntashirAkon** [comment]
Added in 9ec06b78
