### ISSUE TITLE
Some Permissions and App Ops Revert Back

### ISSUE THREAD

**Issue by 2011** [MuntashirAkon/AppManager#623]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

Can't get changes to (some) App Opps to persist.

**To Reproduce**

1a. Go to App Opps tab in an app. Disable (particularly interested in these) 63 RUN_IN_BACKGROUND and 48 WRITE_WALLPAPER. Refresh and note that both permissions jump back to enabled.

1b. With the package list displayed, go to "1-Click Ops", and  select "Set mode for app opps...". Enter 63 in the "Input app ops" field and "allow" in the "Mode" field. List of apps appears. Uncheck apps that should not run in background. Apply. App pages still display permission as enabled.

**Expected behavior**

Would like a permission to stay off when I turn it off. :)

**Device info**
 - Device: multiple (will mention two Samsung Galaxy Tab 2 and Teclast T20).
 - OS Version: Android 6, 7, and 10
 - App Manager Version: [2.6.4]
 - Mode: root

**Additional context**

The filtering search of "Set mode for app ops..." seems completely random. Some apps appear in both Mode Allow and Mode Ignore, and some of those appear with the check box selected when filtered by Allow, yet unselected when filtered by Ignore.

**Comment by MuntashirAkon** [comment]
What happens when you enable/disable these app ops after you click “reset to default” in the app ops tab?

**Comment by 2011** [comment]
Now on 2.6.5.1. Looks like the denied permissions stick now. :) Thank you. Still a problem with the search, though. If I go to "1-Click Ops" / "Set mode for app ops..." and then search on (again) 63, modes allow, deny, or default will return a list of all apps (they appear under each of those modes), while setting the mode to ignore returns no apps (which looks correct).

**Comment by MuntashirAkon** [comment]
> Now on 2.6.5.1. Looks like the denied permissions stick now. :) Thank you. Still a problem with the search, though. If I go to "1-Click Ops" / "Set mode for app ops..." and then search on (again) 63, modes allow, deny, or default will return a list of all apps (they appear under each of those modes), while setting the mode to ignore returns no apps (which looks correct).

There is still a possibility of going things wrong because app ops/permissions aren't well-tested in the AOSP and certainly not generalised like it was done on App Manager (i.e. the tests are only done for specific permissions and/or app ops). As a result, most other apps which support this feature usually deal with specific app ops or permissions instead of all of them. So, if something goes wrong, you may have to reset them from time to time (or they might be reset by themselves). As a result, my suggestion would be to create a profile in App Manager for the rouge apps and control app ops from there.

**Comment by MuntashirAkon** [comment]
I've tried to fix the issues as much as possible (0b571a38, 6c7a89af, d96e9cd0). It's now up to you to check and verify the changes. However, keep in mind that,
1. App ops often gets reverted by the Android system due to various events such as force-stopping the app. App Manager doesn't offer any guards against them right now.
2. Not all app ops support all the modes. Depending on the Android version that you're running, certain mode for certain app op will be reverted by the system.
3. Location permissions/app ops can be problematic because these permissions seem to be handled in a special manner. This issue will be fixed in future.
