### ISSUE TITLE
please update weblate strings

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#647]
latest strings cannot translate on weblate for now.

**Comment by MuntashirAkon** [comment]
I'm very busy this week. I'll try on Monday.

**Comment by MuntashirAkon** [comment]
ac2af6f6

**Comment by gnuhead-chieb** [comment]
not automatically update?

**Comment by MuntashirAkon** [comment]
> not automatically update?

Yes, automatic update was disabled last year because the frequent updates disrupts linearity of the master branch as well as debug build watchers see a lot of useless debug builds.

You do not have to remind me about it every time it diverges. I am well aware of it (and Weblate also sends me messages when it detects it). I shall update the strings when I feel it necessary.
