### ISSUE TITLE
How to use Android 11+ adb over WiFi?

### ISSUE THREAD

**Issue by Mosney** [MuntashirAkon/AppManager#659]
How to pair? I believe Android 11+ must pair before adb connect. I didn't find info in docs, only a old adb over TCP, on port 5555, but it requires cable adb connect before enable it.

**Comment by MuntashirAkon** [comment]
The procedure is similar to Shizuku's: https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging

But for App Manager, you've to select “Wireless debugging” in **Settings** > **Mode of operation**.

**Comment by Mosney** [comment]
But the question is how to pair? Select wireless debugging then press "apply" only popup text box to input "port number below device name", it's not work if don't pair at the beginning. I tried fill port number directly but next is "Fallback to no-root mode?"

**Comment by MuntashirAkon** [comment]
> But the question is how to pair?

I know that it is a bit verbose right now. Since it is a new feature it will take some time to make it for user-friendly. Anyway, here's how you can pair right now:

1. Open App Manager, go to settings to enable **Wireless Debugging**.
2. Choose **pair** in the subsequent dialog box.
3. Open **Developer settings** in Android Settings, click on **Wireless Debugging** and in the subsequent window, turn it on.
4. Go to Android recents page and click on the App Manager or Setting icon (whatever is on top) and in the context menu, click on **Split screen**. At this point, depending on your configuration, App Manager will be shown at the top and Settings at the bottom.
5. Now in the wireless debugging page, click on **Pair device with pairing code**. At this, a new dialog will be displayed, note down the pairing code and port number and DO NOT close the window yet.
6. In the App Manager's pairing dialog, put the pairing code and port number, and click pair.

**Comment by Mosney** [comment]
> I know that it is a bit verbose right now. Since this is a new feature it will take some time to make it user-friendly. Anyway, here's how you can pair right now:

I knew how to pair, identical to the old version of Shizuku, but anyway, thanks for your patience to explain, I believe this will be helpful to those who come after.
But on my side it's different than your said, only port dialog box to input after I choose **wireless debugging** then click **apply** button, no **pair** can be choose, and then, no matter input pair port or adb port, all failed to **Fallback to non-root mode**, see screenshot below. And I checked my app version is the latest 2.6.5.1(397) download from Github release.

![image](https://user-images.githubusercontent.com/22477230/151706782-5edc485a-e2a9-44e1-9138-ae164dde8f0f.png)

**Comment by MuntashirAkon** [comment]
Ah, you've failed to mention that you were using the latest stable build. I thought you were one of the debug build users. I would suggest you to pay attention to the changelogs because AM usually changes a lot between two releases and failing to read the changelogs would mean that you will miss out a lot of features.

This is from the changelogs of v2.6.1:

> In order to use wireless debugging, first enable ADB over TCP as usual and select **Always allow from this computer**. When Ap Manager is working on this mode, enable wireless debugging, and then, go to App Manager settings and change **Mode of Operations** to _Wireless Debugging_. At this point, App Manager should display a prompt where the port number from the wireless debugging window should inserted. With this mode enabled, App Manager will display this prompt every time it requires the port number. As always, remember to disable wireless debugging once App Managers initialisation screen goes aways. Unless you're using MIUI, you won't need to enable wireless debugging until the next reboot.

As to why adb pairing was not available right away in the mainline, see my comment at https://github.com/tananaev/adblib/issues/14#issuecomment-895053996.

ADB pairing will be introduced in App Manager v3.0.0 scheduled to be released in April.

**Comment by Mosney** [comment]
Okay, thanks for your help! I can't find debug build apk file, do I need compile myself? I don't know about this, maybe I should wait v3.0.0 release.

**Comment by MuntashirAkon** [comment]
You can also download from GitHub actions e.g. https://github.com/MuntashirAkon/AppManager/actions/runs/1768859093.

The files are actually uploaded from GitHub actions to the Telegram channel.

**Comment by Mosney** [comment]
> You can also download from GitHub actions e.g. https://github.com/MuntashirAkon/AppManager/actions/runs/1768859093.

Wow! I didn't know that, I used to go release page find some pre-release tag build, Thanks!

**Comment by MuntashirAkon** [comment]
> Wow! I didn't know that, I used to go release page find some pre-release tag build, Thanks!

Pre-releases have been discontinued recently in favour of debug builds (#480). Most people just go to the debug channel and install the latest build when they are free.

**Comment by Werve** [comment]
Hello, with the v3.0.0-rc01 version found on the release page here and the procedure described in the previous comments I was able to pair but when I do connect it still says "Debug wireless (Inferred mode: No root)" and the options in the "1-Click operations" menu indicate that adb or root is required to work so I guess it didn't connect correctly for using adb.

**Comment by MuntashirAkon** [comment]
**FYI:** I've already written an official guide on this topic in the docs: https://muntashirakon.github.io/AppManager/#sec:wireless-debugging
