### ISSUE TITLE
DISCLAIMER Timer

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#670]
(_I don't think it comes under Feature request or Help wanted template but creating this issue under HW_)

Current "DISCLAIMER" screen 👇🏿
![Screenshot_2022-02-05-11-36-31](https://user-images.githubusercontent.com/48226312/152631368-b56b676d-ab71-482b-baca-0a1e92590968.jpeg)

Usually we never read such disclaimer, we just click yes/ok/agree/accept. Though AM  is extra cautious about it by showing a "Never show this again" check box.

IMO it would be nice add a timer to current "I agree" button.
Ppl now just can't "_mark the checkbox-click I agree_" & open AM quickly.
We make sure users read the Disclaimer by adding one more steps. (_though 5sec is not enough to read full disclaimer it prevents users to skip AM's current 2 steps subconsciously/auto-mode_)

https://user-images.githubusercontent.com/48226312/152632132-993fdd9f-96a2-4f26-97eb-8075fe6c1ac6.mp4

source: [SecondScreen](https://github.com/farmerbb/SecondScreen) app

ThankYou🙏🏿

**Comment by MuntashirAkon** [comment]
The purpose of the statement is to _remind_ the users that they cannot blame us for anything they do in App Manager, and the checkbox is there to prevent any accidental clicks. Hence, when you click on “I agree”, you are simply assuring that you've understood the statement. **This disclaimer is not a legal statement** because it's already been covered by the GPL-3.0-or-later license (no liabilities, responsibilities or warranties of any kind), and I do not have the power to weaken it in any ways. I hope you have understood it now.
