### ISSUE TITLE
Using app ops / Permission access notification/prompt

### ISSUE THREAD

**Issue by Raif1** [MuntashirAkon/AppManager#721]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
1.
AppManager will send me a notification which will let me know an app is using a permission or an app ops. The user will choose what permission/app ops is needed to be used to see this notification. Notification example 

1. Whatsapp is trying to access clipboard. Ignored 

2. Material files is using storage 

3.Calculator is trying to access camera. Denyed 

You can change the notification templates. Above are just an example 

The user should be able to change for how long the prompt will be shown.
Like 5 seconds 

2.Related feature

Since the app has full storage access, add an option to see prompt/notification when a folder/file has been created / deleted modified by whom. And add a log system, which will log everything folder creation /folder deletation ,time by whom.

**Describe alternatives you've considered**
AppOps by rikka. Storage isolation by rikka.

**Comment by MuntashirAkon** [comment]
This feature is a very complicated one, partly because monitoring app ops and permissions (in old versions of Android) consumes a lot of energy and probably something only the operating system should do. (Besides, any sane custom ROM would warn you if the camera or recorder is being used). Not to mention the fact that you may receive such notification over a minute after it actually happened (#143 is better in this sense) due to a huge number of iterations. So, in my opinion, it does not worth a try. (Since I will be able to manage a very small amount of time for the project in the coming days, I believe I should only focus on features that are essential.)

> Since the app has full storage access, add an option to see prompt/notification when a folder/file has been created / deleted modified by whom. And add a log system, which will log everything folder creation /folder deletation ,time by whom.

Not possible. See #131 (the author of **Storage Isolation** themselves have replied why this is a very difficult and a bit far-fetched task). _Unfortunately, there's a limit on what a single person can do with a limited amount of resources._

**Comment by Raif1** [comment]
>Not to mention the fact that you may receive such notification over a minute after it actually happened (#143 is better in this sense) due to a huge number of iteration
>
I meant the user will choose which notification they want to get bombarded 
with. Like a clipboard monitoring option will be great because i will have the ability to know which app is trying to access my clipboard for no reason and flag it malicious.

**Comment by Raif1** [comment]
> Not possible. See #131 (the author of **Storage Isolation** themselves have replied why this is a very difficult and a bit far-fetched task). _Unfortunately, there's a limit on what a single person can do with a limited amount of resources._
>
According to issue #131 . The feature request was implement features like storage isolation. Which contains isolating storage spaces for each apps . I was trying to mean is it  possible to notify the user when an app created a folder or file ?

**Comment by MuntashirAkon** [comment]
> If we want an activity log we will need a sorting system. Like i want to know what is being accessed by whatsapp or like who is using storage permission.

Yes, it's all there, and it's easier to implement than a notification system, and there is no need to disturb the user with constant notification. It might be even possible to intelligently guess or mark suspicious activities.

**Comment by MuntashirAkon** [comment]
> I was trying to mean is it possible to notify the user when an app created a folder or file ?

No.

**Comment by Raif1** [comment]
> It might be even possible to intelligently guess or mark suspicious activities.
>
Like creating some templates of what a keyboard , messeging app should do and have access to . If it does something out of that template it will get marked suspicious. **Really** cool .

**Comment by MuntashirAkon** [comment]
Superseded by #1023
