### ISSUE TITLE
material you initializing background

### ISSUE THREAD

**Issue by andsofine** [MuntashirAkon/AppManager#769]
- [✓] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [✓] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
on startup background during initializing does not use material you colors

**Screenshots**
![Screenshot_20220602-231814](https://user-images.githubusercontent.com/99369164/171730710-19684f94-0862-4859-b331-a75c197bf5dd.png)

**Device info**
 - Device: Pixel 4 xl
 - OS Version: Android 12L grapheneos
 - App Manager Version: 3.0.0-rc02
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
This is a known issue. See https://github.com/material-components/material-components-android/issues/2555

Unfortunately, I am unable to fix this issue because I do not posses any device/emulator with Android 12 installed. At this point, the fixes I've made for Android 12 were based on the feedbacks from the testers.

**Comment by MuntashirAkon** [comment]
Should be fixed in 682d3366fa4883c0891e9918c029b0441f559933
