### ISSUE TITLE
matrix, telegram chat 

### ISSUE THREAD

**Issue by andsofine** [MuntashirAkon/AppManager#771]
it would be nice to create a chat (matrix, telegram) to discuss issues, etc. 
to reduce the number of duplicates of known issues. in chat you can ask if issue is known.
search does not always help to find out what is already known

**Comment by MuntashirAkon** [comment]
I do not have enough time to maintain chat groups.

There used to be a Telegram group which was discontinued earlier this year as I could no longer be able to take the pressure. The number of duplicates in GitHub, as of today, is less than 50. If there were a Telegram group, you'd see this number of duplicate issues within three weeks. Since the funding campaign had failed, App Manager still remained to be a side project for me, and I do not afford to spend too much time on it.

**Comment by MuntashirAkon** [comment]
> Is this issue known when you open the app manager and then use other applications and then open the app manager again and it doesn't open?

No. Never heard of this issue before.

> and about the chat, I think the community could tell each other about what issues are known, and you don't have to control it and waste your time

Believe it or not, this was also attempted before finally terminating the group. It worked for a few months until the admins lost interest in the group and decided to leave as I was not active there. @PookaMustard, @Deerp1976, @tommynok and many other contributors were in the group too. They can also explain quite well as to why the group was terminated.

**Comment by MuntashirAkon** [comment]
You need to send some logs using the debug builds. But at first, create a new issue because it's off-topic for this one.
