### ISSUE TITLE
Possible false reporting of Data Usage of other apps

### ISSUE THREAD

**Issue by metronightly** [MuntashirAkon/AppManager#801]
- [x] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
On opening details of the following two apps
i.Privacy Dashboard
ii.Open in WhatsApp
I found that they used Internet and some data was transmitted. But the thing is that these apps don't even have Internet permission, which I verified via AM and Netguard.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Privacy Dashboard from Play Store and Open in WhatsApp from F-Droid.
2. Open App Manager and search the above 2 apps and open app info on AM.
3. Scroll down to Data Usage.
5. To verify if the apps even have internet permission, follow step 2 and swipe till 'Uses Permission'
6. Search for 'Internet'
7. See no result.

**Expected behavior**
The two apps shouldn't have any form of data usage since they don't have internet permission, verified via AM and Netguard.

**Screenshots**
![IMG_20220711_133906](https://user-images.githubusercontent.com/75716685/178230772-0259a124-e411-4e85-bb36-d2984f2af2c0.jpg)

**Device info**
 - Device: Realme c3
 - OS Version: Android 11
 - App Manager Version: 3.0.0-rc04 (406)
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
This is likely happening because your OS has reassigned User ID (UID) to these apps from the previously uninstalled apps (which, if true, is a highly irregular behaviour unless you have installed and uninstalled a lot of apps in the lifetime of the OS). Let me explain why this matters:

Usage data are NOT obtainable for each app but for each UID. Except in a few exceptional cases (e.g. system apps) where shared UID are used (shared UID is deprecated in Android 12 and earlier, and removed in Android 13 for the users apps), most user apps are assigned a unique UID for each package. So, to retrieve usage statistics (e.g. app usage, data usage) for an app, it is enough to retrieve the statistics for the associated UID of the app. However, usage statistics are stored in some files (to make the cleaning easier) in the `/data` partition and not in a flexible data store. Once they are written, these files aren't modified again, and old files are removed after some time depending on how much storage the device has, etc.

So, if the system assigned the UID `100204` to an app which had transmitted some data over the Internet, the data usage will be logged in the mentioned files and you'll see the usage in App Manager or elsewhere. Now, say you uninstalled the app and installed another app which the system assigned the UID `100204` again. What would happen? Since the log files weren't deleted yet, when the system would still retrieve the old data usage even if the new apps do not have the Internet permission, and therefore, incorrect data usage will be displayed. Like data usage, the same is also true for app usage.
