### ISSUE TITLE
Ability to select a custom port for adb over tcp

### ISSUE THREAD

**Issue by sudo-nautilus** [MuntashirAkon/AppManager#832]
- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**

5555 is a commonly used port that will catch attention easily, I found [this article](https://labs.withsecure.com/blog/hackin-around-the-christmas-tree/) on the internet.

**Describe the solution you'd like**

It'd be really nice to pick a custom port for this purpose

**Describe alternatives you've considered**

Hmm, shizuku maybe?
I searched for that in the issues, currently shizuku has an Apache 2.0 licence and is available on f-droid via IzzyOnDroid repo

**Additional context**

N/A

**Comment by MuntashirAkon** [comment]
Port scanner software can be used to detect all the opened ports in an IP address quite easily. But to detect an ADB port in the newer versions of Android, it is much easier to just run an mDNS browser. However, unless port forwarding is enabled, ADB over TCP only works in your local network. So, if you're on a private network, you should be safe from any real harm. To prevent such attacks, `userdebug` builds (except Lineage OS and its derivatives) should be avoided entirely, and if you're running Android 11 and later, use wireless debugging instead of ADB over TCP and disable it once App Manager has connected to it.

**Comment by sudo-nautilus** [comment]
I see, thanks
