### ISSUE TITLE
Activity memory leak caused by anonymous threads

### ISSUE THREAD

**Issue by cuixiaoyiyi** [MuntashirAkon/AppManager#854]
# Possible Memory Leak
An [anonymous inner class](https://stackoverflow.com/questions/17778077/would-anonymous-handler-or-runnable-create-a-memory-leak) will hold a reference to the this pointer of the outer class and will not be released until the thread ends.
It will hold the Activity and prevent its timely release. Please check the links below.

# Occurrences
https://github.com/MuntashirAkon/AppManager/blob/master/app/src/main/java/io/github/muntashirakon/AppManager/profiles/ProfilesActivity.java#L151

# Possible Solution
If it is necessary, it can be changed to [static class + weak reference](https://stackoverflow.com/questions/22162642/will-handler-inside-a-method-leak-memory/27825703#27825703) to eliminate the reference to the activity, which may cause memory leaks.
Further discussion is welcome.

**Comment by MuntashirAkon** [comment]
Hi,
We're gradually migrating the project to MVVM architecture and replacing `Thread`s with `ExecutorService`s that runs inside a `ViewModel`. But as you can see this is a sufficiently large project (~100K LOC sans all the other libraries that I maintain solely for this project) with only a single developer, it's difficult to fix complicated issues such as memory leaks because the amount of time it requires for refactoring or planning alternatives. If you're interested, you can contribute to the project (be sure to read the CONTRIBUTING file first). Thanks!

> If it is necessary, it can be changed to [static class + weak reference](https://stackoverflow.com/questions/22162642/will-handler-inside-a-method-leak-memory/27825703#27825703) to eliminate the reference to the activity, which may cause memory leaks.

A more modern solution is to use the ViewModels which allow better handling of the activity/fragment lifecycles. Use of WeakReferences are discouraged and should only be used when there are absolutely no alternatives.
