### ISSUE TITLE
Backup progress indicator

### ISSUE THREAD

**Issue by 2011** [MuntashirAkon/AppManager#865]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**

I have started experimenting with backups on one device, and I feel quite unsatisfied. It doesn't save my settings (what I want backed up, and even checking the options requires two taps for some reason), it takes **much** longer that other backup apps (more than four hours versus about 10 minutes - would really like the backups to take a normal amount of time, as well), and I just see a notification noting an operation in progress with no indication of the progress of the operation.

**Describe the solution you'd like**

Would like to see something like "backing up com.example, number x of y."

**Comment by MuntashirAkon** [comment]
A detailed explanation is required to actually understand what you're trying to say other than something that is already requested in #347. Backup is fairly fast in my only device (quite old with 3 GB RAM and 8 threads). For instance, it takes less than one and half a minute to take a backup of _Bromite_ with ~500 MB uncompressed size.

**Comment by 2011** [comment]
On the device I have tested Backup with (also an older device with 3 GB of RAM), I just did a backup of all apps (except for System UI, which resets the wallpaper) with Titanium Backup (which obviously misses the splits for processor type, display DPI, and language). It took 8:02 to complete. Backing up the same apps (on the same device, of course) with AppManager Backup requires well over four hours.

**Comment by 2011** [comment]
I don't know if this has any relevance, but I back up to the external SD card. In the years, I have used Titanium Backup, I have never had an issue with that. But twice using AppManager Backup, the SD card "disappeared" on conclusion of the backup (meaning that the system now longer saw it), and I had to reboot the device (an Android 6 phone) in order to access the SD card again.

**Comment by MuntashirAkon** [comment]
> On the device I have tested Backup with (also an older device with 3 GB of RAM), I just did a backup of all apps (except for System UI, which resets the wallpaper) with Titanium Backup (which obviously misses the splits for processor type, display DPI, and language). It took 8:02 to complete. Backing up the same apps (on the same device, of course) with AppManager Backup requires well over four hours.

Try App Manager v2.5.23 (for testing purposes only) to see how long it takes (make sure to take a backup of the backups before you run that because v2.5.23 was a testing release and backups might not actually restore in the later versions App Manager). There could be many issues and it is necessary to pin-point exactly where the problem lies. After two days, I will be ready to send you some debug builds for testing purposes if you're interested in helping me out as you are experiencing a significant deterioration of its performance.

> But twice using AppManager Backup, the SD card "disappeared" on conclusion of the backup (meaning that the system now longer saw it), and I had to reboot the device (an Android 6 phone) in order to access the SD card again.

I have absolutely no idea why this might be happening. If direct access to SD Card is causing trouble, you might want to try SAF instead.

**Comment by jmichael2497** [comment]
> Would like to see something like "backing up com.example, number x of y."

since this can do multi threading, rather than linear, that could complicate things. maybe build a task list, then show work in progress bar status x#/y# tasks complete.

it is very frustrating to have hours long tasks running with no idea if it will be done anytime soon, and i was surprised such a basic design element was missing.

i noticed this issue after using for some split apk backups that TB couldn't handle. also when i tried importing from LOS a11 TB to see if AM could restore them properly to LOS a13 (but most failed to import anyway, so went back and did all the backups with AM).

cheers for the "Has Activities" filter and "User First" sorting.

> the SD card "disappeared" on conclusion of the backup (meaning that the system now longer saw it), and I had to reboot the device (an Android 6 phone) in order to access the SD card again.

i've recently experienced similar with 64G exfat formatted sd card in computer halfway through trying to copy 6G of TWRP backup (mostly 1G files) onto the card.

my theory was it did not like the sustained write speed, since it seemed fine copying one at a time. so more likely hardware (card overheating or just can't keep up) issue rather than AM issue specifically.

**Comment by MuntashirAkon** [comment]
> maybe build a task list, then show work in progress bar status x#/y# tasks complete.

This is what I too am thinking of implementing.

> it is very frustrating to have hours long tasks running with no idea if it will be done anytime soon, and i was surprised such a basic design element was missing.

Delivering notifications in Android in a proper is not an easy tasks. They have sacrificed usability in order to increase flexibility or make it more generic.

> when i tried importing from LOS a11 TB to see if AM could restore them properly to LOS a13 (but most failed to import anyway, so went back and did all the backups with AM).

I've never used TB myself (TB is a highly obfuscated non-free app which could easily be replaced by OAndBackup back then). It was implemented because the TB users who were stuck with their early backups and cannot find a way to restore them in the new versions of Android as well as to promote the use FOSS alternative. Earlier, a user imported TB backups from Android 4.4 and all of them restored properly in Android 8. So, I concluded that backups were imported properly. If AM cannot import a backup, you have to report it along with files (if possible) so that I can test them.

> i've recently experienced similar with 64G exfat formatted sd card in computer halfway through trying to copy 6G of TWRP backup folder (mostly 1G files) onto the card.
> 
> it seemed fine copying one at a time, with the brief pause of manual mouse clicks. so my theory is more likely hardware (card overheating or just can't keep up sustained writes) issue rather than AM issue specifically.

There is also a possibility of a bad OTG support. A few years ago, I lost a TWRP backup due to corrupted files. After an investigation, I found that there is a problem with the OTG support which causes issues when several files are read/written in parallel.

**Comment by jmichael2497** [comment]
> If AM cannot import a backup, you have to report it along with files (if possible) so that I can test them.

btw, i should've mentioned but my TB backups were using TB encryption, so maybe that was it, otherwise i can figure out which apps don't have sensitive data to file a bug report.

meanwhile, glad to switch to AM as primary open source backup solution now for my 5.0+ devices (which means i should get my old tablet upgraded from 4 to 7 soonish 😅)

though still need to rely on proprietary apps like TB for some things like sms/mms and call logs (TB wifi ap list didn't restore through).

**Comment by MuntashirAkon** [comment]
> my TB backups were using TB encryption, so maybe that was it

Yes. AM does not support TB encrypted backups.

> though still need to rely on proprietary apps like TB for some things like sms/mms and call logs

You'll find many apps on F-Droid that do that. One such example is [SMS Import/Export](https://f-droid.org/en/packages/com.github.tmo1.sms_ie/) which _imports and exports SMS and MMS messages, call logs, and contacts._

**Comment by jmichael2497** [comment]
> You'll find many apps on F-Droid that do that.

i didn't have much luck a year ago with all the the f-droid listed non-cloud local-only sms/mms backup/restore apps going from stock a7 to LOS a11, and had to use the commonly recommended play store SMS Backup & Restore app.

i know a year is a long time for improvement, but my patience was exhausted over the prior week plus messing with water damaged phone.

only having patience for one new app, tried yours, which thankfully worked where TB failed for general data backups, so i'm glad to take small steps towards open source when i can.

cheers!

**Comment by MuntashirAkon** [comment]
> i didn't have much luck a year ago with all the the f-droid listed non-cloud local-only sms/mms backup/restore apps going from stock a7 to LOS a11, and had to use the commonly recommended play store SMS Backup & Restore app.

Backing up SMS is fairly easy thing to do, but backing up MMS is quite difficult because there is no official documentation regarding this, not to mention the compatibility issues that are needed to be handled properly. Backing up wireless access points or bluetooth pairing is even more complicated due to compatibility issues and learning curve. This is why you don't usually see any open source apps supporting them.

**Comment by MuntashirAkon** [comment]
Implemented in 688308dcee755f24faa6cefd1a468891064a02e8 via 00a897c7bb7147dcd93aba557ccd83e06a98297f, 9737c375f53f054874befe452ddb34e205edc4e1

This is implemented as follows:
1. A central notification describing the number of apps backed up or restored (e.g. 8 out of 21)
2. A group of notifications describing the status of currently running backups (e.g. 60%).

Note that the progress indicators may not always be perfect due to many complications related to multi-threading. But this, I believe, is a step to the right direction.
