### ISSUE TITLE
adb pairing via WiFi using notification bar 

### ISSUE THREAD

**Issue by ElissonRodrigues** [MuntashirAkon/AppManager#892]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Some Smartphones do not have the function of splitting the screen to enter the pairing data, which makes pairing impossible 

### Describe the solution you'd like

Enter the pairing data (Code and Port) through the notification, as with Shizuku

example in this video:

https://user-images.githubusercontent.com/25101186/196178513-6cccbe8a-45c5-4600-8b8a-7f4b820385c7.mp4

**Comment by MuntashirAkon** [comment]
It seems that some devices do not support splitting screens. Therefore, we also need notification option alongside the existing one.

**Comment by Efreak** [comment]
Should be able to automate pairing via wireless, I think this might be the correct line from Shizuku? https://github.com/RikkaApps/Shizuku/blob/bc29dd17b286ad0b623a0341df2de397cbad5757/manager/src/main/java/moe/shizuku/manager/home/AdbDialogFragment.kt#L73

**Comment by MuntashirAkon** [comment]
The only way you can automate pairing is via the accessibility services. Connecting to ADB demon has already been automated. It has a few known issues, however, which have low priorities because the amount of investigation needed to figure out those issues outweighs the benefits.

**Comment by MuntashirAkon** [comment]
What do you mean? App Manager is already capable of automatically connecting to ADB if it is enabled before opening App Manager.

**Comment by MuntashirAkon** [comment]
> It often asks me for a port number when starting up, after I press the "connect" option I believe. The number is pre-filled but I've had it not work, and when going into wireless debugging settings, I'll find that the port number does not match.

App Manager would only ask for a port number when it is unable to find one within five seconds. This is deliberately done so that it wouldn't affect UX too much. Once App Manager is connected to ADB (and the devices wasn't restarted or USB debugging wasn't disabled), it is no longer necessary for an user to connect to ADB since App Manager runs a server in the `shell` context and connect to it directly instead of asking the user to connect to ADB again. This is proven to be faster than the usual method as well as useful to users who cannot connect to Wi-Fi all the time. So, if you're repeatedly asked for port number, this might be an bug and you should create a bug report instead. [This discussion is offtopic to this issue as the author only asked to implement another way of connecting to ADB].

**Comment by MuntashirAkon** [comment]
> I can put this in a bug report if this not expected behavior.

I think you should report it as a potential bug. The current adb library is maintained by me and is used by many projects. So, it might be helpful to others, too.

**Comment by MuntashirAkon** [comment]
Implemented via 42c316fd501771699f55d2bcd0e9f2882d405c7a
