### ISSUE TITLE
Usage stats

### ISSUE THREAD

**Issue by fynngodau** [MuntashirAkon/AppManager#90]
I noticed that in your wrapper class for the usage stats API, you have set the constant `USAGE_TIME_MAX` to `5000` and are dropping usage timespans below this amount of milliseconds. Why is that? This causes a difference of multiple minutes to the values I am getting out of [my own wrapper implementation](https://codeberg.org/fynngodau/usageDirect/src/branch/master/Application/src/main/java/godau/fynn/usagedirect/wrapper/EventLogWrapper.java#L42), thus your implementation seems to return too low values (removing this lower limit yields the same "total time" data as my implementation under normal conditions).

Also, the assumption that events are always ordered in the order `MOVE_TO_FOREGROUND` – `MOVE_TO_BACKGROUND` – `MOVE_TO_FOREGROUND` – `MOVE_TO_BACKGROUND` – … has turned out not to be true, unfortunately, as I observed at least one occurrence where two events were inexplicably swapped. However, unless one *also* makes the assumption that an unmatched `MOVE_TO_BACKGROUND` event means that this application has been opened before the period that was queried from the event log, the effect of this error in the data is rather small.

Lastly, your implementation ignores unmatched `MOVE_TO_FOREGROUND` events. This doesn't really matter much unless the following neglectable scenario plays out: somebody opens your activity, leaves it open for a few minutes and then pulls refresh; this would lead your application to show the same data again if I'm not mistaken.

(Typing this, I spotted another oversight in my own implementation (: )

**Comment by MuntashirAkon** [comment]
Current implementation is somewhat similar to https://github.com/zhaobao/AppsMonitor (as you might have noticed from the credits section). Initially, I've copied (your app) UsageDirect's implementation (few months ago, the algorithm might be changed in the mean time) which turned out to produce very bad results. I've noticed that AppsMonitor's results are very similar to the Digital Wellbeing apps (by Google and Samsung). So, I've copied its code instead but the algorithm used by this app turned out to be faulty (and somewhat messy) as well. So, I had to change the algorithm a bit to produce more precise results.

> you have set the constant `USAGE_TIME_MAX` to `5000` and are dropping usage timespans below this amount of milliseconds. Why is that?

To be honest, I still have no idea why it works with this value. You can ask @zhaobao about it. But it seems some system apps often move to foreground/background without any user interaction (could be triggered by broadcast receivers). Since broadcast receivers are allowed to run for 10000ms, `USAGE_TIME_MAX` should be set to this value. But interestingly it's set to half of this value.

> Also, the assumption that events are always ordered in the order MOVE_TO_FOREGROUND – MOVE_TO_BACKGROUND – MOVE_TO_FOREGROUND – MOVE_TO_BACKGROUND – … has turned out not to be true, unfortunately, as I observed at least one occurrence where two events were inexplicably swapped.

Yes, this is true. But it's extremely rare case and triggered for some reasons not known to me yet (as you've seen, there's no documentation at all about this as if Google doesn't want any user app to deal with these things). This could be due to some weird bugs in the Android Frameworks as well (like the one I've found with the `appops` command in #17).

> Lastly, your implementation ignores unmatched MOVE_TO_FOREGROUND events.

This is done on purpose. If a device were accidentally rebooted while an activity was opened, you'd get the most weird results.

@Deerp1976 and I worked a lot with this issue (where he has tested my implementations with other apps) and finally concluded that the current algorithm produces good results when compared with other popular apps.

**Comment by fynngodau** [comment]
> Initially, I've copied (your app) UsageDirect's implementation (few months ago, the algorithm might be changed in the mean time) which turned out to produce very bad results.

The Android usage stats API has two different data sources, one is the event log and the other is the aggregated usage stats. These aggregated stats have a terrible API (which my wrapper class works around fairly well in my opinion), are highly unreliable and do a lot of silly things very often (and there's nothing I can do to workaround that), which is why from version 0.5 on my application uses the event log instead. (I see you have code to try querying data up to five times. That would be of use for this bad API but for the event log, it seems unnecessary to me.)

> This could be due to some weird bugs in the Android Frameworks as well (like the one I've found with the `appops` command in #17).

That was the case for the aggregated stats API as well, it's just really terrible.

> But it seems some system apps often move to foreground/background without any user interaction (could be triggered by broadcast receivers).

Ah, I never thought about them, but that would explain these few seconds of "Android System" and "System UI" that I'm seeing.

> This is done on purpose. If a device were accidentally rebooted while an activity was opened, you'd get the most weird results.

My implementation handles this by checking whether the app that has the unmatched start event is still in the foreground at the moment, though it uses an API that is not intended for that unfortunately. If the app is not found to be open it drops the unmatched start event.

**Comment by fynngodau** [comment]
(I'm currently still testing how accurate my data is exactly, by continually comparing "adding up data for the whole day at once" and "adding up data for parts of a day throughout the day".)

**Comment by MuntashirAkon** [comment]
> My implementation handles this by checking whether the app that has the unmatched start event is still in the foreground at the moment, though it uses an API that is not intended for that unfortunately. If the app is not found to be open it drops the unmatched start event.

It seems the Usage Stats APIs are very buggy, especially the NetworkStatsManager (along with other compatibility issues).

**Comment by fynngodau** [comment]
I think the event log API is okay, besides that my wrapper class needs to do multiple steps of abstractions around it to get the data I want.

Especially if you want to query longer timespans like whole days and not fractions of a day, an older version of my implementation that ignored all those edge cases was simpler and served quite well. I only decided for more complicated considerations because I'm interested in storing data to a database while managing these two annoyances: timezones (wouldn't want to count a period twice) and the case that the event log is suddenly deleted.

Thanks for the warning about NetworkStatsManager, then I'll know what I *don't* want to have a look at.

**Comment by MuntashirAkon** [comment]
@Deerp1976 Could you help me compare among these apps, again?

**Comment by MuntashirAkon** [comment]
@fynngodau It seems the latest version isn't on F-Droid. F-Droid captured it but failed to build it for some reason.

**Comment by fynngodau** [comment]
@MuntashirAkon This was due to the introduction of two build flavors for the different data sources, there was a recent fdroiddata MR to fix it and to include the other build flavor as a separate app as well. You'll likely want to compile the latest commit at build flavor `database`.

**Comment by Deerp1976** [comment]
@fynngodau 

With regards to the information @MuntashirAkon has already told you about, when I was testing your app which would have been the latest build from about 2 months ago, I was getting very unusual reports back such as in a days usage I had been on the Contacts app for over 16 hours. There were some other discrepancies with other apps. Me and @MuntashirAkon tested quite a few apps that provide app usage and at the time found App Monitor to be the most accurate. I personally compared app usage with every app on my phone with Digital Balance which is a Huawei system app which keeps a record of app usage. I found with all these apps that have access to app usage all come back with some conflicting information though. I look forward to testing your latest build. I will of course respond here if there is any unusual activity so you can investigate it further.

Thanks

**Comment by Deerp1976** [comment]
@fynngodau many thanks for the your latest debug build. It is clear to see the difference now with the database you're using compared to earlier builds.

So far from my initial assessment of tracking my own app usage and comparing it to your app, yours is very accurate.

There are some things I do not understand and would appreciate some insight from yourself please.

1) I have an app on my phone called 4A Settings Database Editor. This I'm turn has a paid app called 4A Feature Pack for SetEdit. This paid app cannot be launched and has no activities to speak of that can launch this separate paid app. All it does is activated new features on 4A Settings Database Editor. Your Usage Direct app shows 0.00 for the main 4A app and all app usage is on the paid app. I would like some insight into how this possible? Screenshots provided.

2) One of the biggest issues for me on your older builds and why I was recommending @MuntashirAkon to not use it his App Manager app is because it was showing app usage fro system apps that were never used in the foreground. Apps such as contacts app, your launcher. The problem seems to have gone for the most part but your debug build app is still collecting data for apps I could not possibly have used. For example, I have a Huawei Honor 8S phone (non-rooted) with its own stock Huawei launcher. My default launcher is Smart Launcher and yet your debug app is saying I've been in the stock launcher for 2 minutes. Admittedly this is a vast improvement on 16 hours like it was showing before but it is still collecting data from apps that are never in use by me. If this is the fault of Android or Huawei somehow opening up the stock launcher briefly before going to my launcher, please tell us.

There are other system apps which not even launchable that is showing data collected such as Huawei share. I don't even know what this app does and it is impossible to launch normally and there are no activities to activate this system app to check. Again screenshot provided to show you.

3) What are the benefits of refreshing the database you use to collect data? Does it need refeshing every day? Is it only for debugging purposes?

4) So far the app only shows data for the past few days. This in itself is extremely useful to compare data over a period of days to compare app usage to see if you're using an app too much on certain days. Will you be implementing app usage for weeks and months soon like you had before?

Summary

Your app is vastly improved and I'm very impressed by it and the data being collected. Comparing to system apps I've got the data is extremely accurate apart from the queries I've discussed.

Many thanks.

![Screenshot_20200908_193802_godau fynn usagedirect debug](https://user-images.githubusercontent.com/61953306/92517235-4471e400-f20e-11ea-9f11-ba5fe4533430.jpg)
![Screenshot_20200908_193545_godau fynn usagedirect debug](https://user-images.githubusercontent.com/61953306/92517237-450a7a80-f20e-11ea-97b9-aaac12f3cc9f.jpg)
![Screenshot_20200908_193553_godau fynn usagedirect debug](https://user-images.githubusercontent.com/61953306/92517240-45a31100-f20e-11ea-8003-ab0864b15c26.jpg)
![Screenshot_20200908_193655_godau fynn usagedirect debug](https://user-images.githubusercontent.com/61953306/92517243-463ba780-f20e-11ea-9b0a-ca2d5b8e4e4c.jpg)

**Comment by MuntashirAkon** [comment]
Thanks @Deerp1976 for yet another astounding review. It's good to know that **usageDirect** is heading towards the right path. I haven't yet taken a look at the new app but the UI looks impressive and matured than before.

About the launcher app, the launcher app often switch between foreground and background and vice versa without any visible interaction. This behaviour is completely discreet and I've yet to find any reason for it. It even switches between foreground and background when another app is running. There are multiple combinations possible, one example is as follows: _Launcher in foreground > App in foreground > Launcher in background > App in background_, another peculiar example is: _Launcher in foreground > App in foreground > App in background > Launcher in background_ (in which case, you will get a very long usage). My current algorithm ignores these weird behaviours as much as possible but whether it's perfect is still in question.

**Comment by Deerp1976** [comment]
Thanks for the kind comments @MuntashirAkon I appreciate them.

Yes the UI for Usage Direct is excellent. It simplifies matters to show you data you need to see. In particular the main screen, it just shows a list of days and is very easy to use to click each one to compare data between days.

With regards to the launcher, your evaluation makes a lot of sense I appreciate your detailed post explaining it. What I do not understand is how Usage Direct is collecting data on the stock launcher when I haven't even got it as default. Surely if my default was being shown in background/foreground, the data collected would just be for that launcher rather than the one that is never in use? The only logical explanation I can think of is this stock Huawei launcher is constantly running. You cannot force stop it. It's always on, so my assumption is the data collected when the launcher is in foreground/background is collected by both launchers as they are both running at the same time.

**Comment by fynngodau** [comment]
> Your Usage Direct app shows 0.00 for the main 4A app and all app usage is on the paid app.

This indeed is mysterious, I have no clue how this behavior occurs. If my implementation is correct, this must mean that there have been `MOVE_TO_FOREGROUND` events for the paid extension, not for the base app, *except* that there must have been a *tiny* timespan that the base app was supposedly in the foreground, because otherwise it would not be displayed at all. Maybe you can check the event log to verify that – it is at the top of the output of `adb shell dumpsys usagestats`.

> Apps such as contacts app

This sounds a little bit like it logs background services to the event log as well (though I do not know precicely what services your apps are running), even though the [documentation](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/usage/UsageEvents.java;l=77?q=CONTINUE_PREVIOUS_DAY&ss=android) seems to gurantee us otherwise.

It would be very tricky since we wouldn't want too specific cases for each application… I mean, we *could* filter events of certain apps that are taking, for example, less than three seconds? It would involve a fair bit of guessing, and it wouldn't cover the specialties all the other vendors might have invented.

Regarding the mysterious launcher events, I noticed that I, too, am getting events for my stock launcher (Trebuchet) even though I am using Lawnchair. I just discovered the reason for this – it provides the "Recent apps" screen. For example, the following line appears in the event log when I open "Recent apps":

        time="2020-09-09 08:03:46" type=MOVE_TO_FOREGROUND package=com.android.launcher3 class=com.android.quickstep.RecentsActivity flags=0x0 

Additionally, I just found out that opening the system's "Share" or "Open with" menu, for me, increases the usage time of "Android system". Maybe this could be the app "Huawei share" for you?

> What are the benefits of refreshing the database you use to collect data?

Maybe I can illustrate the flow of the event log data:

    Event log  →  Database  →  UI

This primarily serves a practical reason, namely that otherwise, I'd have to show *both* event log *and* database in the UI. However, there's another arguement for it, and that is that data stored in the database is not lost (e.g. in case the event log is suddenly cleared). This is because from version 0.6 on (including your rc), I will copy into database *precicely incrementally*.

So if you open the app at 8 o'clock, your phone crashes at 9 o'clock and you open the app again at 10 o'clock, it will contain data from the start of the day until 8 o'clock, added up with data from 9 o'clock until 10 o'clock. In previous versions, the data from the start of the day until 8 o'clock would have been overwritten with the new data from 9 o'clock until 10 o'clock – less data is lost.

> Will you be implementing app usage for weeks and months soon like you had before?

Yes, I expect I will readd this functionality in one of the next releases. However I will likely not add the second layer of tabs again – even though all features were on the main screen, everything was very packed and there was no room for new features. Additionally, while the nested tabs worked *surprisingly* well, it *did* overload the "side swipe" gesture in a way that was not immediately clear. Thus, I might add a sidebar menu.

Lastly, thank you for your kind words regarding user interface and UI.

**Comment by Deerp1976** [comment]
@fynngodau 

Many thanks for your response, it was most interesting to hear about how your app works and how system apps are showing data when you don't open them in foreground.

I can confirm your findings for the stock launcher as I've just discovered the recent apps does indeed have a connection to stock launcher. I use an app called Netguard you may have heard of. For non root phones, it needs a VPN connection to stop other apps connecting to the internet. The problem with my phone is it doesn't have good ram, only 2gb which makes it problematic to keep an app open in the background constantly whilst using other apps so I decided to go in settings on my phone and deny all network access to every single app on my phone so whenever you use an app, my phone asks me if I want to allow that app network access. By using the recent apps options to clear them, it does indeed ask me if I want to give Huawei Home launcher network access so that clears that up nicely.

The Huawei Share app is indeed used for 'Open with' so that also clears that up perfectly. Thanks for helping discover this.

I have downloaded your system usage stats and latest build in Fdroid for Usage Direct. There is an hour difference between System Usage Stats and Usage Direct in how long in total I've used my phone for today. Going through my apps it looks like the biggest difference is with a game I play a lot called Tom Clancy's Elite Squad. This game frequently crashes on my phone due to large ram usage so I think your System Usage Stats is not able to get accurate data because of that.

Is there any particular reason why you have the two apps on Fdroid?

In particular I love on the System Usage Stats app how you have stated how long it has been since you've used that app. If you incorporate this into your Usage Direct app, then I am happy to give my seal of approval to @MuntashirAkon for it to be incorporated on App Manager after he has tested my findings himself of course.

As far as I'm concerned the apps that all have statistics showing a few seconds of usage can all be explained. The only anomaly is that 4a settings app. My father has my laptop at the moment so cannot test out the ADB command you've suggested but I am happy to send you the apks for both the main and paid all if you wanted to investigate further. They are only around 100k each. I have a protonvpn email which will allow me to send you the apks as we've both discovered Google does not like sharing apps in Gmail! I'm currently looking for other apps that have a paid app separately to see if this statistic is unique to 4a Settings or it is commonplace across all apps that use a 2nd all for paid features. I believe SD Maid has a 2nd app which is just a key to unlock pro features so once I download that again, I will be happy to share my findings with you.

Thanks,

**Comment by Deerp1976** [comment]
@fynngodau 

Oh I also discovered on your System Usage Stats app, the data for yearly app usage is completely inaccurate! It says for the past year I've used only 20 hours for all app usage yet the monthly figure is 486 hours! A strange anomaly indeed.

**Comment by fynngodau** [comment]
> Oh I also discovered on your System Usage Stats app, the data for yearly app usage is completely inaccurate!

Yes, things like this happen all the time. This is unfixable. System usage stats cannot provide reliable data because of the terrible API. Please refer to the in-app help, [also accessible from your phone using this convenince link](https://systemusagestats.toolsnbots.de/help). Specifically, the point "'today' starting at seemingly random points in time" appears to apply.

> Is there any particular reason why you have the two apps on Fdroid?

System usage stats shows certain data that due to being unreliable had to be removed from the main application. However I wanted to prevent a scenario where users would have to switch to an older version just to see previously available charts, as System usage stats contains, as you might notice, e.g. monthly data from more than 10 days prior to app installation ago.

> In particular I love on the System Usage Stats app how you have stated how long it has been since you've used that app. If you incorporate this into your Usage Direct app

Yes, even though it's a little tricky with the rest of the implementation, I do want to add that again.

I don't believe I can do much with that app in specific, and I'll have to decline being sent a paid key to applications that I did not pay for.

**Comment by fynngodau** [comment]
@Deerp1976 I put the feature with displaying "last used" on the "roadmap" for 0.7. I thought maybe you'd be interested in the other ideas I'm having – I wrote them down in a few [issues in my app's repo](https://codeberg.org/fynngodau/usageDirect/issues) (mostly those milestoned 0.7 or 0.8). Though, at the moment, I am busy with schoolwork, so it will likely take some time until I'll be able to implement them.

**Comment by Deerp1976** [comment]
@fynngodau 

I will be very interested to keep being updated with regards to to your roadmap for App Usage. I still have your debug build, stable Fdroid build (with new 0.6 update today) and your system usage app on my phone. 

I do want to discuss in-depth your system usage app on email if you are happy to do so. Here is not the best place for it. I have deep concerns with the statistics it's gathering and I need to go through with you some screenshots. These were taken from your latest 0.6 update available on Fdroid. 

If you agree to this proposal, we can continue the discussion on email. 

At this moment in time, I have discussed the situation with @MuntashirAkon at length. I feel for App Manager to take on board your statistics will be of benefit when your debug build I've got becomes a stable flavour ln Fdroid. Once this has taken place and I do not see this happening in the far future, you get my recommendation for it to be used in App manager for what that is worth. It is a very good app and I enjoy studying it and learning more about my phone and how certain apps are used even when you think they are not. The accurate usage is icing on the cake.

**Comment by fynngodau** [comment]
@Deerp1976 Do feel free to email me.

**Comment by fynngodau** [comment]
@Deerp1976 Though as I mentioned above, the System usage stats application must not be expected to deliver reliable results, as per the in-app warning.

**Comment by MuntashirAkon** [comment]
@fynngodau Hi, any update on achieving precision?

**Comment by fynngodau** [comment]
* Version 0.6 is available on F-Droid.
* There is now documentation on what exactly happens when what data is found: https://codeberg.org/fynngodau/usageDirect/wiki/Event-log-wrapper-scenarios

What is described there is what I'd consider to be the most accurate interpretation of the given data that we can get, because every change I can imagine that handles one scenario better has drawbacks for another. For example, I could increase the query frequency from daily to hourly, which would reduce the risk of loosing data due to the scenario "data gone", but that would mean we'd miss more data in connection with apps that do not appear in `ActivityManager.getRunningAppProcesses()`.
* "Last used" is implemented again, but no release has been released since.
* Feature to remove specific entries from view (in order not to mess up the stats) is half-done (removing is possible, list with removed entries is not done yet)
* In the future, System usage stats (which uses the unreliable "aggregated" API, as opposed to usageDirect) will not be advertised anymore and serve as an "exhibition" of sorts to warn developers not to use `UsageStatsManager.queryUsageStats`.

**Comment by MuntashirAkon** [comment]
Thanks for the update. I've looked at the app. The launcher app problem still remains it seems but only for **today**. When today becomes yesterday, it displays the time just fine.
