### ISSUE TITLE
if you uninstalled the app and reinstall

### ISSUE THREAD

**Issue by terraza1** [MuntashirAkon/AppManager#940]
### Describe the existing feature/documentation

the application always saves the changes after uninstalling. I uninstall it and reinstall it and the previous saved changes appear.

### Describe your problem(s)

I want to uninstall the application since I made some changes that I don't remember, but they didn't sit well with my terminal. And when I uninstall the app, forcing detect and uninstall. I restart the mobile and reinstall it. The application saves yes or yes, all the changes I made. It does not restore everything to how it was. And I give it to delete all the data of the application. Isn't there some way to delete everything and put it like, so to speak, the first time I installed it? So the app always saves everything on the system? Or I don't know if there is a way to uninstall it without leaving any trace and put it back again without any permission removed and so on? I have Lineageos and mobile root.

**Comment by MuntashirAkon** [comment]
> the application always saves the changes after uninstalling. I uninstall it and reinstall it and the previous saved changes appear.

Changes are saved to the system, not in App Manager. It's not possible to create a systemless version of App Manager so that uninstalling App Manager would automatically revert any changes made to the system. So, reinstalling App Manager will not save you from anything. Instead,  you could [remove all rules](https://muntashirakon.github.io/AppManager/en/#remove-all-rules), but even then, not all rules can be reverted.
