### ISSUE TITLE
Updating Fennic (Firefox on Android from Fdroid) lost passwords

### ISSUE THREAD

**Issue by damnedhatter** [MuntashirAkon/AppManager#941]
### Describe your problem(s)

I wasn't able to update Fennic, but using app manager successfully installed the update. It was like a new install tho, and all my passwords were lost. I need to access my email... please help.

**Comment by MuntashirAkon** [comment]
You did not provide any info regarding the steps you have taken to install it. But if you've described it right, it's likely that you've reinstalled the app disregarding the warning regarding your data.

**Comment by MuntashirAkon** [comment]
> Sorry, I'm not so familiar with Android. I didn't see any warning. I guess this is a lessoned learned.

Well, your first mistake is not using an external password manager. Saving passwords in the browser is not a secure means. Secondly, both App Manager and Android OS guarantee the integrity of an update by checking the signature of the app. Even if there were a potentially fatal error in App Manager regarding app installation (which I do not believe because it uses the fail-first ideology, that is, it will fail to install an app if an error is detected, instead of trying with the default options), the OS itself would prevent it by refusing to install the app.

Now, if the APK indeed has a different signature, you'd see the following display. As you can see, there's a hefty warning regarding the loss of your data. If you didn't see this message, it might mean something else, such as an issue with Fennec F-Droid itself.

etc.

![Screenshot_20221201_080809](https://user-images.githubusercontent.com/8176128/204949034-a61d2ef7-7912-46d3-b2db-9575e204b214.png)
