### ISSUE TITLE
Installer queue never processed

### ISSUE THREAD

**Issue by Omrigan** [MuntashirAkon/AppManager#953]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

The applications are apparently stack up at the installer queue and there is no way to check if it is indeed there, and what's causing the blockage.

So I guess this ticket is more like 3-in-1:
1. The main problem is described in "To reporduce"
2. I think the explicit view of the installer queue would be a nice thing to have, so on can view all install requests, reorder, maybe collect debug info for the case when the queue is frozen (like I have). The thing is a background installer is very convenient when used with Aurora Store, which doesn't have it's own installer queue and it's easy to just lose an application on the way from downloading to installing an apk.
3. Maybe update the docs to add more clear indication how the installer and the queue works

### To Reproduce

0. I've done a number of successful installations from both Aurora and FDroid. Maybe one of the apps has failed and blocked the queue.
1. I try to install another one (particularly, GadgetBridge from FDroid)
2. The notification "An app is added to the queue" is appeared
3. Install doesn't happen in the near ~15 mins

### Expected behavior

The ideal case is that I can see the whole queue and applications are not lost

### Logs

Honestly, I see nothing there, but I may try to collect it again

### Device info

- Device: Pixel 7 Pro
- OS Version: Latest GrapheneOS
- App Manager Version: 3.0.3
- Mode: Root/ADB/NonRoot: ADB wireless, but I think I've seen it in NonRoot mode as well

**Comment by Omrigan** [comment]
> In no-root mode, the installer might be stuck for 5 hours if the app currently being processed displayed an installation confirmation notification (which opens the installation confirmation dialog supplied by the Android package installer) just before an item was added to the queue. This happened due to an overlap in the notifications (fixed in [098ca5d](https://github.com/MuntashirAkon/AppManager/commit/098ca5d54bba3bc225f98b8ca74ff0a357c72fe4) and will be available in the next release) which prevented the user from launching the dialog.
> 
> I don't know why the installer would be stuck in ADB mode.
> 

Thanks for explaining. I believe I've just seen it again, with no-root mode disabled long ago (last time I've seen it only a short time after switching to ADB).

> > Honestly, I see nothing there, but I may try to collect it again
> 
> You have to take logs using the debug builds which are available via GitHub actions.

I will try with debug, thanks. Out of curiosity, would it be hard to have debug logs option in the main build?

Any thoughts on adding installer queue view in the app?

**Comment by MuntashirAkon** [comment]
> Any thoughts on adding installer queue view in the app?

This queue is handled automatically by Android Service.

**Comment by Omrigan** [comment]
> > Any thoughts on adding installer queue view in the app?
> 
> This queue is handled automatically by Android Service.

Yeah, but it would be very convenient to see that queue explicitly, like Google Play.

So in my case I use fdrod, aurora and some APK. AppManager could be a unified place to see all requests to install apps, it's status, whether it is successful, how long does it take and so on.

**Comment by MuntashirAkon** [comment]
> Yeah, but it would be very convenient to see that queue explicitly, like in Google Play store.

You're mistaking App Manager's installer with app stores. The installer is a replacement for the Android/Google-provided installer. Hence, the purpose of the installer is to install an app provided by a source which could be an app store, file manager or any other source. The queue is only an additional feature that the default installer does not offer. You cannot expect anything more from it. It's the job of the other app stores to keep track of things like that and I think most stores already does that. When #464 is implemented, you'll see such list in App Manager too.

> AppManager could be a unified place to see all requests to install apps, it's status, whether it is successful, how long does it take and so on.

Yes, App Manager can store a history of installation attempts. But this is not the same as displaying a queue like in the app stores. If this is what you want, you can open a feature requests for this so that I can look into this later.

**Comment by Omrigan** [comment]
> > Yeah, but it would be very convenient to see that queue explicitly, like in Google Play store.
> 
> You're mistaking App Manager's installer with app stores. The installer is a replacement for the Android/Google-provided installer. Hence, the purpose of the installer is to install an app provided by a source which could be an app store, file manager or any other source. The queue is only an additional feature that the default installer does not offer. 
> You cannot expect anything more from it. It's the job of the other app stores to keep track of things like that and I think most stores already does that. 

That is true, but the queue in fdroid and aurora isn't perfect (plus it's distributed across apps, plus you don't have it for direct APKs). They should do the job of queueing and tracking downloading, but then once they pass the installation request to the AppManager, AppManager could have its own queue only for installation.    

> When #464 is implemented, you'll see such list in App Manager too.

That looks awesome, would solve all the issues!

> 
> > AppManager could be a unified place to see all requests to install apps, it's status, whether it is successful, how long does it take and so on.
> 
> Yes, App Manager can store a history of installation attempts. But this is not the same as displaying a queue like in the app stores. If this is what you want, you can open a feature requests for this so that I can look into this later.

Yes, installation attempts and whether it was successful. Perhaps it can be one of the steps in the direction of #464

Also, 

> This queue is handled automatically by Android Service.

Play Store is capable of showing a progress bar with installation progress. Does it use some privileged introspection mechanisms or is it just (while percent < 95%; percent+=5%; sleep 10)?

**Comment by MuntashirAkon** [comment]
> That is true, but the queue in fdroid and aurora isn't perfect (plus it's distributed across apps, plus you don't have it for direct APKs). They should do the job of queueing and tracking downloading, but then once they pass the installation request to the AppManager, AppManager could have its own queue only for installation.

This isn't how this process works. An app store is supposed to take care of queueing, downloading and installing – everything. They can keep track of the installation even if they pass it to an installer such as App Manager. If they don't do that, it is their problem and you can ask them to take care of it. I've abandoned the official F-Droid client long ago because it can't even detect installations properly and display false updates.

> Yes, installation attempts and whether it was successful. Perhaps it can be one of the steps in the direction of #464

Not quite. #464 is about app store, not the installer. Two are very different concepts in the sense that an installer only installs app from _any source_, and the app store is one of such sources.

> Play Store is capable of showing a progress bar with installation progress. Does it use some privileged introspection mechanisms or is it just (while percent < 95%; percent+=5%; sleep 10)?

The installation process is composed of several different parts:
1. Ask the OS to reserve an installer session
2. Copy APK files to the session
3. Commit the session
4. If user interaction is needed (i.e. asking user to approve the installation), wait for user confirmation, or cancel the session
5. If user approves, proceed to the next level, or cancel otherwise
6. If there exists a security mechanism apart from the basics, check the security of the APK files
7. If everything goes well, the app is finally installed.

The part where you can display progress is where the APK files are copied to the session (step 2). Steps 4-6 requires and indefinite amount of time depending on when the user confirms the installation and how long it takes for the security app to figure out if the app can be installed. Now, Google Play apps are often whitelisted in the ROMs. As a result they can install apps without user interaction (steps 4-5), and the security app is usually Google Play itself (step 6). So, they can take care of progress quite easily than the rests.

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.

**Comment by MuntashirAkon** [comment]
> Any suggestions?

You need to create a new issue along with the steps to reproduce the issue.

**Comment by MuntashirAkon** [comment]
You don't need to give an explanation as to why you didn't create another issue. When I asked you to create another issue with the steps to reproduce it, you should know that the issue might be different from the OP. Just to be clear, the OP's issue is about App Manager not clearing its own queue, which has already been fixed. There, the queue was created and maintained by the installer activity which didn't send the newly added item to the installer service if it was the last item in the queue.

> where is this 'queue'? It's not the Session/System Installer because everything is fine as long as AM is disabled.

There are three queues here, actually. The first is managed by the installer activity, the second is managed by the installer service, and the third, possibly the one that is causing your issue, is managed by the system in a per app basis. Since the system stores it in a per app basis, you can only see this issue when App Manager is being actively used by you. However, the exact reasons are unknown to me. This is where the steps to reproduce the issue helps. The “steps to reproduce the issue” involves sharing every detail that can consistently reproduce the issue. This includes any app or resources like the one you mentioned above.

I hope this helps you understand your situation. I don't write long comments like this anymore because I can't afford to spend much time with my projects. If I spend explaining every user what to do, I have to reduce the amount of time I can work on my projects (however, I am planning on discontinuing two more projects so that I can allocate more time to App Manager). This eventually leads more issues/features to remain unaddressed for a long time. So, it's better for a user to follow the advice instead of asking questions about it. I'd love to give an explanation, but I could no longer afford it.

**Comment by MuntashirAkon** [comment]
> Just concisely tell me, please, where (in the filesystem) the system keeps this queue on a per-app basis. I am rooted so I can delete some folders if need be.

Providing a solution like this may solve your issue. But it won't solve it in App Manager, and other users may face it again. The best way to fix it is to share everything that you did (AKA steps to reproduce the issue). You don't need to reproduce the issue, but I do, if I want to fix it.
