### ISSUE TITLE
I am against having an expiry date for AppManager and this is my ideas for a better solution (maybe)

### ISSUE THREAD

**Issue by Rustlang4Future** [MuntashirAkon/AppManager#954]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

I don't like having an expiry date for AppManager because in my threat model it doesn't provide a better security for me (and probably many others)

### Describe the solution you'd like

I am prepared a comment about this matter that it isn't completely in a format that I fill this forms properly but I try my hardest.

Probably it is better that I write is fully in alternative form below.

### Describe alternatives you've considered

I think having an expiry date and specially forcing the user to remove the app isn't a great approach.

Although I really pleased with the fact that you this much care about security of the users and am grateful for it. 

I like to say some use cases that the user probably won't get in danger of using an old version of AppManager.

Because of not so much good English and because I want to my comment be as clear as possible, I will use numbers.

1. Maybe a user just use AppManager in non-root mode that from what I think it doesn't possess real security risk.

2. You, yourself already use or had used F-droid classic that hadn't updated for years so using an old version of an app as long as the user be careful or it be compatible with the threat model of the user won't possess the user to real danger.

3. There are many other security issues that can expose user to risk than just AppManager like old android system webview and many more.

4. (And maybe my main point): 

Probably many users because of some reasons may already use old versions of Android and old version of apps so just not being able to use AppManager in that case won't have any more security enhancement to user. Specially if they use it in non-root mode.

Worse, some users may use molded apps (that is unfortunately common) and that fact is far more dangerous than using an old version of AppManager. 

7. Isn't it better that you make the AppManager to warn the user everytime after that expiry date ended and not force them to remove it?

Or in addition to that you can also force user to just they can use non-root mode and can't use other modes.

What do you think about my comment and the last alternative solution?

BTW, Thank you for this great app. It is a real life saver.

Best wishes.

### Additional context

Also there is a possibility that someone fork AppManager and remove those limitations and many users go to that fork.

The issue here can be two, one is bad and other is a disaster.

1. That person may just remove expiry limit.

2. That person may put suspicious code in the app and because AppManager gets powerful permissions in adb and root mode, that will be a disaster.

Best wishes.

**Comment by J4CKED** [comment]
I didn't know the app had a time limit. Does it work like Whatsapp? And after a certain amount of time it is impossible to use the app?
Of course, I am against it.

**Comment by MuntashirAkon** [comment]
> Does it work like Whatsapp? And after a certain amount of time it is impossible to use the app?

Yes.

> Of course, I am against it.

The question is not for/against anything. I am not a corporate entity deciding against the users, we should be clear on that. Rather I want the users to be safe from any potential harms that might be introduced by the app. However, as I've delicately put forward the reasoning behind the decision, the only sane way to divert me is to provide convincing justification as to why this should be a bad idea.

**Comment by J4CKED** [comment]
I will give a comparison like this. You buy a car that has 300HP, but for our safety, the government decides to limit it to 200HP.

**Comment by MuntashirAkon** [comment]
> I will give a comparison like this. You buy a car that has 300HP, but for our safety, the government decides to limit it to 200HP.

Well, a car and its driver require a government-issued license/ID as well as insurance. The obtaining a driving license requires that you know how to drive safely knowing the traffic rules, abide by the rules and are aware of the penalties in case they are broken. A driver, as a result, has to go through sufficient training to ensure that they have mastered enough before appearing in the exams. Even then, you have to renew the license after a few years in most countries. There is no such thing for an electronic device, apps or their user that would ensure that the user is not only aware of but also ensure the safety of their device in a world where data theft is ever so transparent (that is, hidden) and a common incident. This is why privacy-respecting apps are gradually introducing expiry dates. Among the front-ends (back-ends always have had expiry dates), Signal added it a long time ago to ensure the safety of the messages, Bromite only displays a warning because it has no control over the updates, and many others are trying to figure out the best way to implement it. This is usually done without any announcement because the user, in general, has nothing to be afraid of as long as the development is active (if it is no longer maintained, the users should not use it anymore no matter how useful it is). But I think you haven't read my early replies and commented only on the title of the issue.

**Comment by J4CKED** [comment]
Anyone can drive a car without a license. This can be done on a private road without fear of a fine. 
A private road is like a phone without internet access.
After all, I can use AppManager offline.

In the application it is enough to give a warning about the existing danger. People can read and think, if not then let them pay for their mistakes. 
I don't need someone to lead me by the hand and force me to update.
I still use the old QuickPic photo app.

I think this is a topic for conversation over a beer, because I feel that nothing and no one will convince you.
Merry Christmas :)

**Comment by MuntashirAkon** [comment]
@Rustlang4Future: What I do not understand, as I've already specified in the [second comment](https://github.com/MuntashirAkon/AppManager/issues/954#issuecomment-1347832067) if you've read it carefully, is why anybody should continue to use the old versions instead of the new ones.

Let me explain how support in App Manager works here. While this is quite common in a desktop environment, due to abstractions made by Google Play Store (and most people use Google Play Store), this is mostly unknown to the Android users unless they are familiar with the desktop environments.

We have several version lineups, as you can see in the docs, such as v2.5.x, v2.6.x, v3.0.x and (coming up) v3.1.x. We have discontinued support for v2.5.x this year because we have received only a single report in a year. This is what I [posted](https://t.me/AppManagerChannel/207) in the Telegram channel regarding the decision:

> **Important.**
>
> App Manager v2.5.x and earlier versions did not received any security updates for more than a year and should not be used.
>
> For root and ADB users, this is very crucial because today crackers like to exploit any vulnerabilities they can find, even if it is an app with a small number of users such as App Manager. App Manager has a very specific set of users which might entice them to find and exploit vulnerabilities in the app.
>
> **App Manager v2.6.5 and later are still supported** and patches will be released if critical vulnerabilities have been discovered. Since the release of v3.0.0 has been announced, no new features will be added to the v2.6.x version lineup.

With the release of v3.1.x next year, we are going to discontinue support for v2.6.x as we haven't received any reports from v2.6.x for many months.

Now, unstable releases (debug, RC, etc.) should not be used for longer periods as they are not made to sustain and may break anytime, and I think we all can agree on this point. The question would be whether we should add an expiry date to the stable releases. Although we have set up 18 + 3 months (one year and nine months as the expiry date), statistics suggest that most users move to the next version of the app in much less time. A few others may not move due to the fact that they haven't used the app for quite some time.

However, there will always be a few people who would prefer an older version for no real reason. For example, a user told me that they still use v2.5.23 because the backup feature worked quite fast and asked me to revert the new changes and reimplement it. However, they failed to realise that the feature worked fast because it was not making a perfect backup of the app data which was fixed in the subsequent release and, thereby, slowing down the backup process. Now, backups can be made faster in many ways as put forward by some users and I gracefully considered their idea and design methods, and I am still working on a good solution to the feature. So, in this case, the former who asked me to support v2.5.23 was communicating their needs in a manner that cannot be done (a victim of the xy problem), and the latter users addressed real issues and possible solutions to the issue. (The latter is how anything develops and persists in an open source environment (or in a real society).)

I hope this makes things even more clear to you regarding this seemingly non-feature.

> BTW, I tried to explain the use cases for users that have a disconnected phone like me.

What is the possible use-cases of App Manager in a disconnected phone (that is, a fully offline phone, not just using App Manager offline which doesn't really work in Android as you might be well aware)? The features offered and to be offered by App Manager are mostly for a connected phone.

**Comment by MuntashirAkon** [comment]
> I think this is a topic for conversation over a beer, because I feel that nothing and no one will convince you.

This surely shall not convince me :)

**Comment by MuntashirAkon** [comment]
Added in c698ccf622edcaaeceba5b9e81dc4145e62682f5 with the following limitation:

The dialog will still be displayed when user launches the app, but in stable releases, there will now be a **continue** button which will let users continue using the app without updating it.

**Comment by leao-nardo** [comment]
wait what ? so, theres expiry date for thew app . 
really, theres no place for this in a floss app . thats an anti feature.
glad it seem solved . 
such a thing sohuld never even be considered for any app . especially a libre floss one .
no machine ,software, system, not anything should be designed like that.

dont even start losing time ,guessing(or wanting to control) what device and how old people "should" /can use or not . 

every single point here holds true.

**Comment by leao-nardo** [comment]
> I will give a comparison like this. You buy a car that has 300HP, but for our safety, the government decides to limit it to 200HP.

more like selling you a car and then taking away from you after 2 or 3 years . totally unreasonable.

**Comment by MuntashirAkon** [comment]
Having an expiry date is not an anti-feature. This is analogous to having an expiry date for a TLS certificate. Every app in Android is signed with a signing key, which has an expiry date. To avoid signature mismatch on the user end, the expiry date is usually set to 20 years from the day it was created. To enforce proper security, therefore, additional improvisation is needed.

Free and open source software allows you to modify the software you use as you choose. It's perfectly fine if you do not want to have a expiry date (you life choices are your own). But just make sure not to involve me or this project. We have an obligation to ensure that the users of App Manager are safe (since privacy and security is our top priority), and we intend to stick to it.
