### ISSUE TITLE
Cannot clear cache with AM debug

### ISSUE THREAD

**Issue by Kimphunh** [MuntashirAkon/AppManager#962]
I love using this app to clear app data,it so easy,but it cant clear cache
Fix it pls
### **More Info**
Device:Vsmart
Android 11
Adb mode
Version:lastest Am debug

**Comment by MuntashirAkon** [comment]
Very weird issue. For some reason, the system get stuck forever.

**Comment by MuntashirAkon** [comment]
Very weird behaviour. It works perfectly well using the `am` command, but it stuck when it's triggered using `ActivityManager` service.

**Comment by MuntashirAkon** [comment]
Since Android 9, clearing cache for individual app using system API [requires](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/core/java/com/android/server/pm/PackageManagerService.java;l=4651;drc=6aba151873bfae198ef9eceb10f943e18b52d58c) `android.permission.INTERNAL_DELETE_CACHE_FILES` permission which is not available to `shell` UID. Hence, the feature has been disabled. According to the source code (linked above), system API clears caches from `/data/user`, `/data/user_de` and `/sdcard/Android/data` paths for the particular package and user. Although it's possible to clear caches from `/sdcard/Android/data` manually, saying it “Clear cache” might be misleading since it does not clear caches from the former two directories. But I can compromise on the terminology if the ADB users want this feature any way (in that case, you need to open a new _feature request_).
