### ISSUE TITLE
Can not uninstall 

### ISSUE THREAD

**Issue by GTee75** [MuntashirAkon/AppManager#990]
### Describe the existing feature/documentation

Problems with App Manager, latest version (problems existed on previous version also, hoped update would rectify) running on Android 10 with UI 2.5.

Un rooted S9. 

### Describe your problem(s)

When trying to uninstall, either using standard Android menu or via FDroids 'Manage Installed Apps' the Package Installer crashes giving the usual ' i   App info' or 'x    Close App'. Nightmare.

Also, in my browser, no defaults set nor in App Manager, when trying to play certain video media Interceptor kicks in and stops progress leaving me unable to view chosen media.

### Additional context

Had also tried in the previous version(s) to uninstall  so that I can reinstall in Work profile but will not happen, get the exact same 'Package Installer' crash.

Device is unrooted S9, Android 10, One UI 2.5.

Please help

**Comment by MuntashirAkon** [comment]
See the solution in #989. Can you, perhaps, share the crash log with us? A lot of people report such issues but nobody ever shared the crash log so that we can actually figure out the real cause of the crash. For example, for Lineage OS 17.1 with OpenGapps, we know that SD Card causes the crash (and they fixed it in the latest version).

**Comment by GTee75** [comment]
Dear Muntashir,

Apologies for not replying sooner and I see you would like a Crash Report
for your App Manager app, Android, as I am having uninstall problems.

If you would explain how I get one of these crash reports I would be happy
to cooy and paste and forward to you.

Yours

Gareth
