### ISSUE TITLE
AppManager seems to have hijacked the email intent on my device. 

### ISSUE THREAD

**Issue by bagarwa** [MuntashirAkon/AppManager#997]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AppManager seems to have hijacked the email intent on my device. 

In some apps, when I initiate an action that will send an email to the app's developer, AppManager is intercepting that action, instead of the default email app of my device. 

[Screenshot](https://i.imgur.com/jmZKH5x.png).

Here, when I click "Send edited intent", then I'm able to select my email app and the content the original app intended to send shows up in the mail's compose window.

But, if I freeze or uninstall AppManager, the system starts acting like there's no email app set up and the system doesn't know how to handle android.intent.action.SEND. For example, in some apps, when I initiate an action that will send an email to the app's developer, it throws error saying "Set up an email app".

### To Reproduce

**Steps for when AppManager is installed and enabled.**
 
1. Install the AppManager app and grant it root permission "forever". 
2. Install and set up any email app, like GMail.
3. Launch 1Password app, set up and unlock it. 
4. Go to 1Password settings -> help -> send diagnostics. 
5. Instead of opening the email app, it gets intercepted by AppManager. [Screenshot](https://i.imgur.com/jmZKH5x.png).
6. Tap "Send edited intent" button and choose the email app from the floating window. Email content will open in email app's compose window. 

**Steps for when AppManager is uninstalled or frozen / disabled.**

1. Install the AppManager app and grant it root permission "forever". 
2. Install and set up any email app, like GMail.
3. Freeze / Disable or Uninstall AppManager app. 
4. Launch 1Password app, set up and unlock it. 
5. Go to 1Password settings -> help -> send diagnostics. 
6. It throws an error saying "Set up an email app" - "To send a diagnostic report, you will need to set up an email app on this device first."

### Expected behavior

I don't want AppManager to intercept these. At the minimum, there should be a setting that enables / disables AppManager intercepting these send email action.

Also, when I freeze or uninstall AppManager, it should revert whatever changes it has made at system level; or at least ask the user whether they want to revert those changes. So that the system doesn't keep failing like I described above.

### Screenshots

https://i.imgur.com/jmZKH5x.png

### Device info

- Device: Pixel 7 Pro
- OS Version: Android 14 DP1
- App Manager Version: v3.0.4
- Mode: Root

### Additional context

This was not an issue when I had not installed AppManager ever. Before the very first time that I installed AppManager, I was able to tap "send diagnostics" in 1Password and it used to directly open the email app. Only after I installed AppManager, this issue has started.

Surprisingly, it is not happening in all apps. For example, when I tap "contact us" button in F-Stop Gallery app, that directly opens the email app - no matter whether AppManager is installed or not.

**Comment by MuntashirAkon** [comment]
App Manager \*doesn't\* (and can't) hijack anything via Intent intercept because:

1. It doesn't use root to intercept activities. (You can't actually use root to intercept activities, you'd need complicated injections via Xposed, for example.)
2. It uses a bunch of known intent filters to intercept activities which is why it appears in most of the cases, and it would appear on the top of the matching activities only when there are no other matching activities.

This can happen due to many reasons (in order of likelihood):

1. In Android 13 and later, an Intent has to contain all the required fields needed by the target app. The caller app didn't create the Intent properly which made Interceptor the only matching activity due to the restrictions introduced. You can test this by downgrading the target app to a version that targeted SDK 32 or earlier.
2. Same as 1, but in reverse. The target app may have skipped some traditionally used Intent filters which resulted in the same issue.
3. You've accidentally made the Interceptor the default activity for the app.
4. Bug in your OS, highly unlikely but not impossible.

**Comment by bagarwa** [comment]
Thanks for the detailed explainer. I've also posted this in the 1Password's community, in case its an issue from their end. I'll update here if/when I hear anything from them.

**Comment by MuntashirAkon** [comment]
> Also, when I freeze or uninstall AppManager, it should revert whatever changes it has made at system level; or at least ask the user whether they want to revert those changes. So that the system doesn't keep failing like I described above.

When you uninstall a user app, it's simply removed from your device (unless you have it installed in another profile). There's no way for the app to know that it's being uninstalled. App Manager offers some interesting features, but it still has no control over the system so as to revert the system back to some previously saved snapshots. Still, it offers the users to revert back some rules in settings.
